language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install gfortran libeigen3-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
