language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libeigen3-dev
      - gfortran
  homebrew:
    packages:
      - eigen
      - gcc
    update: true
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
