(oneLoopFlag*(-16*(lmMst1 + lmMst2 - 2*lmMt)*pow(Mt,4) + 
       ((2 + lmMst1 - lmMst2)*pow(Mst1,4) - 
          4*pow(Mst1,2)*pow(Mst2,2) + 
          (2 - lmMst1 + lmMst2)*pow(Mst2,4))*pow(s2t,4) + 
       4*pow(Mt,2)*pow(s2t,2)*
        (-2*(lmMst1 - lmMst2)*pow(Mst1,2) + 
          2*(lmMst1 - lmMst2)*pow(Mst2,2) + 
          ((-2*pow(Mst2,4) + 
               lmMst1*(2*pow(Mst1,4) + 
                  2*pow(Mst1,2)*pow(Mst2,2) + pow(Mst2,4)) - 
               lmMst2*(2*pow(Mst1,4) + 2*pow(Mst1,2)*pow(Mst2,2) + 
                  pow(Mst2,4)))*pow(MuSUSY,2)*(-1 + pow(Sbeta,2)))/
           (pow(Mst2,4)*pow(Sbeta,2))) - 
       (16*(lmMst1 - lmMst2)*pow(Mt,3)*MuSUSY*s2t)/Tbeta + 
       (4*((2 + lmMst1 - lmMst2)*pow(Mst1,2) + 
            (-2 + lmMst1 - lmMst2)*pow(Mst2,2))*Mt*MuSUSY*pow(s2t,3))/
        Tbeta))/32. + (Al4p*twoLoopFlag*
     ((9*pow(s2t,4)*(8*Dmglst1*Mgl*
             ((-1 + lmMst1)*pow(Mst2,4) + 
               pow(Mst1,4)*
                (-3 - 2*lmMst1 + pow(lmMst1,2) + lmMst2 - 
                  pow(lmMst2,2) - 2*z2) + 
               pow(Mst1,2)*pow(Mst2,2)*
                (2 - 2*lmMst1 - pow(lmMst1,2) + lmMst2 + 
                  pow(lmMst2,2) + 2*z2)) + 
            4*pow(Dmglst1,2)*
             ((-4 + 3*lmMst1)*pow(Mst2,4) + 
               3*pow(Mst1,4)*
                (-4 - 4*lmMst1 + pow(lmMst1,2) + 3*lmMst2 - 
                  pow(lmMst2,2) - 2*z2) + 
               3*pow(Mst1,2)*pow(Mst2,2)*
                (4 - 2*lmMst1 - pow(lmMst1,2) + lmMst2 + 
                  pow(lmMst2,2) + 2*z2)) + 
            pow(Mgl,2)*(pow(Mst1,4)*
                (13 + 12*pow(lmMst1,2) + lmMst1*(26 - 8*lmMst2) - 
                  14*lmMst2 - 4*pow(lmMst2,2) - 4*z2) - 
               4*pow(Mst2,4)*
                (-7 - 7*lmMst2 - 2*pow(lmMst2,2) + 
                  2*lmMst1*(1 + lmMst2) + z2) + 
               4*pow(Mst1,2)*pow(Mst2,2)*
                (-12 + pow(lmMst1,2) - 3*lmMst2 + 3*pow(lmMst2,2) - 
                  2*lmMst1*(3 + 2*lmMst2) + 2*z2))))/pow(Mgl,2) + 
       (32*pow(Mt,4)*(2*pow(Dmglst1,2)*
             ((151 + 51*lmMt + 18*lmMst2*(1 + lmMt) - 
                  3*lmMst1*(23 + 6*lmMt))*Mst1*pow(Mst2,2)*MuSUSY + 
               27*(1 + lmMt)*pow(Mst1,2)*pow(Mst2,2)*Tbeta + 
               (-11 + 21*lmMst1 + 6*lmMt)*pow(Mst2,4)*Tbeta + 
               pow(Mst1,3)*MuSUSY*
                (151 - 108*pow(lmMst2,2) + 
                  3*lmMst1*(-23 + 36*lmMst2 - 42*lmMt) + 177*lmMt + 
                  18*lmMst2*(-6 + 7*lmMt) - 216*z2) + 
               9*pow(Mst1,4)*Tbeta*
                (-9 - 10*pow(lmMst2,2) + 
                  10*lmMst1*(1 + lmMst2 - lmMt) + 19*lmMt + 
                  lmMst2*(-29 + 10*lmMt) - 20*z2)) - 
            9*pow(Mgl,2)*(-4*
                (2 + lmMst2 + lmMt + lmMst2*lmMt - lmMst1*(2 + lmMt))*
                Mst1*pow(Mst2,2)*MuSUSY - 
               2*(1 + lmMt)*pow(Mst1,2)*pow(Mst2,2)*Tbeta + 
               (3 + lmMst1 + pow(lmMst1,2) + pow(lmMst2,2) - 
                  lmMt + 2*lmMst1*lmMt - 6*pow(lmMt,2) + 
                  2*lmMst2*(1 + lmMt))*pow(Mst2,4)*Tbeta - 
               2*pow(Mst1,4)*Tbeta*
                (-pow(lmMst2,2) + lmMst1*(1 + lmMst2 - lmMt) + 
                  lmMst2*(-2 + lmMt) + lmMt - 2*z2) - 
               4*pow(Mst1,3)*MuSUSY*
                (2 + lmMst2 - pow(lmMst2,2) + lmMt + 2*lmMst2*lmMt + 
                  lmMst1*(lmMst2 - 2*(1 + lmMt)) - 2*z2)) + 
            2*Dmglst1*Mgl*(18*
                (5 + lmMst2 + 2*lmMt + lmMst2*lmMt - lmMst1*(3 + lmMt))*
                Mst1*pow(Mst2,2)*MuSUSY + 
               18*(1 + lmMt)*pow(Mst1,2)*pow(Mst2,2)*Tbeta + 
               (1 + 12*lmMst1 + 6*lmMt)*pow(Mst2,4)*Tbeta + 
               18*pow(Mst1,4)*Tbeta*
                (-1 - 5*lmMst2 - 2*pow(lmMst2,2) + 
                  2*lmMst1*(1 + lmMst2 - lmMt) + 3*lmMt + 
                  2*lmMst2*lmMt - 4*z2) - 
               18*pow(Mst1,3)*MuSUSY*
                (-5 + lmMst2 + 3*pow(lmMst2,2) - 4*lmMt - 
                  4*lmMst2*lmMt + lmMst1*(3 - 3*lmMst2 + 4*lmMt) + 6*z2)))
)/(pow(Mgl,2)*pow(Mst2,4)*Tbeta) - 
       (36*Mt*pow(s2t,3)*(pow(Mgl,2)*
             ((-7 + 16*pow(lmMst1,2) + 2*lmMst2 + 
                  16*pow(lmMst2,2) - 2*lmMst1*(3 + 16*lmMst2))*
                pow(Mst1,4)*MuSUSY - 
               2*(3 + 2*lmMst1 - 2*lmMst2)*pow(Mst1,5)*Tbeta + 
               4*Mst1*pow(Mst2,4)*Tbeta*
                (-8 + 2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                  pow(lmMst2,2) - 2*z2) - 
               4*pow(Mst2,4)*MuSUSY*
                (-7 - 7*lmMst2 - 2*pow(lmMst2,2) + 
                  2*lmMst1*(1 + lmMst2) + z2) + 
               4*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*
                (-5 + pow(lmMst1,2) + 4*lmMst2 + 5*pow(lmMst2,2) - 
                  2*lmMst1*(4 + 3*lmMst2) + z2) + 
               4*pow(Mst1,3)*pow(Mst2,2)*Tbeta*
                (10 + 3*pow(lmMst1,2) - 4*lmMst1*(-2 + lmMst2) - 
                  4*lmMst2 + pow(lmMst2,2) + 2*z2)) - 
            2*Dmglst1*Mgl*(4*(2 + 3*lmMst1 - 2*lmMst2)*pow(Mst1,4)*
                MuSUSY - 4*(-1 + lmMst1)*pow(Mst2,4)*MuSUSY + 
               (19 + 18*lmMst1 - 18*lmMst2)*pow(Mst1,5)*Tbeta + 
               4*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*
                (-1 + lmMst1 + pow(lmMst1,2) - lmMst2 - 
                  pow(lmMst2,2) - 2*z2) + 
               2*Mst1*pow(Mst2,4)*Tbeta*
                (12 - 2*lmMst1 - pow(lmMst1,2) + 6*lmMst2 + 
                  pow(lmMst2,2) + 2*z2) - 
               2*pow(Mst1,3)*pow(Mst2,2)*Tbeta*
                (14 + 7*pow(lmMst1,2) + lmMst1*(4 - 12*lmMst2) + 
                  5*pow(lmMst2,2) + 10*z2)) - 
            2*pow(Dmglst1,2)*
             (2*(4 + 15*lmMst1 - 12*lmMst2)*pow(Mst1,4)*MuSUSY + 
               2*(4 - 3*lmMst1)*pow(Mst2,4)*MuSUSY + 
               (43 + 66*lmMst1 - 66*lmMst2)*pow(Mst1,5)*Tbeta + 
               2*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*
                (-8 + 3*lmMst1 + 3*pow(lmMst1,2) - 3*lmMst2 - 
                  3*pow(lmMst2,2) - 6*z2) + 
               2*Mst1*pow(Mst2,4)*Tbeta*
                (16 - 2*lmMst1 - pow(lmMst1,2) + 6*lmMst2 + 
                  pow(lmMst2,2) + 2*z2) - 
               2*pow(Mst1,3)*pow(Mst2,2)*Tbeta*
                (30 + 13*pow(lmMst1,2) + 14*lmMst2 + 
                  11*pow(lmMst2,2) - 2*lmMst1*(5 + 12*lmMst2) + 22*z2)))
)/(pow(Mgl,2)*pow(Mst2,2)*Tbeta) + 
       12*pow(Mt,2)*pow(s2t,2)*
        (-12*(-2 + 3*pow(lmMst1,2) - 2*lmMst1*(-1 + lmMst2) - 
             6*lmMst2 - pow(lmMst2,2))*pow(Mst1,2) - 
          (24*(1 + lmMst1)*pow(Mst1,4))/pow(Mst2,2) + 
          12*(pow(lmMst1,2) + 2*lmMst1*(1 + lmMst2) - 
             lmMst2*(4 + 3*lmMst2))*pow(Mst2,2) - 
          (4*pow(Dmglst1,2)*
             (6*(-6 + 10*lmMst1 - 7*lmMst2)*pow(Mst1,4) - 
               (1 + 18*lmMst1 + 18*lmMst2)*pow(Mst1,2)*pow(Mst2,2) + 
               (-17 + 18*lmMst1)*pow(Mst2,4)))/
           (pow(Mgl,2)*pow(Mst2,2)) - 
          (24*Dmglst1*(-((pow(Mst1,2) + pow(Mst2,2))*
                  (2*lmMst2*pow(Mst1,2) + pow(Mst2,2))) + 
               2*lmMst1*(2*pow(Mst1,4) - pow(Mst1,2)*pow(Mst2,2) + 
                  pow(Mst2,4))))/(Mgl*pow(Mst2,2)) + 
          (3*pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
             (8*Dmglst1*Mgl*(-((-1 + lmMst1)*pow(Mst2,4)) + 
                  pow(Mst1,4)*
                   (2 + 3*lmMst1 + pow(lmMst1,2) - 3*lmMst2 - 
                     pow(lmMst2,2) - 2*z2) + 
                  pow(Mst1,2)*pow(Mst2,2)*
                   (pow(lmMst1,2) - lmMst2 - pow(lmMst2,2) - 2*z2)) 
- 4*pow(Dmglst1,2)*(4*pow(Mst1,2)*pow(Mst2,2) - 4*pow(Mst2,4) - 
                  3*pow(lmMst1,2)*pow(Mst1,2)*
                   (pow(Mst1,2) + pow(Mst2,2)) + 
                  3*pow(lmMst2,2)*pow(Mst1,2)*
                   (pow(Mst1,2) + pow(Mst2,2)) + 
                  3*lmMst2*pow(Mst1,2)*
                   (5*pow(Mst1,2) + pow(Mst2,2)) + 
                  3*lmMst1*(-5*pow(Mst1,4) + pow(Mst2,4)) + 
                  6*pow(Mst1,4)*z2 + 6*pow(Mst1,2)*pow(Mst2,2)*z2) 
- pow(Mgl,2)*((1 + 20*pow(lmMst1,2) + 46*lmMst2 + 
                     44*pow(lmMst2,2) - 2*lmMst1*(23 + 32*lmMst2))*
                   pow(Mst1,4) + 
                  4*(2 + pow(lmMst1,2) + 11*lmMst2 + 
                     7*pow(lmMst2,2) - 2*lmMst1*(5 + 4*lmMst2))*
                   pow(Mst1,2)*pow(Mst2,2) - 
                  4*pow(Mst2,4)*
                   (-7 - 7*lmMst2 - 2*pow(lmMst2,2) + 
                     2*lmMst1*(1 + lmMst2) + z2))))/
           (pow(Mgl,2)*pow(Mst2,4)*pow(Sbeta,2)) + 
          (18*Mst1*MuSUSY*(pow(Mgl,2)*
                ((1 + 8*pow(lmMst1,2) + lmMst1*(18 - 8*lmMst2) - 
                     18*lmMst2)*pow(Mst1,4) + 
                  4*(1 + 2*pow(lmMst1,2) + lmMst1*(5 - 2*lmMst2) - 
                     5*lmMst2)*pow(Mst1,2)*pow(Mst2,2) + 
                  2*pow(Mst2,4)*
                   (-8 + 2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                     pow(lmMst2,2) - 2*z2)) + 
               Dmglst1*Mgl*(4*pow(Mst1,2)*pow(Mst2,2)*
                   (1 + 4*pow(lmMst1,2) + lmMst1*(3 - 6*lmMst2) - 
                     3*lmMst2 + 2*pow(lmMst2,2) + 4*z2) + 
                  pow(Mst1,4)*
                   (-15 + 16*pow(lmMst1,2) + 6*lmMst2 + 
                     8*pow(lmMst2,2) - 6*lmMst1*(1 + 4*lmMst2) + 16*z2
) + 2*pow(Mst2,4)*(2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                     pow(lmMst2,2) - 2*(6 + z2))) + 
               pow(Dmglst1,2)*
                (4*pow(Mst1,2)*pow(Mst2,2)*
                   (7 + 7*pow(lmMst1,2) + 4*lmMst2 + 
                     5*pow(lmMst2,2) - 4*lmMst1*(1 + 3*lmMst2) + 10*z2) 
+ pow(Mst1,4)*(-15 + 28*pow(lmMst1,2) + 82*lmMst2 + 
                     20*pow(lmMst2,2) - 2*lmMst1*(41 + 24*lmMst2) + 
                     40*z2) + 
                  2*pow(Mst2,4)*
                   (2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                     pow(lmMst2,2) - 2*(8 + z2)))))/
           (pow(Mgl,2)*pow(Mst2,4)*Tbeta)) - 
       (32*pow(Mt,3)*s2t*(-9*pow(Mgl,2)*
             (pow(lmMst1,2)*MuSUSY*
                (2*pow(Mst1,4)*pow(Sbeta,2) + 
                  2*pow(Mst1,2)*pow(Mst2,2)*pow(Sbeta,2) - 
                  pow(Mst2,4)*pow(Sbeta,2) + 
                  5*pow(Mst1,3)*MuSUSY*(-1 + pow(Sbeta,2))*Tbeta + 
                  Mst1*pow(Mst2,2)*MuSUSY*(-1 + pow(Sbeta,2))*Tbeta) 
+ pow(lmMst2,2)*(2*pow(Mst1,4)*MuSUSY*pow(Sbeta,2) + 
                  2*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*pow(Sbeta,2) + 
                  3*pow(Mst2,4)*MuSUSY*pow(Sbeta,2) + 
                  4*pow(Mst1,5)*pow(Sbeta,2)*Tbeta - 
                  Mst1*pow(Mst2,2)*pow(MuSUSY,2)*
                   (-1 + pow(Sbeta,2))*Tbeta + 
                  pow(Mst1,3)*
                   (pow(MuSUSY,2) + 4*pow(Mst2,2)*pow(Sbeta,2) - 
                     pow(MuSUSY,2)*pow(Sbeta,2))*Tbeta) - 
               2*lmMst2*(pow(Mst1,4)*MuSUSY*pow(Sbeta,2) + 
                  pow(Mst1,2)*pow(Mst2,2)*MuSUSY*pow(Sbeta,2) - 
                  2*pow(Mst2,4)*MuSUSY*pow(Sbeta,2) + 
                  (-5 + 2*lmMt)*pow(Mst1,5)*pow(Sbeta,2)*Tbeta + 
                  Mst1*pow(Mst2,2)*
                   ((1 + 2*lmMt)*pow(Mst2,2)*pow(Sbeta,2) + 
                     3*pow(MuSUSY,2)*(-1 + pow(Sbeta,2)))*Tbeta + 
                  pow(Mst1,3)*
                   ((-1 + 2*lmMt)*pow(Mst2,2)*pow(Sbeta,2) + 
                     8*pow(MuSUSY,2)*(-1 + pow(Sbeta,2)))*Tbeta) - 
               2*lmMst1*((-1 + 2*lmMst2)*pow(Mst1,4)*MuSUSY*
                   pow(Sbeta,2) + 
                  2*lmMst2*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*
                   pow(Sbeta,2) + 
                  (1 + lmMst2)*pow(Mst2,4)*MuSUSY*pow(Sbeta,2) + 
                  (5 + 2*lmMst2 - 2*lmMt)*pow(Mst1,5)*pow(Sbeta,2)*
                   Tbeta - Mst1*pow(Mst2,2)*
                   ((3 + 2*lmMt)*pow(Mst2,2)*pow(Sbeta,2) + 
                     pow(MuSUSY,2)*(-1 + pow(Sbeta,2)))*Tbeta + 
                  pow(Mst1,3)*
                   ((1 + 2*lmMst2 - 2*lmMt)*pow(Mst2,2)*
                      pow(Sbeta,2) + 
                     2*(-3 + lmMst2)*pow(MuSUSY,2)*
                      (-1 + pow(Sbeta,2)))*Tbeta) - 
               2*Mst1*(Mst1*pow(Mst2,2)*MuSUSY*pow(Sbeta,2) - 
                  4*pow(Mst1,4)*pow(Sbeta,2)*Tbeta*(-1 + z2) + 
                  pow(Mst1,2)*Tbeta*
                   (-4*pow(Mst2,2)*pow(Sbeta,2)*z2 + 
                     pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*(3 + z2)) + 
                  pow(Mst2,2)*Tbeta*
                   ((3 + 2*lmMt)*pow(Mst2,2)*pow(Sbeta,2) + 
                     pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*(4 + z2)))) + 
            9*Dmglst1*Mgl*(4*(1 - 2*lmMst1 + 2*lmMst2)*pow(Mst1,4)*
                MuSUSY*pow(Sbeta,2) + 
               4*(1 + lmMst2)*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*
                pow(Sbeta,2) + 
               2*(1 - 2*lmMst1)*pow(Mst2,4)*MuSUSY*pow(Sbeta,2) + 
               2*pow(Mst1,5)*pow(Sbeta,2)*Tbeta*
                (10 - 10*pow(lmMst2,2) + 
                  5*lmMst1*(5 + 2*lmMst2 - 2*lmMt) + 4*lmMt + 
                  lmMst2*(-29 + 10*lmMt) - 20*z2) + 
               pow(Mst1,3)*Tbeta*
                (2*pow(Mst2,2)*pow(Sbeta,2)*
                   (-2 - 6*pow(lmMst2,2) + 
                     lmMst1*(3 + 6*lmMst2 - 6*lmMt) + 4*lmMt + 
                     lmMst2*(-7 + 6*lmMt) - 12*z2) - 
                  pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
                   (-10 + 9*pow(lmMst1,2) + lmMst1*(8 - 12*lmMst2) - 
                     12*lmMst2 + 3*pow(lmMst2,2) + 6*z2)) + 
               Mst1*pow(Mst2,2)*Tbeta*
                (2*(8 + lmMst2 + 4*lmMt + 2*lmMst2*lmMt - 
                     lmMst1*(5 + 2*lmMt))*pow(Mst2,2)*pow(Sbeta,2) - 
                  pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
                   (2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                     pow(lmMst2,2) - 2*(6 + z2)))) + 
            pow(Dmglst1,2)*(-18*(-9 + 10*lmMst1 - 10*lmMst2)*
                pow(Mst1,4)*MuSUSY*pow(Sbeta,2) + 
               54*(1 + lmMst2)*pow(Mst1,2)*pow(Mst2,2)*MuSUSY*
                pow(Sbeta,2) + 
               3*(17 - 18*lmMst1)*pow(Mst2,4)*MuSUSY*pow(Sbeta,2) + 
               18*pow(Mst1,5)*pow(Sbeta,2)*Tbeta*
                (5 - 30*pow(lmMst2,2) + 
                  15*lmMst1*(5 + 2*lmMst2 - 2*lmMt) + 22*lmMt + 
                  lmMst2*(-97 + 30*lmMt) - 60*z2) - 
               9*pow(Mst1,3)*Tbeta*
                (pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
                   (-2 + 15*pow(lmMst1,2) + 2*lmMst2 + 
                     9*pow(lmMst2,2) - 6*lmMst1*(1 + 4*lmMst2) + 18*z2) 
+ 2*pow(Mst2,2)*pow(Sbeta,2)*
                   (7 + 12*pow(lmMst2,2) - 
                     6*lmMst1*(1 + 2*lmMst2 - 2*lmMt) - 14*lmMt - 
                     4*lmMst2*(-5 + 3*lmMt) + 24*z2)) + 
               Mst1*pow(Mst2,2)*Tbeta*
                ((251 + 102*lmMt + 18*lmMst2*(1 + 2*lmMt) - 
                     12*lmMst1*(10 + 3*lmMt))*pow(Mst2,2)*pow(Sbeta,2) 
- 9*pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
                   (2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                     pow(lmMst2,2) - 2*(8 + z2))))))/
        (pow(Mgl,2)*pow(Mst2,4)*pow(Sbeta,2)*Tbeta)))/216. + 
  pow(Al4p,2)*threeLoopFlag*((pow(Mt,4)*
        (10501 - 4920*lmMsq + 1980*pow(lmMsq,2) + 360*pow(lmMsq,3) - 
          784*lmMst1 - 1080*lmMsq*lmMst1 - 540*pow(lmMsq,2)*lmMst1 + 
          1914*pow(lmMst1,2) - 750*pow(lmMst1,3) + 2682*lmMst2 + 
          900*lmMsq*lmMst2 - 540*pow(lmMsq,2)*lmMst2 + 
          684*lmMst1*lmMst2 + 18*pow(lmMst2,2) - 
          342*lmMst1*pow(lmMst2,2) - 204*pow(lmMst2,3) - 462*lmMt - 
          3780*lmMsq*lmMt - 2652*lmMst1*lmMt + 1080*lmMsq*lmMst1*lmMt + 
          774*pow(lmMst1,2)*lmMt - 3564*lmMst2*lmMt + 
          1080*lmMsq*lmMst2*lmMt + 684*lmMst1*lmMst2*lmMt - 
          522*pow(lmMst2,2)*lmMt + 3024*pow(lmMt,2) - 
          1080*lmMsq*pow(lmMt,2) - 3132*lmMst1*pow(lmMt,2) - 
          1836*lmMst2*pow(lmMt,2) + 4968*pow(lmMt,3) + 4704*z2 + 
          4320*lmMsq*z2 - 1332*lmMst1*z2 - 2988*lmMt*z2 + 
          (1080*pow(Msq,2)*(-1 + shiftst2)*(-1 + 2*lmMsq + 2*z2))/
           pow(Mst2,2) + (81*pow(Mst2,4)*
             (-14.682624986502537 + (38*pow(lmMsq,2))/21. - 
               (32*pow(lmMst2,2))/21. + 
               lmMsq*(7.439002267573696 - (2*lmMst2)/7. - (10*lmMt)/3.) + 
               (5*lmMt)/2. + lmMst2*(-9.939002267573697 + (10*lmMt)/3.) + 
               (20*z2)/3.))/pow(Msq,4) + 
          (4*pow(Mst2,2)*(-13517 + 3150*pow(lmMsq,2) - 
               1350*pow(lmMst2,2) + 6000*lmMt + 
               30*lmMst2*(-241 + 150*lmMt) - 
               30*lmMsq*(-41 + 60*lmMst2 + 150*lmMt) + 9000*z2))/
           (25.*pow(Msq,2)) + 
          (108*(10*pow(Msq,2)*(-1 + shiftst1)*(-1 + 2*lmMsq + 2*z2) + 
               pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2)))/
           pow(Mst1,2) - 11736*z3 + 432*lmMst1*z3 + 432*lmMst2*z3 - 
          864*lmMt*z3 + 81*pow(Mst1,4)*
           ((100*(-11 + 6*lmMsq - 6*lmMt))/
              (27.*pow(Msq,2)*pow(Mst2,2)) + 
             (-57.89250152971241 + (1234*pow(lmMsq,2))/63. - 
                (32*pow(lmMst1,2))/21. - (275*lmMst2)/54. + 
                lmMsq*(33.36492819349962 - (788*lmMst1)/63. - 
                   (50*lmMst2)/9. - (190*lmMt)/9.) + (205*lmMt)/54. + 
                (50*lmMst2*lmMt)/9. + 
                lmMst1*(-32.068631897203325 + (140*lmMt)/9.) + 
                (380*z2)/9.)/pow(Msq,4) + 
             (-608.1924559142881 - (380*pow(lmMst1,3))/27. - 
                (6582874*lmMst2)/33075. - (88582*pow(lmMst2,2))/945. - 
                (580*pow(lmMst2,3))/27. + (899*lmMt)/9. - 
                (526*lmMst2*lmMt)/3. - (128*pow(lmMst2,2)*lmMt)/9. + 
                (64*pow(lmMt,2))/3. + (64*lmMst2*pow(lmMt,2))/3. + 
                (4*pow(lmMst1,2)*(-8128 + 8295*lmMst2 + 1680*lmMt))/
                 945. - (9532*z2)/27. - (1640*lmMst2*z2)/9. - 
                (400*lmMt*z2)/9. + 
                (40*lmMsq*(2 + 12*lmMst2 + 5*pow(lmMst2,2) - 
                     5*lmMst1*(1 + lmMst2 - lmMt) - 7*lmMt - 
                     5*lmMst2*lmMt + 10*z2))/3. + 
                lmMst1*(-57.30464096749811 + (33734*lmMst2)/945. + 
                   (4*pow(lmMst2,2))/9. + (718*lmMt)/3. + 
                   (64*lmMst2*lmMt)/9. - (64*pow(lmMt,2))/3. + 
                   (632*z2)/9.) + (2536*z3)/9.)/pow(Mst2,4)) + 
          (pow(Mst1,2)*(5625*pow(Mst2,4)*
                (-115 + 36*pow(lmMsq,2) + 21*lmMt - 
                  12*lmMsq*(-4 + 3*lmMst2 + 3*lmMt) + 
                  lmMst2*(-69 + 36*lmMt) + 72*z2) + 
               180*pow(Msq,2)*pow(Mst2,2)*
                (5550*pow(lmMsq,2) - 450*pow(lmMst1,2) + 
                  10*lmMst1*(-491 + 375*lmMt) - 
                  10*lmMsq*(-116 + 285*lmMst1 + 225*lmMst2 + 600*lmMt) + 
                  3*(-4113 + 1375*lmMt + 125*lmMst2*(-1 + 6*lmMt) + 
                     4000*z2)) + 
               4*pow(Msq,4)*
                (-2459588 + 151875*pow(lmMsq,2) - 
                  65250*pow(lmMst1,3) + 813345*lmMst2 + 
                  370350*pow(lmMst2,2) + 78750*pow(lmMst2,3) - 
                  225*pow(lmMst1,2)*(1339 + 30*lmMst2 - 900*lmMt) - 
                  222750*lmMt - 1022625*lmMst2*lmMt - 
                  229500*pow(lmMst2,2)*lmMt + 162000*pow(lmMt,2) - 
                  151875*lmMsq*(3 + 2*lmMt) + 650250*z2 + 
                  513000*lmMst2*z2 - 499500*lmMt*z2 - 
                  15*lmMst1*(17548 + 450*pow(lmMst2,2) - 71775*lmMt - 
                     15*lmMst2*(773 + 120*lmMt) + 900*z2) + 972000*z3)))/
           (375.*pow(Msq,4)*pow(Mst2,2)) - 
          (Dmglst1*(-360*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                (10*(-11 + 6*lmMsq - 6*lmMt)*pow(Mst1,2) + 
                  3*pow(Mst2,2)*
                   (-27 + 12*pow(lmMsq,2) - 14*lmMst1 - lmMst2 + 
                     3*lmMt + 6*lmMst1*lmMt + 6*lmMst2*lmMt - 
                     6*lmMsq*(-2 + lmMst1 + lmMst2 + 2*lmMt) + 24*z2)) - 
               15*pow(Mst1,2)*pow(Mst2,4)*
                (6*pow(Mst2,2)*
                   (-115 + 36*pow(lmMsq,2) + 21*lmMt - 
                     12*lmMsq*(-4 + 3*lmMst2 + 3*lmMt) + 
                     lmMst2*(-69 + 36*lmMt) + 72*z2) + 
                  pow(Mst1,2)*
                   (-2095 + 936*pow(lmMsq,2) - 330*lmMst2 - 114*lmMt + 
                     360*lmMst2*lmMt + 48*lmMst1*(-25 + 12*lmMt) - 
                     12*lmMsq*(-137 + 48*lmMst1 + 30*lmMst2 + 78*lmMt) + 
                     1872*z2)) + 
               2*pow(Msq,4)*
                (3*pow(Mst1,4)*
                   (99985 + 1512*pow(lmMst1,3) + 34432*lmMst2 + 
                     17388*pow(lmMst2,2) + 4104*pow(lmMst2,3) - 
                     4584*lmMt + 20904*lmMst2*lmMt + 
                     144*pow(lmMst2,2)*lmMt - 5184*pow(lmMt,2) - 
                     3456*lmMst2*pow(lmMt,2) + 
                     pow(lmMst1,2)*(3156 - 5832*lmMst2 + 1296*lmMt) + 
                     8*lmMst1*
                      (517 + 168*lmMst2 + 27*pow(lmMst2,2) - 
                        4557*lmMt - 180*lmMst2*lmMt + 
                        432*pow(lmMt,2) - 1350*z2) + 
                     1080*lmMsq*
                      (-9 - 29*lmMst2 - 10*pow(lmMst2,2) + 
                        10*lmMst1*(1 + lmMst2 - lmMt) + 19*lmMt + 
                        10*lmMst2*lmMt - 20*z2) + 67176*z2 + 
                     33264*lmMst2*z2 + 2880*lmMt*z2 - 47376*z3) + 
                  3*pow(Mst2,4)*
                   (2215 - 1620*pow(lmMsq,2) - 3018*pow(lmMst1,2) + 
                     254*lmMst2 - 162*pow(lmMst2,2) - 2322*lmMt + 
                     264*lmMst2*lmMt - 1872*pow(lmMt,2) + 
                     60*lmMsq*(5 + 42*lmMst1 + 12*lmMt) + 
                     lmMst1*(824 + 60*lmMst2 + 984*lmMt) - 3564*z2 + 
                     963*z3) - 
                  2*pow(Mst1,2)*pow(Mst2,2)*
                   (-64093 + 2430*pow(lmMsq,2) - 1080*pow(lmMst1,3) + 
                     12414*lmMst2 + 6354*pow(lmMst2,2) + 
                     1188*pow(lmMst2,3) - 
                     36*pow(lmMst1,2)*(38 + 3*lmMst2 - 93*lmMt) - 
                     21420*lmMt - 16794*lmMst2*lmMt - 
                     3564*pow(lmMst2,2)*lmMt + 2592*pow(lmMt,2) - 
                     2430*lmMsq*(3 + 2*lmMt) + 
                     6*lmMst1*
                      (988 + 393*lmMst2 + 2367*lmMt + 36*lmMst2*lmMt) + 
                     10872*z2 + 7776*lmMst2*z2 - 7776*lmMt*z2 + 41688*z3))
))/(3.*Mgl*pow(Msq,4)*pow(Mst2,4)) - 
          (pow(Dmglst1,2)*(-360*pow(Msq,2)*pow(Mst1,2)*
                pow(Mst2,2)*
                (1250*(-11 + 6*lmMsq - 6*lmMt)*pow(Mst1,2) + 
                  pow(Mst2,2)*
                   (-6698 + 2700*pow(lmMsq,2) - 225*lmMst2 + 
                     105*lmMt + 1350*lmMst2*lmMt + 
                     90*lmMst1*(-62 + 15*lmMt) - 
                     150*lmMsq*(-38 + 9*lmMst1 + 9*lmMst2 + 18*lmMt) + 
                     5400*z2)) - 
               15*pow(Mst1,2)*pow(Mst2,4)*
                (450*pow(Mst2,2)*
                   (-115 + 36*pow(lmMsq,2) + 21*lmMt - 
                     12*lmMsq*(-4 + 3*lmMst2 + 3*lmMt) + 
                     lmMst2*(-69 + 36*lmMt) + 72*z2) + 
                  pow(Mst1,2)*
                   (-215363 + 106200*pow(lmMsq,2) - 41250*lmMst2 - 
                     29370*lmMt + 45000*lmMst2*lmMt - 
                     300*lmMsq*
                      (-763 + 204*lmMst1 + 150*lmMst2 + 354*lmMt) + 
                     120*lmMst1*(-1319 + 510*lmMt) + 212400*z2)) + 
               2*pow(Msq,4)*
                (pow(Mst1,4)*
                   (37614091 + 451800*pow(lmMst1,3) + 
                     12134250*lmMst2 + 6674400*pow(lmMst2,2) + 
                     1616400*pow(lmMst2,3) - 
                     2700*pow(lmMst1,2)*
                      (-303 + 824*lmMst2 - 322*lmMt) + 2155140*lmMt + 
                     6916500*lmMst2*lmMt - 253800*pow(lmMst2,2)*lmMt - 
                     2462400*pow(lmMt,2) - 
                     1296000*lmMst2*pow(lmMt,2) + 
                     30*lmMst1*
                      (31687 + 89130*lmMst2 + 5220*pow(lmMst2,2) - 
                        472950*lmMt - 20520*lmMst2*lmMt + 
                        43200*pow(lmMt,2) - 129960*z2) + 
                     405000*lmMsq*
                      (-13 - 33*lmMst2 - 10*pow(lmMst2,2) + 
                        10*lmMst1*(1 + lmMst2 - lmMt) + 23*lmMt + 
                        10*lmMst2*lmMt - 20*z2) + 27183600*z2 + 
                     12938400*lmMst2*z2 + 464400*lmMt*z2 - 18046800*z3) - 
                  3*pow(Mst2,4)*
                   (242588 + 121500*pow(lmMsq,2) + 
                     164850*pow(lmMst1,2) - 6364*lmMst2 + 
                     12150*pow(lmMst2,2) - 
                     20*lmMst1*(12992 + 582*lmMst2 - 465*lmMt) + 
                     103920*lmMt - 12660*lmMst2*lmMt + 
                     61200*pow(lmMt,2) - 
                     120*lmMsq*(-1003 + 1770*lmMst1 + 255*lmMt) + 
                     267300*z2 - 454275*z3) - 
                  12*pow(Mst1,2)*pow(Mst2,2)*
                   (-1477147 + 30375*pow(lmMsq,2) - 
                     13500*pow(lmMst1,3) + 158575*lmMst2 + 
                     79425*pow(lmMst2,2) + 14850*pow(lmMst2,3) - 
                     150*pow(lmMst1,2)*(-134 + 9*lmMst2 - 279*lmMt) - 
                     408405*lmMt - 211125*lmMst2*lmMt - 
                     44550*pow(lmMst2,2)*lmMt + 32400*pow(lmMt,2) - 
                     30375*lmMsq*(3 + 2*lmMt) + 
                     5*lmMst1*
                      (17951 + 6135*lmMst2 + 28065*lmMt + 
                        540*lmMst2*lmMt) + 135900*z2 + 97200*lmMst2*z2 - 
                     97200*lmMt*z2 + 1046700*z3))))/
           (150.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)) - 
          (Mst1*MuSUSY*(pow(Dmglst1,2)*
                (240*pow(Msq,2)*
                   ((1174 + 6*lmMst1*(-137 + 39*lmMsq - 39*lmMt) + 
                        429*lmMt + lmMst2*(393 - 234*lmMsq + 234*lmMt)
)*pow(Mst1,2)*pow(Mst2,2) + 
                     pow(Mst1,4)*
                      (1174 - 810*pow(lmMst2,2) - 
                        3*lmMst2*(157 + 78*lmMsq - 348*lmMt) + 
                        6*lmMst1*
                        (-137 + 39*lmMsq + 135*lmMst2 - 174*lmMt) + 
                        1293*lmMt - 1620*z2) + 
                     pow(Mst2,4)*
                      (-17 + 18*pow(lmMsq,2) + 33*lmMt - 
                        6*lmMsq*(5 + 3*lmMst2 + 3*lmMt) + 
                        3*lmMst2*(-1 + 6*lmMt) + 36*z2)) + 
                  15*pow(Mst2,2)*
                   (4*(3220 + 
                        6*lmMst1*(-323 + 174*lmMsq - 174*lmMt) + 
                        1293*lmMt + 
                        lmMst2*(645 - 1044*lmMsq + 1044*lmMt))*
                      pow(Mst1,4) + 
                     pow(Mst2,4)*
                      (-299 + 72*pow(lmMsq,2) + 78*lmMt - 
                        12*lmMsq*(-5 + 6*lmMst2 + 6*lmMt) + 
                        6*lmMst2*(-23 + 12*lmMt) + 144*z2) + 
                     pow(Mst1,2)*pow(Mst2,2)*
                      (-2519 + 936*pow(lmMsq,2) + 1014*lmMt - 
                        12*lmMsq*(7 + 78*lmMst2 + 78*lmMt) + 
                        lmMst2*(-930 + 936*lmMt) + 1872*z2)) + 
                  4*pow(Msq,4)*
                   (pow(Mst1,2)*
                      (112558 - 9018*pow(lmMst1,3) + 
                        1620*pow(lmMsq,2)*(lmMst1 - lmMst2) + 
                        118485*lmMst2 + 111204*pow(lmMst2,2) + 
                        30240*pow(lmMst2,3) - 110178*lmMt - 
                        80604*lmMst2*lmMt - 9990*pow(lmMst2,2)*lmMt - 
                        25488*pow(lmMt,2) - 
                        18144*lmMst2*pow(lmMt,2) + 
                        pow(lmMst1,2)*
                        (19044 - 19116*lmMst2 + 45306*lmMt) + 
                        180*lmMsq*
                        (244 - 216*pow(lmMst2,2) + 
                        6*lmMst1*(-16 + 36*lmMst2 - 39*lmMt) + 
                        429*lmMt + 9*lmMst2*(-37 + 26*lmMt) - 432*z2) + 
                        300096*z2 + 174960*lmMst2*z2 + 2268*lmMt*z2 + 
                        432*pow(z2,2) - 147825*z3 + 1296*lmMst2*z3 - 
                        9*lmMst1*
                        (6907 + 234*pow(lmMst2,2) + 2084*lmMt - 
                        2016*pow(lmMt,2) + 
                        12*lmMst2*(50 + 327*lmMt) + 1260*z2 + 144*z3) - 
                        216*z4) + 
                     3*pow(Mst2,2)*
                      (33943 - 132*pow(lmMst1,3) + 
                        540*pow(lmMsq,2)*(lmMst1 - lmMst2) - 
                        2918*lmMst2 - 612*pow(lmMst2,2) - 
                        84*pow(lmMst2,3) - 5778*lmMt - 
                        3702*lmMst2*lmMt - 648*pow(lmMst2,2)*lmMt - 
                        2448*pow(lmMt,2) - 864*lmMst2*pow(lmMt,2) + 
                        6*pow(lmMst1,2)*(799 + 30*lmMst2 + 84*lmMt) + 
                        60*lmMsq*
                         (244 + 69*lmMt + 9*lmMst2*(3 + 2*lmMt) - 
                         6*lmMst1*(16 + 3*lmMt)) - 96*z2 - 
                        648*lmMst2*z2 - 504*lmMt*z2 + 144*pow(z2,2) + 
                        2*lmMst1*
                         (-10100 + 18*pow(lmMst2,2) - 1173*lmMt + 
                         432*pow(lmMt,2) + lmMst2*(429 + 72*lmMt) + 
                         576*z2 - 216*z3) - 15255*z3 + 432*lmMst2*z3 - 
                        72*z4))) + 
               Dmglst1*Mgl*(240*pow(Msq,2)*
                   ((439 - 3*lmMst2*(-65 + 42*lmMsq - 42*lmMt) + 
                        6*lmMst1*(-62 + 21*lmMsq - 21*lmMt) + 177*lmMt
)*pow(Mst1,2)*pow(Mst2,2) + 
                     pow(Mst1,4)*
                      (439 - 270*pow(lmMst2,2) - 
                        3*lmMst2*(1 + 42*lmMsq - 132*lmMt) + 
                        6*lmMst1*
                        (-62 + 21*lmMsq + 45*lmMst2 - 66*lmMt) + 
                        375*lmMt - 540*z2) + 
                     pow(Mst2,4)*
                      (-17 + 18*pow(lmMsq,2) + 33*lmMt - 
                        6*lmMsq*(5 + 3*lmMst2 + 3*lmMt) + 
                        3*lmMst2*(-1 + 6*lmMt) + 36*z2)) + 
                  15*pow(Mst2,2)*
                   (4*(871 + 6*lmMst1*(-89 + 66*lmMsq - 66*lmMt) + 
                        375*lmMt + lmMst2*(159 - 396*lmMsq + 396*lmMt)
)*pow(Mst1,4) + pow(Mst2,4)*
                      (-299 + 72*pow(lmMsq,2) + 78*lmMt - 
                        12*lmMsq*(-5 + 6*lmMst2 + 6*lmMt) + 
                        6*lmMst2*(-23 + 12*lmMt) + 144*z2) + 
                     pow(Mst1,2)*pow(Mst2,2)*
                      (-1409 + 504*pow(lmMsq,2) + 546*lmMt - 
                        12*lmMsq*(1 + 42*lmMst2 + 42*lmMt) + 
                        6*lmMst2*(-89 + 84*lmMt) + 1008*z2)) + 
                  4*pow(Msq,4)*
                   (pow(Mst1,2)*
                      (16303 - 4914*pow(lmMst1,3) + 
                        1620*pow(lmMsq,2)*(lmMst1 - lmMst2) + 
                        47667*lmMst2 + 54666*pow(lmMst2,2) + 
                        14958*pow(lmMst2,3) - 58878*lmMt - 
                        56340*lmMst2*lmMt - 6588*pow(lmMst2,2)*lmMt - 
                        10368*pow(lmMt,2) - 
                        10368*lmMst2*pow(lmMt,2) + 
                        pow(lmMst1,2)*
                        (8226 - 8910*lmMst2 + 22788*lmMt) + 
                        180*lmMsq*
                        (151 - 99*lmMst2 - 108*pow(lmMst2,2) + 
                        6*lmMst1*(-13 + 18*lmMst2 - 21*lmMt) + 
                        177*lmMt + 126*lmMst2*lmMt - 216*z2) + 
                        149868*z2 + 87156*lmMst2*z2 + 432*pow(z2,2) - 
                        50760*z3 + 1296*lmMst2*z3 - 
                        3*lmMst1*
                        (10535 + 3876*lmMst2 + 378*pow(lmMst2,2) - 
                        5148*lmMt + 5400*lmMst2*lmMt - 
                        3456*pow(lmMt,2) + 1404*z2 + 432*z3) - 216*z4) 
+ 6*pow(Mst2,2)*(1846 - 66*pow(lmMst1,3) + 
                        270*pow(lmMsq,2)*(lmMst1 - lmMst2) - 
                        1057*lmMst2 - 306*pow(lmMst2,2) - 
                        42*pow(lmMst2,3) - 3315*lmMt - 
                        1824*lmMst2*lmMt - 324*pow(lmMst2,2)*lmMt - 
                        864*pow(lmMt,2) - 432*lmMst2*pow(lmMt,2) + 
                        6*pow(lmMst1,2)*(352 + 15*lmMst2 + 42*lmMt) + 
                        30*lmMsq*
                         (151 + 51*lmMt + 9*lmMst2*(3 + 2*lmMt) - 
                         6*lmMst1*(13 + 3*lmMt)) - 48*z2 - 
                        324*lmMst2*z2 - 252*lmMt*z2 + 72*pow(z2,2) + 
                        2*lmMst1*
                         (-2534 + 201*lmMst2 + 9*pow(lmMst2,2) - 
                         192*lmMt + 36*lmMst2*lmMt + 
                         216*pow(lmMt,2) + 288*z2 - 108*z3) + 666*z3 + 
                        216*lmMst2*z3 - 36*z4))) + 
               3*pow(Mgl,2)*
                (80*pow(Msq,2)*
                   (9*(11 + 6*lmMst1*(-2 + lmMsq - lmMt) + 5*lmMt + 
                        lmMst2*(7 - 6*lmMsq + 6*lmMt))*pow(Mst1,2)*
                      pow(Mst2,2) + 
                     9*pow(Mst1,4)*
                      (11 - 6*pow(lmMst2,2) + 
                        6*lmMst1*(-2 + lmMsq + lmMst2 - 2*lmMt) + 
                        7*lmMt + lmMst2*(5 - 6*lmMsq + 12*lmMt) - 12*z2) 
+ pow(Mst2,4)*(-17 + 18*pow(lmMsq,2) + 33*lmMt - 
                        6*lmMsq*(5 + 3*lmMst2 + 3*lmMt) + 
                        3*lmMst2*(-1 + 6*lmMt) + 36*z2)) + 
                  5*pow(Mst2,2)*
                   (36*(15 + 6*lmMst1*(-1 + 2*lmMsq - 2*lmMt) + 
                        7*lmMt + lmMst2*(-1 - 12*lmMsq + 12*lmMt))*
                      pow(Mst1,4) + 
                     3*pow(Mst1,2)*pow(Mst2,2)*
                      (-223 + 72*pow(lmMsq,2) + 78*lmMt + 
                        18*lmMst2*(-5 + 4*lmMt) - 
                        12*lmMsq*(-1 + 6*lmMst2 + 6*lmMt) + 144*z2) + 
                     pow(Mst2,4)*
                      (-299 + 72*pow(lmMsq,2) + 78*lmMt - 
                        12*lmMsq*(-5 + 6*lmMst2 + 6*lmMt) + 
                        6*lmMst2*(-23 + 12*lmMt) + 144*z2)) + 
                  4*pow(Msq,4)*
                   (pow(Mst1,2)*
                      (-1747 - 726*pow(lmMst1,3) + 
                        540*pow(lmMsq,2)*(lmMst1 - lmMst2) + 
                        1929*lmMst2 + 5274*pow(lmMst2,2) + 
                        1590*pow(lmMst2,3) - 5886*lmMt - 
                        10260*lmMst2*lmMt - 1440*pow(lmMst2,2)*lmMt - 
                        864*pow(lmMt,2) - 1728*lmMst2*pow(lmMt,2) + 
                        pow(lmMst1,2)*(522 - 702*lmMst2 + 2592*lmMt) + 
                        540*lmMsq*
                         (7 + lmMst2 - 4*pow(lmMst2,2) + 
                         lmMst1*(-6 + 4*lmMst2 - 6*lmMt) + 5*lmMt + 
                         6*lmMst2*lmMt - 8*z2) + 16572*z2 + 
                        9540*lmMst2*z2 - 504*lmMt*z2 + 144*pow(z2,2) - 
                        4644*z3 + 432*lmMst2*z3 - 
                        3*lmMst1*
                         (985 + 492*lmMst2 + 54*pow(lmMst2,2) - 
                         2268*lmMt + 384*lmMst2*lmMt - 
                         576*pow(lmMt,2) - 60*z2 + 144*z3) - 72*z4) + 
                     6*pow(Mst2,2)*
                      (-212 - 22*pow(lmMst1,3) + 
                        90*pow(lmMsq,2)*(lmMst1 - lmMst2) - 
                        225*lmMst2 - 102*pow(lmMst2,2) - 
                        14*pow(lmMst2,3) - 795*lmMt - 606*lmMst2*lmMt - 
                        108*pow(lmMst2,2)*lmMt - 144*pow(lmMt,2) - 
                        144*lmMst2*pow(lmMt,2) + 
                        6*pow(lmMst1,2)*(67 + 5*lmMst2 + 14*lmMt) + 
                        90*lmMsq*
                         (7 + 3*lmMst2 + 3*lmMt + 2*lmMst2*lmMt - 
                         2*lmMst1*(3 + lmMt)) - 16*z2 - 108*lmMst2*z2 - 
                        84*lmMt*z2 + 24*pow(z2,2) + 
                        6*lmMst1*
                         (-54 + 22*lmMst2 + pow(lmMst2,2) + 37*lmMt + 
                         4*lmMst2*lmMt + 24*pow(lmMt,2) + 32*z2 - 12*z3
) + 324*z3 + 72*lmMst2*z3 - 12*z4)))))/
           (3.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)*Tbeta) + 
          (8*pow(Mst1,2)*pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
             (pow(Dmglst1,2)*
                (-9893 + 54*B4 + 27*DN + 50*lmMst1 - 
                  138*pow(lmMst1,2) + 234*pow(lmMst1,3) - 
                  4538*lmMst2 + 300*lmMst1*lmMst2 - 
                  54*pow(lmMst1,2)*lmMst2 - 1026*pow(lmMst2,2) - 
                  162*lmMst1*pow(lmMst2,2) - 18*pow(lmMst2,3) - 
                  696*lmMt + 840*lmMst1*lmMt - 216*pow(lmMst1,2)*lmMt - 
                  840*lmMst2*lmMt + 432*lmMst1*lmMst2*lmMt - 
                  216*pow(lmMst2,2)*lmMt - 2970*z2 - 864*lmMst2*z2 + 
                  3960*z3 + 162*lmMst1*z3 - 162*lmMst2*z3 - 405*z4) + 
               3*pow(Mgl,2)*
                (-417 + 6*B4 + 3*DN + 162*lmMst1 + 26*pow(lmMst1,3) - 
                  522*lmMst2 + 48*lmMst1*lmMst2 - 
                  6*pow(lmMst1,2)*lmMst2 - 144*pow(lmMst2,2) - 
                  18*lmMst1*pow(lmMst2,2) - 2*pow(lmMst2,3) - 
                  24*lmMt + 48*lmMst1*lmMt - 24*pow(lmMst1,2)*lmMt - 
                  48*lmMst2*lmMt + 48*lmMst1*lmMst2*lmMt - 
                  24*pow(lmMst2,2)*lmMt - 330*z2 - 96*lmMst2*z2 - 
                  138*z3 + 18*lmMst1*z3 - 18*lmMst2*z3 - 45*z4) + 
               6*Dmglst1*Mgl*(-735 + 6*B4 + 3*DN + 78*lmMst1 - 
                  6*pow(lmMst1,2) + 26*pow(lmMst1,3) - 510*lmMst2 + 
                  36*lmMst1*lmMst2 - 6*pow(lmMst1,2)*lmMst2 - 
                  126*pow(lmMst2,2) - 18*lmMst1*pow(lmMst2,2) - 
                  2*pow(lmMst2,3) - 48*lmMt + 72*lmMst1*lmMt - 
                  24*pow(lmMst1,2)*lmMt - 72*lmMst2*lmMt + 
                  48*lmMst1*lmMst2*lmMt - 24*pow(lmMst2,2)*lmMt - 
                  330*z2 - 96*lmMst2*z2 + 117*z3 + 18*lmMst1*z3 - 
                  18*lmMst2*z3 - 45*z4)))/
           (pow(Mgl,2)*pow(Mst2,4)*pow(Sbeta,2))))/81. + 
     (Mt*pow(s2t,3)*((pow(Mst1,5)*
             (-2880*pow(Msq,2)*pow(Mst2,2)*
                (-83 - 24*pow(lmMst1,2) + 
                  12*lmMsq*(2 + lmMst1 - lmMst2) + 28*lmMst2 - 
                  12*pow(lmMst2,2) + 4*lmMst1*(-13 + 9*lmMst2) - 24*z2) 
- 180*pow(Mst2,4)*(343 - 18*lmMst1 - 36*pow(lmMst1,2) + 
                  12*lmMsq*(-13 + 6*lmMst1 - 6*lmMst2) + 174*lmMst2 + 
                  36*pow(lmMst2,2) + 72*z2) + 
               pow(Msq,4)*(-622151 + 110304*pow(lmMst1,3) - 
                  12960*lmMsq*(11 + 10*lmMst1 - 10*lmMst2) + 
                  135756*lmMst2 + 185688*pow(lmMst2,2) + 
                  288*pow(lmMst2,3) - 
                  72*pow(lmMst1,2)*(-4499 + 3060*lmMst2) + 106128*z2 - 
                  122688*lmMst2*z2 + 
                  36*lmMst1*(69 - 14924*lmMst2 + 3048*pow(lmMst2,2) + 
                     3408*z2) + 448416*z3)))/(pow(Msq,4)*pow(Mst2,2)) - 
          (4*pow(Mst1,3)*(45*(-43 + 12*lmMsq - 12*lmMst2)*
                pow(Mst2,4) + 
               1440*pow(Msq,2)*pow(Mst2,2)*
                (37 - 8*lmMst1 - 3*pow(lmMst1,2) + 
                  6*lmMsq*(-2 + lmMst1 - lmMst2) + 20*lmMst2 + 
                  3*pow(lmMst2,2) + 6*z2) + 
               2*pow(Msq,4)*
                (132407 + 11880*B4 - 108*DN - 45360*lmMsq + 
                  6480*pow(lmMsq,2) + 137940*lmMst1 - 
                  22680*lmMsq*lmMst1 + 3240*pow(lmMsq,2)*lmMst1 + 
                  60786*pow(lmMst1,2) - 16200*lmMsq*pow(lmMst1,2) + 
                  14472*pow(lmMst1,3) - 20004*lmMst2 + 
                  9720*lmMsq*lmMst2 - 3240*pow(lmMsq,2)*lmMst2 - 
                  21132*lmMst1*lmMst2 + 25920*lmMsq*lmMst1*lmMst2 - 
                  7128*pow(lmMst1,2)*lmMst2 - 15462*pow(lmMst2,2) - 
                  9720*lmMsq*pow(lmMst2,2) - 
                  10152*lmMst1*pow(lmMst2,2) + 2808*pow(lmMst2,3) + 
                  48780*z2 - 19440*lmMsq*z2 + 864*lmMst1*z2 + 
                  26784*lmMst2*z2 - 12096*pow(z2,2) + 66744*z3 + 
                  48600*lmMst1*z3 - 48600*lmMst2*z3 - 18252*z4)))/
           pow(Msq,4) - (72*Mst1*pow(Mst2,2)*
             (-120*pow(Mst2,2) + 
               pow(Msq,2)*(-13317 + 408*B4 + 12*DN + 4320*lmMsq - 
                  720*pow(lmMsq,2) + 474*lmMst1 - 1080*lmMsq*lmMst1 + 
                  360*pow(lmMsq,2)*lmMst1 + 1002*pow(lmMst1,2) - 
                  360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                  12810*lmMst2 + 2520*lmMsq*lmMst2 - 
                  360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                  360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                  360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                  584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                  768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) + 
                  3192*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4)))/
           pow(Msq,2) + (3888*MuSUSY*
             (((939 + 30*lmMsq*(-12 + 5*lmMst1 - 5*lmMst2) + 
                    760*lmMst2 + 150*pow(lmMst2,2) - 
                    50*lmMst1*(8 + 3*lmMst2))*pow(Mst2,4))/
                (135.*pow(Msq,2)) + 
               (10*pow(Msq,2)*
                  (shiftst1 - shiftst2 + 
                    lmMst1*(-2 + shiftst1 + shiftst2) - 
                    lmMst2*(-2 + shiftst1 + shiftst2))*
                  (-1 + 2*lmMsq + 2*z2))/3. - 
               (pow(Mst2,2)*
                  (10*pow(Msq,2)*(-1 + shiftst1)*
                     (-1 + 2*lmMsq + 2*z2) + 
                    pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2)
))/(3.*pow(Mst1,2)) + (pow(Dmglst1,2)*
                  (1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                     (-3*pow(Mst2,2)*
                        (108 - 133*lmMst1 - 9*pow(lmMst1,2) + 
                        2*lmMsq*(32 + 9*lmMst1 - 9*lmMst2) + 
                        69*lmMst2 + 9*pow(lmMst2,2) + 18*z2) + 
                       pow(Mst1,2)*
                        (994 - 593*lmMst1 - 273*pow(lmMst1,2) + 
                        6*lmMsq*(-18 + 91*lmMst1 - 91*lmMst2) + 
                        701*lmMst2 + 273*pow(lmMst2,2) + 546*z2)) - 
                    180*pow(Mst1,2)*pow(Mst2,4)*
                     (-54*pow(Mst2,2) + 
                       pow(Mst1,2)*
                        (3141 - 2306*lmMst1 - 300*pow(lmMst1,2) + 
                        12*lmMsq*(47 + 50*lmMst1 - 50*lmMst2) + 
                        1742*lmMst2 + 300*pow(lmMst2,2) + 600*z2)) + 
                    pow(Msq,4)*
                     (-72*pow(Mst2,4)*
                        (6457 + 1620*pow(lmMsq,2) - 982*lmMst1 + 
                        834*pow(lmMst1,2) - 
                        60*lmMsq*(-67 + 54*lmMst1) - 2670*lmMst2 + 
                        1980*lmMst1*lmMst2 + 162*pow(lmMst2,2) + 
                        3564*z2 - 9198*z3) + 
                       pow(Mst1,4)*
                        (283217 + 55296*B4 + 27648*DN + 142560*lmMsq + 
                        116640*pow(lmMsq,2) + 4026660*lmMst1 - 
                        1944000*lmMsq*lmMst1 + 
                        1003464*pow(lmMst1,2) + 
                        184320*pow(lmMst1,3) - 3469380*lmMst2 + 
                        1710720*lmMsq*lmMst2 + 2098800*lmMst1*lmMst2 - 
                        1216512*pow(lmMst1,2)*lmMst2 - 
                        2335032*pow(lmMst2,2) + 
                        1880064*lmMst1*pow(lmMst2,2) - 
                        847872*pow(lmMst2,3) + 2439792*z2 + 
                        857088*lmMst1*z2 - 857088*lmMst2*z2 - 
                        10708416*z3 + 165888*lmMst1*z3 - 
                        165888*lmMst2*z3 - 414720*z4) - 
                       72*pow(Mst1,2)*pow(Mst2,2)*
                        (-709 + 432*B4 + 360*DN - 15720*lmMsq + 
                         13198*lmMst1 + 6480*lmMsq*lmMst1 - 
                         3240*pow(lmMsq,2)*lmMst1 - 
                         8586*pow(lmMst1,2) + 
                         3240*lmMsq*pow(lmMst1,2) - 
                         780*pow(lmMst1,3) + 12402*lmMst2 - 
                         6480*lmMsq*lmMst2 + 
                         3240*pow(lmMsq,2)*lmMst2 + 
                         1116*lmMst1*lmMst2 - 
                         2844*pow(lmMst1,2)*lmMst2 + 
                         13230*pow(lmMst2,2) - 
                         3240*lmMsq*pow(lmMst2,2) - 
                         1764*lmMst1*pow(lmMst2,2) + 
                         5388*pow(lmMst2,3) + 24516*z2 - 
                         6480*lmMsq*z2 - 10008*lmMst1*z2 + 
                         22680*lmMst2*z2 - 288*pow(z2,2) + 16254*z3 + 
                         9936*lmMst1*z3 - 9936*lmMst2*z3 - 19080*z4))))/
                (7776.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,2)) + 
               (Dmglst1*(1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                     (-(pow(Mst2,2)*
                        (82 - 93*lmMst1 - 9*pow(lmMst1,2) + 
                        6*lmMsq*(4 + 3*lmMst1 - 3*lmMst2) + 
                        69*lmMst2 + 9*pow(lmMst2,2) + 18*z2)) + 
                       pow(Mst1,2)*
                        (192 - 91*lmMst1 - 51*pow(lmMst1,2) + 
                        6*lmMsq*(-6 + 17*lmMst1 - 17*lmMst2) + 
                        127*lmMst2 + 51*pow(lmMst2,2) + 102*z2)) - 
                    180*pow(Mst1,2)*pow(Mst2,4)*
                     (-18*pow(Mst2,2) + 
                       pow(Mst1,2)*
                        (503 - 346*lmMst1 - 60*pow(lmMst1,2) + 
                        12*lmMsq*(1 + 10*lmMst1 - 10*lmMst2) + 
                        334*lmMst2 + 60*pow(lmMst2,2) + 120*z2)) + 
                    pow(Msq,4)*
                     (pow(Mst1,4)*
                        (606133 + 38880*pow(lmMsq,2) - 
                        2304*pow(lmMst1,3) - 
                        12960*lmMsq*(11 + 30*lmMst1 - 24*lmMst2) - 
                        624756*lmMst2 - 361944*pow(lmMst2,2) - 
                        218880*pow(lmMst2,3) - 
                        72*pow(lmMst1,2)*(-3901 + 2976*lmMst2) + 
                        441648*z2 - 290304*lmMst2*z2 + 
                        12*lmMst1*
                        (92887 + 23460*lmMst2 + 
                        36288*pow(lmMst2,2) + 24192*z2) - 2458944*z3) 
- 216*pow(Mst2,4)*(7 + 180*pow(lmMsq,2) + 178*pow(lmMst1,2) - 
                        60*lmMsq*(-5 + 6*lmMst1) - 226*lmMst2 + 
                        18*pow(lmMst2,2) + 
                        lmMst1*(-2 + 220*lmMst2) + 396*z2 - 390*z3) - 
                       72*pow(Mst1,2)*pow(Mst2,2)*
                        (2323 + 144*B4 + 120*DN - 2880*lmMsq + 
                         1758*lmMst1 + 2160*lmMsq*lmMst1 - 
                         1080*pow(lmMsq,2)*lmMst1 - 
                         3630*pow(lmMst1,2) + 
                         1080*lmMsq*pow(lmMst1,2) - 
                         260*pow(lmMst1,3) + 3426*lmMst2 - 
                         2160*lmMsq*lmMst2 + 
                         1080*pow(lmMsq,2)*lmMst2 + 
                         372*lmMst1*lmMst2 - 
                         948*pow(lmMst1,2)*lmMst2 + 
                         4410*pow(lmMst2,2) - 
                         1080*lmMsq*pow(lmMst2,2) - 
                         588*lmMst1*pow(lmMst2,2) + 
                         1796*pow(lmMst2,3) + 8172*z2 - 
                         2160*lmMsq*z2 - 3336*lmMst1*z2 + 
                         7560*lmMst2*z2 - 96*pow(z2,2) + 3690*z3 + 
                         3312*lmMst1*z3 - 3312*lmMst2*z3 - 6360*z4))))/
                (3888.*Mgl*pow(Msq,4)*pow(Mst2,2)) + 
               pow(Mst2,2)*(-83.27932098765432 - 4*B4 + (4*DN)/9. + 
                  (185*lmMsq)/9. - (25*pow(lmMsq,2))/3. + 
                  (3781*lmMst1)/108. - (25*lmMsq*lmMst1)/9. + 
                  (5*pow(lmMsq,2)*lmMst1)/3. - 
                  (229*pow(lmMst1,2))/36. + 
                  (5*lmMsq*pow(lmMst1,2))/3. - 
                  (11*pow(lmMst1,3))/18. - (14137*lmMst2)/108. + 
                  (175*lmMsq*lmMst2)/9. - (5*pow(lmMsq,2)*lmMst2)/3. + 
                  (583*lmMst1*lmMst2)/18. - 
                  (20*lmMsq*lmMst1*lmMst2)/3. + 
                  (pow(lmMst1,2)*lmMst2)/6. - 
                  (731*pow(lmMst2,2))/12. + 5*lmMsq*pow(lmMst2,2) + 
                  (221*lmMst1*pow(lmMst2,2))/18. - 
                  (71*pow(lmMst2,3))/6. - (8*OepS2)/27. - 33*S2 + 
                  6*lmMst1*S2 - 6*lmMst2*S2 - shiftst3/3. - 
                  (lmMst1*shiftst3)/3. + lmMst2*shiftst3 + 
                  (2*lmMst1*lmMst2*shiftst3)/3. - 
                  (2*pow(lmMst2,2)*shiftst3)/3. + (4*T1ep)/9. + 
                  37*z2 - (10*lmMsq*z2)/3. - (37*lmMst1*z2)/9. + 
                  (149*lmMst2*z2)/9. + (2*shiftst3*z2)/3. + 
                  (2*lmMst1*shiftst3*z2)/3. - 
                  (2*lmMst2*shiftst3*z2)/3. + (35*pow(z2,2))/9. - 
                  (328*z3)/9. - (242*z4)/9.) + 
               pow(Mst1,2)*(110.18859670781893 - (40*B4)/9. - 
                  (2*DN)/9. - (80*lmMsq)/9. + (10*pow(lmMsq,2))/3. + 
                  (510889*lmMst1)/2700. - (355*lmMsq*lmMst1)/9. + 
                  (35*pow(lmMsq,2)*lmMst1)/3. + 
                  (847*pow(lmMst1,2))/180. - 
                  (5*lmMsq*pow(lmMst1,2))/3. + 
                  (49*pow(lmMst1,3))/54. - (393289*lmMst2)/2700. + 
                  (295*lmMsq*lmMst2)/9. - 
                  (35*pow(lmMsq,2)*lmMst2)/3. + 
                  (4421*lmMst1*lmMst2)/30. - 20*lmMsq*lmMst1*lmMst2 - 
                  (239*pow(lmMst1,2)*lmMst2)/18. - 
                  (2717*pow(lmMst2,2))/20. + 
                  (65*lmMsq*pow(lmMst2,2))/3. + 
                  (389*lmMst1*pow(lmMst2,2))/6. - 
                  (2833*pow(lmMst2,3))/54. + 
                  ((1.0841585681891803 - pow(lmMsq,2)/21. - 
                       (157*lmMst1)/135. + 
                       lmMsq*
                        (-0.6291383219954648 + (7*lmMst1)/9. - 
                        (43*lmMst2)/63.) + (47419*lmMst2)/26460. - 
                       (7*lmMst1*lmMst2)/9. + (46*pow(lmMst2,2))/63.
)*pow(Mst2,4))/pow(Msq,4) - (472*OepS2)/243. + (295*S2)/3. + 
                  (118*lmMst1*S2)/3. - (118*lmMst2*S2)/3. + 
                  (236*T1ep)/81. - (2740*z2)/81. + (50*lmMsq*z2)/3. + 
                  (281*lmMst1*z2)/9. - (521*lmMst2*z2)/9. + 
                  (179*pow(z2,2))/27. + 
                  (10*pow(Msq,2)*(-1 + shiftst2)*
                     (-1 + 2*lmMsq + 2*z2))/(3.*pow(Mst2,2)) - 
                  (pow(Mst2,2)*
                     (1775 - 315*pow(lmMst1,2) + 
                       30*lmMsq*(-5 + lmMst1 - lmMst2) + 407*lmMst2 - 
                       285*pow(lmMst2,2) + 
                       lmMst1*(-257 + 600*lmMst2) + 450*z2))/
                   (135.*pow(Msq,2)) - (14614*z3)/81. - 28*lmMst1*z3 + 
                  28*lmMst2*z3 + (2152*z4)/81.) + 
               pow(Mst1,4)*((pow(Mst2,2)*
                     (-5.4591585681891805 + pow(lmMsq,2)/21. + 
                       (271*pow(lmMst1,2))/252. - 
                       (lmMsq*(-12899 + 6230*lmMst1 - 5390*lmMst2))/
                        8820. + 
                       lmMst1*(0.8236394557823129 - (13*lmMst2)/9.) - 
                       (823*lmMst2)/360. + (5*pow(lmMst2,2))/12. - 
                       (25*z2)/18.))/pow(Msq,4) + 
                  (787 - 25*pow(lmMst1,2) + 
                     20*lmMsq*(-9 + 20*lmMst1 - 20*lmMst2) + 
                     525*lmMst2 + 375*pow(lmMst2,2) - 
                     5*lmMst1*(69 + 70*lmMst2) + 350*z2)/
                   (45.*pow(Msq,2)) + 
                  (239.07595982905215 + 5*pow(lmMsq,2) + 
                     (8*pow(lmMst1,3))/3. + 
                     pow(lmMst1,2)*
                      (-64.58505291005291 - (776*lmMst2)/9.) - 
                     (71872687*lmMst2)/529200. - 
                     (770503*pow(lmMst2,2))/7560. - 
                     (728*pow(lmMst2,3))/9. + 
                     (5*lmMsq*
                        (-29 + 16*pow(lmMst1,2) + 18*lmMst2 + 
                        16*pow(lmMst2,2) - 2*lmMst1*(15 + 16*lmMst2))
)/6. - (1328*OepS2)/729. + (2374*S2)/27. - (332*lmMst2*S2)/9. + 
                     (664*T1ep)/243. + (65617*z2)/972. - 
                     (208*lmMst2*z2)/3. + (166*pow(z2,2))/81. + 
                     lmMst1*(202.14717876039305 + 
                        (706663*lmMst2)/3780. + 
                        (1480*pow(lmMst2,2))/9. + (332*S2)/9. + 
                        (208*z2)/3.) - (82514*z3)/243. + (332*z4)/243.)/
                   pow(Mst2,2))))/Tbeta - 
          (pow(Dmglst1,2)*Mst1*
             (180*pow(Mst1,2)*pow(Mst2,4)*
                ((-163 + 12*lmMsq - 12*lmMst2)*pow(Mst2,2) + 
                  3*pow(Mst1,2)*
                   (1961 - 290*lmMst1 - 180*pow(lmMst1,2) + 
                     4*lmMsq*(-181 + 90*lmMst1 - 90*lmMst2) + 
                     1014*lmMst2 + 180*pow(lmMst2,2) + 360*z2)) - 
               2880*pow(Msq,2)*pow(Mst2,2)*
                (3*pow(Mst2,4) + 
                  pow(Mst1,2)*pow(Mst2,2)*
                   (-563 + 126*lmMst1 + 36*pow(lmMst1,2) - 
                     72*lmMsq*(-2 + lmMst1 - lmMst2) - 270*lmMst2 - 
                     36*pow(lmMst2,2) - 72*z2) + 
                  pow(Mst1,4)*
                   (914 + 306*pow(lmMst1,2) - 
                     72*lmMsq*(2 + lmMst1 - lmMst2) + 174*lmMst2 + 
                     234*pow(lmMst2,2) - 30*lmMst1*(1 + 18*lmMst2) + 
                     468*z2)) + 
               pow(Msq,4)*(pow(Mst1,4)*
                   (9306949 - 309024*pow(lmMst1,3) + 
                     12960*lmMsq*(59 + 222*lmMst1 - 222*lmMst2) - 
                     3056388*lmMst2 + 1925208*pow(lmMst2,2) + 
                     198432*pow(lmMst2,3) + 
                     648*pow(lmMst1,2)*(-2917 + 1260*lmMst2) - 
                     192240*z2 + 1950912*lmMst2*z2 - 
                     12*lmMst1*
                      (-132587 - 10908*lmMst2 + 58824*pow(lmMst2,2) + 
                        162576*z2) - 8258976*z3) + 
                  24*pow(Mst1,2)*pow(Mst2,2)*
                   (57101 + 17640*B4 - 396*DN - 90360*lmMsq + 
                     2160*pow(lmMsq,2) + 17532*lmMst1 + 
                     52920*lmMsq*lmMst1 + 1080*pow(lmMsq,2)*lmMst1 - 
                     8406*pow(lmMst1,2) - 
                     27000*lmMsq*pow(lmMst1,2) + 
                     31884*pow(lmMst1,3) + 125076*lmMst2 - 
                     57240*lmMsq*lmMst2 - 1080*pow(lmMsq,2)*lmMst2 - 
                     44172*lmMst1*lmMst2 + 51840*lmMsq*lmMst1*lmMst2 - 
                     25956*pow(lmMst1,2)*lmMst2 + 
                     60642*pow(lmMst2,2) - 
                     24840*lmMsq*pow(lmMst2,2) - 
                     25884*lmMst1*pow(lmMst2,2) + 
                     19956*pow(lmMst2,3) + 155340*z2 - 
                     49680*lmMsq*z2 - 20232*lmMst1*z2 + 
                     98568*lmMst2*z2 - 18432*pow(z2,2) + 23940*z3 + 
                     100440*lmMst1*z3 - 100440*lmMst2*z3 - 79884*z4) + 
                  72*pow(Mst2,4)*
                   (413 + 408*B4 + 12*DN + 8520*lmMsq - 
                     720*pow(lmMsq,2) - 3146*lmMst1 - 
                     1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 - 
                     918*pow(lmMst1,2) - 360*lmMsq*pow(lmMst1,2) + 
                     200*pow(lmMst1,3) - 15206*lmMst2 + 
                     2520*lmMsq*lmMst2 - 360*pow(lmMsq,2)*lmMst2 + 
                     708*lmMst1*lmMst2 + 360*pow(lmMst1,2)*lmMst2 - 
                     4782*pow(lmMst2,2) + 360*lmMsq*pow(lmMst2,2) + 
                     24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                     7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                     2304*lmMst2*z2 - 384*pow(z2,2) - 6708*z3 - 
                     216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))))/
           (pow(Mgl,2)*pow(Msq,4)*pow(Mst2,2)) - 
          (Dmglst1*Mst1*(-8640*pow(Msq,2)*pow(Mst2,2)*
                (pow(Mst2,4) - 
                  2*pow(Mst1,2)*pow(Mst2,2)*
                   (42 - 10*lmMst1 - 3*pow(lmMst1,2) + 
                     6*lmMsq*(-2 + lmMst1 - lmMst2) + 22*lmMst2 + 
                     3*pow(lmMst2,2) + 6*z2) + 
                  pow(Mst1,4)*
                   (107 + 32*lmMst1 + 36*pow(lmMst1,2) - 
                     12*lmMsq*(2 + lmMst1 - lmMst2) - 8*lmMst2 - 
                     60*lmMst1*lmMst2 + 24*pow(lmMst2,2) + 48*z2)) + 
               180*pow(Mst1,2)*pow(Mst2,4)*
                ((-91 + 12*lmMsq - 12*lmMst2)*pow(Mst2,2) + 
                  pow(Mst1,2)*
                   (1807 - 234*lmMst1 - 180*pow(lmMst1,2) + 
                     12*lmMsq*(-61 + 30*lmMst1 - 30*lmMst2) + 
                     966*lmMst2 + 180*pow(lmMst2,2) + 360*z2)) + 
               pow(Msq,4)*(pow(Mst1,4)*
                   (3058187 - 203616*pow(lmMst1,3) + 
                     12960*lmMsq*(43 + 66*lmMst1 - 66*lmMst2) - 
                     960732*lmMst2 + 400968*pow(lmMst2,2) + 
                     93024*pow(lmMst2,3) + 
                     72*pow(lmMst1,2)*(-9407 + 6948*lmMst2) - 
                     201168*z2 + 737856*lmMst2*z2 - 
                     36*lmMst1*
                      (-4415 - 9980*lmMst2 + 10824*pow(lmMst2,2) + 
                        20496*z2) - 2584224*z3) + 
                  24*pow(Mst1,2)*pow(Mst2,2)*
                   (54053 + 9432*B4 - 180*DN - 34560*lmMsq + 
                     2160*pow(lmMsq,2) + 29868*lmMst1 + 
                     9720*lmMsq*lmMst1 + 1080*pow(lmMsq,2)*lmMst1 + 
                     20574*pow(lmMst1,2) - 
                     14040*lmMsq*pow(lmMst1,2) + 
                     15648*pow(lmMst1,3) + 34788*lmMst2 - 
                     14040*lmMsq*lmMst2 - 1080*pow(lmMsq,2)*lmMst2 - 
                     30708*lmMst1*lmMst2 + 25920*lmMsq*lmMst1*lmMst2 - 
                     11808*pow(lmMst1,2)*lmMst2 + 
                     18198*pow(lmMst2,2) - 
                     11880*lmMsq*pow(lmMst2,2) - 
                     12384*lmMst1*pow(lmMst2,2) + 
                     8544*pow(lmMst2,3) + 69876*z2 - 23760*lmMsq*z2 - 
                     7920*lmMst1*z2 + 44784*lmMst2*z2 - 
                     9792*pow(z2,2) + 24912*z3 + 49896*lmMst1*z3 - 
                     49896*lmMst2*z3 - 35604*z4) + 
                  72*pow(Mst2,4)*
                   (-11337 + 408*B4 + 12*DN + 6480*lmMsq - 
                     720*pow(lmMsq,2) - 2190*lmMst1 - 
                     1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 + 
                     234*pow(lmMst1,2) - 360*lmMsq*pow(lmMst1,2) + 
                     200*pow(lmMst1,3) - 13986*lmMst2 + 
                     2520*lmMsq*lmMst2 - 360*pow(lmMsq,2)*lmMst2 + 
                     708*lmMst1*lmMst2 + 360*pow(lmMst1,2)*lmMst2 - 
                     4782*pow(lmMst2,2) + 360*lmMsq*pow(lmMst2,2) + 
                     24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                     7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                     2304*lmMst2*z2 - 384*pow(z2,2) + 1392*z3 - 
                     216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))))/
           (Mgl*pow(Msq,4)*pow(Mst2,2))))/3888. + 
     pow(s2t,4)*((5*pow(Msq,2)*pow(Mst2,4)*(-1 + shiftst1)*
           (-1 + 2*lmMsq + 2*z2))/(6.*pow(Mst1,2)) - 
        (5*pow(Msq,2)*pow(Mst2,2)*
           (-1 + 4*shiftst1 + 2*lmMst1*(-1 + shiftst2) - 
             2*lmMst2*(-1 + shiftst2) - 3*shiftst2)*(-1 + 2*lmMsq + 2*z2))/
         6. + (pow(Dmglst1,2)*
           (180*pow(Mst1,4)*pow(Mst2,4)*
              (3195 - 2306*lmMst1 - 300*pow(lmMst1,2) + 
                12*lmMsq*(47 + 50*lmMst1 - 50*lmMst2) + 1742*lmMst2 + 
                300*pow(lmMst2,2) + 600*z2) - 
             1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
              (-3*pow(Mst2,2)*
                 (108 - 133*lmMst1 - 9*pow(lmMst1,2) + 
                   2*lmMsq*(32 + 9*lmMst1 - 9*lmMst2) + 69*lmMst2 + 
                   9*pow(lmMst2,2) + 18*z2) + 
                2*pow(Mst1,2)*
                 (659 - 496*lmMst1 - 150*pow(lmMst1,2) + 
                   6*lmMsq*(7 + 50*lmMst1 - 50*lmMst2) + 454*lmMst2 + 
                   150*pow(lmMst2,2) + 300*z2)) - 
             pow(Msq,4)*(-72*pow(Mst2,4)*
                 (6457 + 1620*pow(lmMsq,2) - 982*lmMst1 + 
                   834*pow(lmMst1,2) - 60*lmMsq*(-67 + 54*lmMst1) - 
                   2670*lmMst2 + 1980*lmMst1*lmMst2 + 
                   162*pow(lmMst2,2) + 3564*z2 - 9198*z3) + 
                pow(Mst1,4)*
                 (232169 + 86400*B4 + 53568*DN - 989280*lmMsq + 
                   116640*pow(lmMsq,2) + 4976916*lmMst1 - 
                   1477440*lmMsq*lmMst1 - 233280*pow(lmMsq,2)*lmMst1 + 
                   385272*pow(lmMst1,2) + 
                   233280*lmMsq*pow(lmMst1,2) + 
                   128160*pow(lmMst1,3) - 2576436*lmMst2 + 
                   1244160*lmMsq*lmMst2 + 233280*pow(lmMsq,2)*lmMst2 + 
                   2179152*lmMst1*lmMst2 - 
                   1421280*pow(lmMst1,2)*lmMst2 - 
                   1382472*pow(lmMst2,2) - 
                   233280*lmMsq*pow(lmMst2,2) + 
                   1753056*lmMst1*pow(lmMst2,2) - 
                   459936*pow(lmMst2,3) + 4204944*z2 - 
                   466560*lmMsq*z2 + 136512*lmMst1*z2 + 
                   775872*lmMst2*z2 - 20736*pow(z2,2) - 9538128*z3 + 
                   881280*lmMst1*z3 - 881280*lmMst2*z3 - 1788480*z4) - 
                144*pow(Mst1,2)*pow(Mst2,2)*
                 (-3583 + 216*B4 + 180*DN - 9870*lmMsq - 
                   810*pow(lmMsq,2) + 7090*lmMst1 + 4860*lmMsq*lmMst1 - 
                   1620*pow(lmMsq,2)*lmMst1 - 4710*pow(lmMst1,2) + 
                   1620*lmMsq*pow(lmMst1,2) - 390*pow(lmMst1,3) + 
                   7536*lmMst2 - 3240*lmMsq*lmMst2 + 
                   1620*pow(lmMsq,2)*lmMst2 - 432*lmMst1*lmMst2 - 
                   1422*pow(lmMst1,2)*lmMst2 + 6534*pow(lmMst2,2) - 
                   1620*lmMsq*pow(lmMst2,2) - 
                   882*lmMst1*pow(lmMst2,2) + 2694*pow(lmMst2,3) + 
                   10476*z2 - 3240*lmMsq*z2 - 5004*lmMst1*z2 + 
                   11340*lmMst2*z2 - 144*pow(z2,2) + 12726*z3 + 
                   4968*lmMst1*z3 - 4968*lmMst2*z3 - 9540*z4))))/
         (31104.*pow(Mgl,2)*pow(Msq,4)) + 
        (pow(Mst1,2)*(101250*pow(Msq,4)*
              (1 + 2*lmMst1*(-1 + shiftst1) - 2*lmMst2*(-1 + shiftst1) + 
                3*shiftst1 - 4*shiftst2)*(-1 + 2*lmMsq + 2*z2) + 
             225*pow(Mst2,4)*
              (2714 - 315*pow(lmMst1,2) + 
                30*lmMsq*(-17 + 6*lmMst1 - 6*lmMst2) + 1167*lmMst2 - 
                135*pow(lmMst2,2) + 9*lmMst1*(-73 + 50*lmMst2) + 450*z2) 
+ pow(Msq,2)*pow(Mst2,2)*(-5876588 + 13500*B4 + 20250*DN + 
                894375*lmMsq - 354375*pow(lmMsq,2) - 4684095*lmMst1 + 
                1113750*lmMsq*lmMst1 - 303750*pow(lmMsq,2)*lmMst1 - 
                336150*pow(lmMst1,2) + 101250*lmMsq*pow(lmMst1,2) - 
                46125*pow(lmMst1,3) + 448470*lmMst2 - 
                405000*lmMsq*lmMst2 + 303750*pow(lmMsq,2)*lmMst2 - 
                3492450*lmMst1*lmMst2 + 405000*lmMsq*lmMst1*lmMst2 + 
                408375*pow(lmMst1,2)*lmMst2 + 2276100*pow(lmMst2,2) - 
                506250*lmMsq*pow(lmMst2,2) - 
                1596375*lmMst1*pow(lmMst2,2) + 1234125*pow(lmMst2,3) + 
                50000*OepS2 - 3989250*S2 - 1012500*lmMst1*S2 + 
                1012500*lmMst2*S2 - 30375*shiftst3 - 
                20250*lmMst1*shiftst3 + 81000*lmMst2*shiftst3 + 
                40500*lmMst1*lmMst2*shiftst3 - 
                40500*pow(lmMst2,2)*shiftst3 - 75000*T1ep + 2151375*z2 - 
                607500*lmMsq*z2 - 1073250*lmMst1*z2 + 2261250*lmMst2*z2 + 
                60750*shiftst3*z2 + 40500*lmMst1*shiftst3*z2 - 
                40500*lmMst2*shiftst3*z2 - 83250*pow(z2,2) + 
                4373250*z3 + 850500*lmMst1*z3 - 850500*lmMst2*z3 - 
                1623750*z4)))/(121500.*pow(Msq,2)) + 
        pow(Mst1,4)*(-32.221840780308305 - (10*B4)/9. - DN/18. + 
           (275*lmMsq)/72. - (5*pow(lmMsq,2))/12. - 
           (253409*lmMst1)/78400. - (65*lmMsq*lmMst1)/18. + 
           (35*pow(lmMsq,2)*lmMst1)/12. + 
           (523837*pow(lmMst1,2))/30240. - 
           (15*lmMsq*pow(lmMst1,2))/4. - (95*pow(lmMst1,3))/216. - 
           (1737319*lmMst2)/705600. + (40*lmMsq*lmMst2)/9. - 
           (35*pow(lmMsq,2)*lmMst2)/12. - (149617*lmMst1*lmMst2)/15120. + 
           (5*lmMsq*lmMst1*lmMst2)/3. + (1313*pow(lmMst1,2)*lmMst2)/72. - 
           (256523*pow(lmMst2,2))/30240. + 
           (25*lmMsq*pow(lmMst2,2))/12. - 
           (1793*lmMst1*pow(lmMst2,2))/72. + 
           (1535*pow(lmMst2,3))/216. - (22*OepS2)/729. + (281*S2)/108. + 
           (11*lmMst1*S2)/18. - (11*lmMst2*S2)/18. + (11*T1ep)/243. - 
           (pow(Mst2,4)*(-12119532 + 176400*pow(lmMsq,2) + 
                1991850*pow(lmMst1,2) - 
                420*lmMsq*(-9224 + 6545*lmMst1 - 5705*lmMst2) - 
                7553665*lmMst2 - 580650*pow(lmMst2,2) - 
                35*lmMst1*(-105131 + 35280*lmMst2) - 2572500*z2))/
            (7.4088e6*pow(Msq,4)) + 
           (pow(Mst2,2)*(-2068 + 195*pow(lmMst1,2) - 991*lmMst2 - 
                420*pow(lmMst2,2) + lmMst1*(646 + 225*lmMst2) + 
                lmMsq*(345 - 615*lmMst1 + 615*lmMst2) - 750*z2))/
            (270.*pow(Msq,2)) - (98497*z2)/3888. + (25*lmMsq*z2)/6. - 
           (343*lmMst1*z2)/36. + (103*lmMst2*z2)/36. + 
           (371*pow(z2,2))/324. + 
           (5*pow(Msq,2)*(-1 + shiftst2)*(-1 + 2*lmMsq + 2*z2))/
            (6.*pow(Mst2,2)) + (9668*z3)/243. - 7*lmMst1*z3 + 
           7*lmMst2*z3 + (1531*z4)/243.) + 
        (pow(Mst2,4)*(53749 + 2592*B4 - 288*DN - 13320*lmMsq + 
             5400*pow(lmMsq,2) - 22686*lmMst1 + 1800*lmMsq*lmMst1 - 
             1080*pow(lmMsq,2)*lmMst1 + 4122*pow(lmMst1,2) - 
             1080*lmMsq*pow(lmMst1,2) + 396*pow(lmMst1,3) + 
             85254*lmMst2 - 12600*lmMsq*lmMst2 + 
             1080*pow(lmMsq,2)*lmMst2 - 20988*lmMst1*lmMst2 + 
             4320*lmMsq*lmMst1*lmMst2 - 108*pow(lmMst1,2)*lmMst2 + 
             39474*pow(lmMst2,2) - 3240*lmMsq*pow(lmMst2,2) - 
             7956*lmMst1*pow(lmMst2,2) + 7668*pow(lmMst2,3) + 
             192*OepS2 + 21384*S2 - 3888*lmMst1*S2 + 3888*lmMst2*S2 + 
             864*shiftst3 - 1728*lmMst2*shiftst3 - 288*T1ep - 23544*z2 + 
             2160*lmMsq*z2 + 2664*lmMst1*z2 - 10728*lmMst2*z2 - 
             1728*shiftst3*z2 - 2520*pow(z2,2) + 23616*z3 + 17424*z4))/
         2592. + (Dmglst1*(180*pow(Mst1,4)*pow(Mst2,4)*
              (521 - 346*lmMst1 - 60*pow(lmMst1,2) + 
                12*lmMsq*(1 + 10*lmMst1 - 10*lmMst2) + 334*lmMst2 + 
                60*pow(lmMst2,2) + 120*z2) - 
             1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
              (-(pow(Mst2,2)*
                   (82 - 93*lmMst1 - 9*pow(lmMst1,2) + 
                     6*lmMsq*(4 + 3*lmMst1 - 3*lmMst2) + 69*lmMst2 + 
                     9*pow(lmMst2,2) + 18*z2)) + 
                2*pow(Mst1,2)*
                 (137 - 92*lmMst1 - 30*pow(lmMst1,2) + 
                   lmMsq*(-6 + 60*lmMst1 - 60*lmMst2) + 98*lmMst2 + 
                   30*pow(lmMst2,2) + 60*z2)) + 
             pow(Msq,4)*(216*pow(Mst2,4)*
                 (7 + 180*pow(lmMsq,2) - 2*lmMst1 + 
                   178*pow(lmMst1,2) - 60*lmMsq*(-5 + 6*lmMst1) - 
                   226*lmMst2 + 220*lmMst1*lmMst2 + 18*pow(lmMst2,2) + 
                   396*z2 - 390*z3) + 
                144*pow(Mst1,2)*pow(Mst2,2)*
                 (1151 + 72*B4 + 60*DN - 1890*lmMsq - 270*pow(lmMsq,2) + 
                   882*lmMst1 + 1620*lmMsq*lmMst1 - 
                   540*pow(lmMsq,2)*lmMst1 - 2082*pow(lmMst1,2) + 
                   540*lmMsq*pow(lmMst1,2) - 130*pow(lmMst1,3) + 
                   2052*lmMst2 - 1080*lmMsq*lmMst2 + 
                   540*pow(lmMsq,2)*lmMst2 - 144*lmMst1*lmMst2 - 
                   474*pow(lmMst1,2)*lmMst2 + 2178*pow(lmMst2,2) - 
                   540*lmMsq*pow(lmMst2,2) - 
                   294*lmMst1*pow(lmMst2,2) + 898*pow(lmMst2,3) + 
                   3492*z2 - 1080*lmMsq*z2 - 1668*lmMst1*z2 + 
                   3780*lmMst2*z2 - 48*pow(z2,2) + 2430*z3 + 
                   1656*lmMst1*z3 - 1656*lmMst2*z3 - 3180*z4) + 
                pow(Mst1,4)*(-773389 - 10368*B4 - 8640*DN + 
                   349920*lmMsq - 38880*pow(lmMsq,2) - 1241220*lmMst1 + 
                   233280*lmMsq*lmMst1 + 77760*pow(lmMsq,2)*lmMst1 - 
                   19512*pow(lmMst1,2) - 77760*lmMsq*pow(lmMst1,2) + 
                   21024*pow(lmMst1,3) + 378084*lmMst2 - 
                   155520*lmMsq*lmMst2 - 77760*pow(lmMsq,2)*lmMst2 - 
                   308304*lmMst1*lmMst2 + 282528*pow(lmMst1,2)*lmMst2 + 
                   44424*pow(lmMst2,2) + 77760*lmMsq*pow(lmMst2,2) - 
                   393120*lmMst1*pow(lmMst2,2) + 89568*pow(lmMst2,3) - 
                   1030032*z2 + 155520*lmMsq*z2 - 50112*lmMst1*z2 - 
                   254016*lmMst2*z2 + 6912*pow(z2,2) + 2193264*z3 - 
                   238464*lmMst1*z3 + 238464*lmMst2*z3 + 457920*z4))))/
         (15552.*Mgl*pow(Msq,4))) + 
     (pow(Mt,3)*s2t*((-4*pow(Mst1,5)*
             (1080*pow(Msq,2)*pow(Mst2,2)*
                (1 + 6*pow(lmMst2,2) + lmMst2*(5 - 6*lmMt) - 2*lmMt + 
                  lmMst1*(-3 - 6*lmMst2 + 6*lmMt) + 12*z2) + 
               45*pow(Mst2,4)*
                (-200 + 36*pow(lmMsq,2) - 3*lmMt + 72*lmMst1*lmMt - 
                  12*lmMsq*(-2 + 6*lmMst1 - 3*lmMst2 + 3*lmMt) - 
                  3*lmMst2*(7 + 12*lmMt) + 72*z2) - 
               2*pow(Msq,4)*
                (-20293 - 1620*pow(lmMst1,3) + 52254*lmMst2 + 
                  41841*pow(lmMst2,2) + 6912*pow(lmMst2,3) - 
                  9*pow(lmMst1,2)*(3199 + 504*lmMst2 - 852*lmMt) - 
                  4482*lmMt - 22248*lmMst2*lmMt - 
                  4428*pow(lmMst2,2)*lmMt - 2592*lmMst2*pow(lmMt,2) + 
                  1620*lmMsq*(7 - 17*lmMst2 - 6*pow(lmMst2,2) + 
                     3*lmMst1*(5 + 2*lmMst2 - 2*lmMt) + 2*lmMt + 
                     6*lmMst2*lmMt - 12*z2) + 82602*z2 + 
                  39528*lmMst2*z2 - 
                  18*lmMst1*(4094 + 533*lmMst2 + 42*pow(lmMst2,2) - 
                     1044*lmMt + 180*lmMst2*lmMt - 144*pow(lmMt,2) + 
                     276*z2) - 48384*z3)))/(pow(Msq,4)*pow(Mst2,4)) - 
          (24*pow(Mst1,3)*(20*pow(Msq,2)*pow(Mst2,2)*
                (18*pow(lmMsq,2) + 27*lmMst1*(3 + 2*lmMt) - 
                  3*lmMsq*(7 + 18*lmMst1 - 12*lmMst2 + 6*lmMt) - 
                  2*(55 + 6*lmMt + 6*lmMst2*(4 + 3*lmMt) - 18*z2)) - 
               5*pow(Mst2,4)*
                (-112 + 36*pow(lmMsq,2) + 39*lmMt - 
                  12*lmMsq*(-1 + 3*lmMst2 + 3*lmMt) + 
                  lmMst2*(-51 + 36*lmMt) + 72*z2) + 
               pow(Msq,4)*(-83 + 594*pow(lmMst1,3) - 6591*lmMst2 - 
                  6282*pow(lmMst2,2) - 1674*pow(lmMst2,3) + 
                  18*pow(lmMst1,2)*(163 + 49*lmMst2 - 116*lmMt) + 
                  1116*lmMt + 5760*lmMst2*lmMt + 
                  792*pow(lmMst2,2)*lmMt + 864*lmMst2*pow(lmMt,2) - 
                  16668*z2 - 10188*lmMst2*z2 + 
                  540*lmMsq*(1 + 4*lmMst2 + 4*pow(lmMst2,2) - 2*lmMt - 
                     4*lmMst2*lmMt + lmMst1*(-2 - 4*lmMst2 + 4*lmMt) + 
                     8*z2) + 3*lmMst1*
                   (1249 + 66*pow(lmMst2,2) - 1536*lmMt - 
                     288*pow(lmMt,2) + 108*lmMst2*(5 + 4*lmMt) + 324*z2
) + 6588*z3)))/(pow(Msq,4)*pow(Mst2,2)) - 
          (4*pow(Dmglst1,2)*Mst1*
             (-60*pow(Msq,2)*pow(Mst2,2)*
                (54*pow(Mst1,4)*
                   (-16 - 47*lmMst2 - 30*pow(lmMst2,2) + 
                     15*lmMst1*(1 + 2*lmMst2 - 2*lmMt) + 32*lmMt + 
                     30*lmMst2*lmMt - 60*z2) - 
                  6*pow(Mst1,2)*pow(Mst2,2)*
                   (-331 + 6*pow(lmMsq,2) + 235*lmMst1 - 96*lmMst2 - 
                     132*lmMt + 78*lmMst1*lmMt - 72*lmMst2*lmMt - 
                     lmMsq*(7 + 78*lmMst1 - 72*lmMst2 + 6*lmMt) + 12*z2) 
+ pow(Mst2,4)*(-67 + 36*pow(lmMsq,2) - 24*lmMst2 + 66*lmMt + 
                     36*lmMst2*lmMt - 6*lmMsq*(7 + 6*lmMst2 + 6*lmMt) + 
                     72*z2)) - 
               15*pow(Mst2,4)*
                (-3*pow(Mst1,4)*
                   (156*pow(lmMsq,2) + 
                     lmMsq*(64 - 696*lmMst1 + 540*lmMst2 - 156*lmMt) + 
                     8*lmMst1*(118 + 87*lmMt) - 
                     3*(740 + 231*lmMt + 15*lmMst2*(7 + 12*lmMt) - 
                        104*z2)) + 
                  pow(Mst2,4)*
                   (-169 + 36*pow(lmMsq,2) + 39*lmMt - 
                     12*lmMsq*(-4 + 3*lmMst2 + 3*lmMt) + 
                     lmMst2*(-87 + 36*lmMt) + 72*z2) + 
                  12*pow(Mst1,2)*pow(Mst2,2)*
                   (-112 + 36*pow(lmMsq,2) + 39*lmMt - 
                     12*lmMsq*(-1 + 3*lmMst2 + 3*lmMt) + 
                     lmMst2*(-51 + 36*lmMt) + 72*z2)) - 
               2*pow(Msq,4)*
                (3*pow(Mst1,4)*
                   (134328 - 4788*pow(lmMst1,3) + 272545*lmMst2 + 
                     200058*pow(lmMst2,2) + 31338*pow(lmMst2,3) - 
                     18*pow(lmMst1,2)*
                      (7074 + 1807*lmMst2 - 2573*lmMt) - 71466*lmMt - 
                     75966*lmMst2*lmMt - 14166*pow(lmMst2,2)*lmMt - 
                     9504*pow(lmMt,2) - 12960*lmMst2*pow(lmMt,2) + 
                     lmMst1*(-153271 + 5976*pow(lmMst2,2) + 
                        14334*lmMt + 12960*pow(lmMt,2) - 
                        6*lmMst2*(265 + 5358*lmMt) - 15696*z2) + 
                     1620*lmMsq*
                      (-20 - 107*lmMst2 - 30*pow(lmMst2,2) + 
                        15*lmMst1*(5 + 2*lmMst2 - 2*lmMt) + 32*lmMt + 
                        30*lmMst2*lmMt - 60*z2) + 389244*z2 + 
                     185796*lmMst2*z2 + 2700*lmMt*z2 - 231048*z3) + 
                  pow(Mst1,2)*pow(Mst2,2)*
                   (57151 - 8622*pow(lmMst1,3) + 161988*lmMst2 + 
                     117063*pow(lmMst2,2) + 30492*pow(lmMst2,3) - 
                     9*pow(lmMst1,2)*
                      (1915 + 2184*lmMst2 - 4866*lmMt) - 74700*lmMt - 
                     53946*lmMst2*lmMt - 8046*pow(lmMst2,2)*lmMt - 
                     18144*pow(lmMt,2) - 15552*lmMst2*pow(lmMt,2) + 
                     6480*lmMsq*
                      (-5 - 13*lmMst2 - 6*pow(lmMst2,2) + 
                        lmMst1*(3 + 6*lmMst2 - 6*lmMt) + 10*lmMt + 
                        6*lmMst2*lmMt - 12*z2) + 298494*z2 + 
                     176904*lmMst2*z2 + 3780*lmMt*z2 - 
                     6*lmMst1*
                      (-716 + 369*pow(lmMst2,2) + 4545*lmMt - 
                        2592*pow(lmMt,2) + 
                        6*lmMst2*(-275 + 993*lmMt) + 2466*z2) - 102060*z3
) + 3*pow(Mst2,4)*(36832 - 132*pow(lmMst1,3) + 
                     540*pow(lmMsq,2)*(lmMst1 - lmMst2) - 1067*lmMst2 - 
                     288*pow(lmMst2,2) - 84*pow(lmMst2,3) - 
                     3330*lmMt - 2838*lmMst2*lmMt - 
                     648*pow(lmMst2,2)*lmMt - 2448*pow(lmMt,2) - 
                     864*lmMst2*pow(lmMt,2) + 
                     6*pow(lmMst1,2)*(757 + 30*lmMst2 + 84*lmMt) + 
                     30*lmMsq*
                      (419 + 138*lmMt + 36*lmMst2*(1 + lmMt) - 
                        6*lmMst1*(29 + 6*lmMt)) + 156*z2 - 
                     648*lmMst2*z2 - 504*lmMt*z2 + 144*pow(z2,2) + 
                     lmMst1*(-19027 + 36*pow(lmMst2,2) - 3210*lmMt + 
                        864*pow(lmMt,2) + 6*lmMst2*(131 + 24*lmMt) + 
                        1152*z2 - 432*z3) - 15255*z3 + 432*lmMst2*z3 - 
                     72*z4))))/(pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)) - 
          (4*Dmglst1*Mst1*(-60*pow(Msq,2)*pow(Mst2,2)*
                (-6*pow(Mst1,2)*pow(Mst2,2)*
                   (6*pow(lmMsq,2) - 
                     lmMsq*(7 + 42*lmMst1 - 36*lmMst2 + 6*lmMt) + 
                     lmMst1*(103 + 42*lmMt) - 
                     4*(32 + 12*lmMst2 + 12*lmMt + 9*lmMst2*lmMt - 3*z2)
) + 18*pow(Mst1,4)*(-11 - 30*pow(lmMst2,2) + 
                     15*lmMst1*(1 + 2*lmMst2 - 2*lmMt) + 22*lmMt + 
                     lmMst2*(-37 + 30*lmMt) - 60*z2) + 
                  pow(Mst2,4)*
                   (-67 + 36*pow(lmMsq,2) + 66*lmMt + 
                     12*lmMst2*(-2 + 3*lmMt) - 
                     6*lmMsq*(7 + 6*lmMst2 + 6*lmMt) + 72*z2)) - 
               15*pow(Mst2,4)*
                (pow(Mst2,4)*
                   (-169 + 36*pow(lmMsq,2) + 39*lmMt - 
                     12*lmMsq*(-4 + 3*lmMst2 + 3*lmMt) + 
                     lmMst2*(-87 + 36*lmMt) + 72*z2) + 
                  6*pow(Mst1,2)*pow(Mst2,2)*
                   (-112 + 36*pow(lmMsq,2) + 39*lmMt - 
                     12*lmMsq*(-1 + 3*lmMst2 + 3*lmMt) + 
                     lmMst2*(-51 + 36*lmMt) + 72*z2) - 
                  3*pow(Mst1,4)*
                   (-736 + 84*pow(lmMsq,2) - 105*lmMst2 - 159*lmMt - 
                     180*lmMst2*lmMt - 
                     4*lmMsq*(-10 + 66*lmMst1 - 45*lmMst2 + 21*lmMt) + 
                     8*lmMst1*(28 + 33*lmMt) + 168*z2)) - 
               2*pow(Msq,4)*
                (pow(Mst1,4)*
                   (54037 - 5508*pow(lmMst1,3) + 273408*lmMst2 + 
                     207819*pow(lmMst2,2) + 32940*pow(lmMst2,3) - 
                     9*pow(lmMst1,2)*
                      (14497 + 3276*lmMst2 - 4920*lmMt) - 57618*lmMt - 
                     91188*lmMst2*lmMt - 16200*pow(lmMst2,2)*lmMt - 
                     5184*pow(lmMt,2) - 12960*lmMst2*pow(lmMt,2) + 
                     6*lmMst1*
                      (-41437 + 342*pow(lmMst2,2) + 8286*lmMt + 
                        2160*pow(lmMt,2) - 
                        15*lmMst2*(341 + 312*lmMt) - 3348*z2) + 
                     1620*lmMsq*
                      (5 - 97*lmMst2 - 30*pow(lmMst2,2) + 
                        15*lmMst1*(5 + 2*lmMst2 - 2*lmMt) + 22*lmMt + 
                        30*lmMst2*lmMt - 60*z2) + 398142*z2 + 
                     191376*lmMst2*z2 + 1512*lmMt*z2 - 237168*z3) + 
                  pow(Mst1,2)*pow(Mst2,2)*
                   (24721 - 4518*pow(lmMst1,3) + 76707*lmMst2 + 
                     58824*pow(lmMst2,2) + 15210*pow(lmMst2,3) - 
                     18*pow(lmMst1,2)*(838 + 525*lmMst2 - 1182*lmMt) - 
                     33804*lmMt - 37620*lmMst2*lmMt - 
                     4644*pow(lmMst2,2)*lmMt - 5184*pow(lmMt,2) - 
                     7776*lmMst2*pow(lmMt,2) + 
                     1620*lmMsq*
                      (-7 - 12*pow(lmMst2,2) + 
                        6*lmMst1*(1 + 2*lmMst2 - 2*lmMt) + 14*lmMt + 
                        4*lmMst2*(-5 + 3*lmMt) - 24*z2) + 149400*z2 + 
                     89100*lmMst2*z2 + 1512*lmMt*z2 - 
                     9*lmMst1*
                      (1119 + 138*pow(lmMst2,2) - 1108*lmMt - 
                        864*pow(lmMt,2) + 12*lmMst2*(53 + 154*lmMt) + 
                        852*z2) - 54756*z3) + 
                  3*pow(Mst2,4)*
                   (7007 - 132*pow(lmMst1,3) + 
                     540*pow(lmMsq,2)*(lmMst1 - lmMst2) - 290*lmMst2 - 
                     288*pow(lmMst2,2) - 84*pow(lmMst2,3) - 
                     4902*lmMt - 2784*lmMst2*lmMt - 
                     648*pow(lmMst2,2)*lmMt - 1728*pow(lmMt,2) - 
                     864*lmMst2*pow(lmMt,2) + 
                     12*pow(lmMst1,2)*(331 + 15*lmMst2 + 42*lmMt) + 
                     30*lmMsq*
                      (251 + 102*lmMt + 36*lmMst2*(1 + lmMt) - 
                        6*lmMst1*(23 + 6*lmMt)) + 156*z2 - 
                     648*lmMst2*z2 - 504*lmMt*z2 + 144*pow(z2,2) + 
                     4*lmMst1*
                      (-2438 + 9*pow(lmMst2,2) - 408*lmMt + 
                        216*pow(lmMt,2) + 3*lmMst2*(61 + 12*lmMt) + 
                        288*z2 - 108*z3) + 1332*z3 + 432*lmMst2*z3 - 72*z4
))))/(Mgl*pow(Msq,4)*pow(Mst2,4)) + 
          (12*Mst1*(20*pow(Msq,2)*pow(Mst2,2)*
                (-67 + 36*pow(lmMsq,2) + 66*lmMt + 
                  12*lmMst2*(-2 + 3*lmMt) - 
                  6*lmMsq*(7 + 6*lmMst2 + 6*lmMt) + 72*z2) + 
               5*pow(Mst2,4)*
                (-169 + 36*pow(lmMsq,2) + 39*lmMt - 
                  12*lmMsq*(-4 + 3*lmMst2 + 3*lmMt) + 
                  lmMst2*(-87 + 36*lmMt) + 72*z2) + 
               6*pow(Msq,4)*
                (371 - 44*pow(lmMst1,3) + 
                  180*pow(lmMsq,2)*(lmMst1 - lmMst2) + 156*lmMst2 - 
                  96*pow(lmMst2,2) - 28*pow(lmMst2,3) - 1302*lmMt - 
                  924*lmMst2*lmMt - 216*pow(lmMst2,2)*lmMt - 
                  288*pow(lmMt,2) - 288*lmMst2*pow(lmMt,2) + 
                  12*pow(lmMst1,2)*(60 + 5*lmMst2 + 14*lmMt) + 
                  90*lmMsq*(11 + 6*lmMt + 4*lmMst2*(1 + lmMt) - 
                     2*lmMst1*(5 + 2*lmMt)) + 52*z2 - 216*lmMst2*z2 - 
                  168*lmMt*z2 + 48*pow(z2,2) + 
                  6*lmMst1*(-145 + 2*pow(lmMst2,2) + 26*lmMt + 
                     48*pow(lmMt,2) + 8*lmMst2*(5 + lmMt) + 64*z2 - 
                     24*z3) + 648*z3 + 144*lmMst2*z3 - 24*z4)))/
           pow(Msq,4) + (486*MuSUSY*
             (29.117283950617285 - (16*DN)/9. - (20*lmMsq)/3. + 
               20*pow(lmMsq,2) - (1816*lmMst1)/27. - 
               (80*lmMsq*lmMst1)/9. - (20*pow(lmMsq,2)*lmMst1)/3. + 
               (164*pow(lmMst1,2))/9. - (116*pow(lmMst1,3))/27. + 
               (2860*lmMst2)/27. - (280*lmMsq*lmMst2)/9. + 
               (20*pow(lmMsq,2)*lmMst2)/3. - (448*lmMst1*lmMst2)/9. + 
               (40*lmMsq*lmMst1*lmMst2)/3. - 
               (16*pow(lmMst1,2)*lmMst2)/3. + 
               (764*pow(lmMst2,2))/9. - (40*lmMsq*pow(lmMst2,2))/3. - 
               (176*lmMst1*pow(lmMst2,2))/9. + 
               (788*pow(lmMst2,3))/27. - 
               (4*(5108 + 900*pow(lmMsq,2) + 
                    15*lmMsq*(-218 + 75*lmMst1 - 195*lmMst2) + 
                    6270*lmMst2 + 2025*pow(lmMst2,2) - 
                    375*lmMst1*(8 + 3*lmMst2))*pow(Mst2,2))/
                (2025.*pow(Msq,2)) - 
               ((103583 + 44100*pow(lmMsq,2) + 
                    420*lmMsq*(-256 + 49*lmMst1 - 259*lmMst2) + 
                    150052*lmMst2 + 64680*pow(lmMst2,2) - 
                    1372*lmMst1*(31 + 15*lmMst2))*pow(Mst2,4))/
                (92610.*pow(Msq,4)) + (16*OepS2)/27. - 6*S2 - 
               12*lmMst1*S2 + 12*lmMst2*S2 - (8*T1ep)/9. + (587*z2)/9. - 
               (8*lmMst1*z2)/3. + (8*lmMst2*z2)/3. + 
               (10*pow(z2,2))/9. - 
               (40*pow(Msq,2)*(-1 + shiftst2)*(-1 + 2*lmMsq + 2*z2))/
                (3.*pow(Mst2,2)) + 
               (4*(10*pow(Msq,2)*(-1 + shiftst1)*
                     (-1 + 2*lmMsq + 2*z2) + 
                    pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2)
))/(3.*pow(Mst1,2)) + (172*z3)/9. + 
               (pow(Dmglst1,2)*
                  (-360*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                     (50*(-11 + 6*lmMsq - 6*lmMst2)*pow(Mst1,2) + 
                       3*(9 - 100*lmMsq + 118*lmMst1 - 18*lmMst2)*
                        pow(Mst2,2)) + 
                    45*pow(Mst1,2)*pow(Mst2,4)*
                     (2*(307 + 936*lmMsq - 1236*lmMst1 + 300*lmMst2)*
                        pow(Mst1,2) + 
                       9*(13 - 12*lmMsq + 12*lmMst2)*pow(Mst2,2)) + 
                    2*pow(Msq,4)*
                     (9*pow(Mst2,4)*
                        (8802 + 3120*lmMsq + 1620*pow(lmMsq,2) - 
                        2924*lmMst1 - 3240*lmMsq*lmMst1 + 
                        1986*pow(lmMst1,2) - 888*lmMst2 + 
                        828*lmMst1*lmMst2 + 162*pow(lmMst2,2) + 
                        3564*z2 - 10437*z3) + 
                       2*pow(Mst1,4)*
                        (-333689 + 1296*B4 + 648*DN + 105300*lmMsq + 
                        321816*lmMst1 - 81000*lmMsq*lmMst1 + 
                        346779*pow(lmMst1,2) + 
                        77472*pow(lmMst1,3) - 498072*lmMst2 + 
                        81000*lmMsq*lmMst2 - 610614*lmMst1*lmMst2 - 
                        17280*pow(lmMst1,2)*lmMst2 + 
                        241371*pow(lmMst2,2) - 
                        151200*lmMst1*pow(lmMst2,2) + 
                        91008*pow(lmMst2,3) - 82080*lmMt + 
                        153792*lmMst1*lmMt - 
                        59616*pow(lmMst1,2)*lmMt - 
                        153792*lmMst2*lmMt + 
                        119232*lmMst1*lmMst2*lmMt - 
                        59616*pow(lmMst2,2)*lmMt + 117486*z2 - 
                        168696*lmMst1*z2 + 282744*lmMst2*z2 - 
                        66528*z3 + 3888*lmMst1*z3 - 3888*lmMst2*z3 - 
                        9720*z4) + 
                       3*pow(Mst1,2)*pow(Mst2,2)*
                        (-248545 + 864*B4 + 432*DN + 14580*lmMsq - 
                         4860*pow(lmMsq,2) - 9042*lmMst1 - 
                         3870*pow(lmMst1,2) + 7200*pow(lmMst1,3) - 
                         137442*lmMst2 + 9720*lmMsq*lmMst2 + 
                         4860*lmMst1*lmMst2 - 
                         2592*pow(lmMst1,2)*lmMst2 - 
                         36414*pow(lmMst2,2) - 
                         6048*lmMst1*pow(lmMst2,2) + 
                         1440*pow(lmMst2,3) - 16704*lmMt + 
                         20160*lmMst1*lmMt - 
                         5184*pow(lmMst1,2)*lmMt - 
                         20160*lmMst2*lmMt + 10368*lmMst1*lmMst2*lmMt - 
                         5184*pow(lmMst2,2)*lmMt - 99972*z2 - 
                         4320*lmMst1*z2 - 16416*lmMst2*z2 + 113256*z3 + 
                         2592*lmMst1*z3 - 2592*lmMst2*z3 - 6480*z4))))/
                (486.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)) + 
               (Dmglst1*(-360*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                     (10*(-11 + 6*lmMsq - 6*lmMst2)*pow(Mst1,2) + 
                       3*(7 - 20*lmMsq + 26*lmMst1 - 6*lmMst2)*
                        pow(Mst2,2)) + 
                    45*pow(Mst1,2)*pow(Mst2,4)*
                     (2*(11 + 144*lmMsq - 204*lmMst1 + 60*lmMst2)*
                        pow(Mst1,2) + 
                       3*(13 - 12*lmMsq + 12*lmMst2)*pow(Mst2,2)) + 
                    2*pow(Msq,4)*
                     (18*pow(Mst2,4)*
                        (-158 + 270*pow(lmMsq,2) - 70*lmMst1 + 
                        459*pow(lmMst1,2) - 
                        60*lmMsq*(-4 + 9*lmMst1) - 96*lmMst2 + 
                        138*lmMst1*lmMst2 + 27*pow(lmMst2,2) + 
                        594*z2 - 330*z3) + 
                       pow(Mst1,2)*pow(Mst2,2)*
                        (-164809 + 864*B4 + 432*DN + 14580*lmMsq - 
                        4860*pow(lmMsq,2) + 9366*lmMst1 - 
                        1854*pow(lmMst1,2) + 7200*pow(lmMst1,3) - 
                        141450*lmMst2 + 9720*lmMsq*lmMst2 + 
                        5436*lmMst1*lmMst2 - 
                        2592*pow(lmMst1,2)*lmMst2 - 
                        39006*pow(lmMst2,2) - 
                        6048*lmMst1*pow(lmMst2,2) + 
                        1440*pow(lmMst2,3) - 10368*lmMt + 
                        15552*lmMst1*lmMt - 
                        5184*pow(lmMst1,2)*lmMt - 
                        15552*lmMst2*lmMt + 10368*lmMst1*lmMst2*lmMt - 
                        5184*pow(lmMst2,2)*lmMt - 99972*z2 - 
                        4320*lmMst1*z2 - 16416*lmMst2*z2 + 34344*z3 + 
                        2592*lmMst1*z3 - 2592*lmMst2*z3 - 6480*z4) + 
                       6*pow(Mst1,4)*
                        (-17783 + 144*B4 + 72*DN + 4860*lmMsq + 
                         46668*lmMst1 - 5400*lmMsq*lmMst1 + 
                         30483*pow(lmMst1,2) + 6120*pow(lmMst1,3) - 
                         63660*lmMst2 + 5400*lmMsq*lmMst2 - 
                         41382*lmMst1*lmMst2 - 
                         1368*pow(lmMst1,2)*lmMst2 + 
                         8019*pow(lmMst2,2) - 
                         10440*lmMst1*pow(lmMst2,2) + 
                         5688*pow(lmMst2,3) - 3456*lmMt + 
                         8640*lmMst1*lmMt - 4320*pow(lmMst1,2)*lmMt - 
                         8640*lmMst2*lmMt + 8640*lmMst1*lmMst2*lmMt - 
                         4320*pow(lmMst2,2)*lmMt - 5586*z2 - 
                         11448*lmMst1*z2 + 14904*lmMst2*z2 - 1440*z3 + 
                         432*lmMst1*z3 - 432*lmMst2*z3 - 1080*z4))))/
                (243.*Mgl*pow(Msq,4)*pow(Mst2,4)) + 
               pow(Mst1,4)*((-187967 + 44100*pow(lmMsq,2) - 
                     141120*pow(lmMst1,2) - 
                     420*lmMsq*(-2194 + 259*lmMst1 - 49*lmMst2) + 
                     471968*lmMst2 - 205800*pow(lmMst2,2) + 
                     28*lmMst1*(-49766 + 13965*lmMst2))/
                   (92610.*pow(Msq,4)) - 
                  (20*(-55 + 30*lmMsq + 9*pow(lmMst1,2) - 
                       30*lmMst2 - 18*lmMst1*lmMst2 + 9*pow(lmMst2,2)
))/(27.*pow(Msq,2)*pow(Mst2,2)) + 
                  (-41.95060131895204 + (2708*pow(lmMst1,3))/27. - 
                     (46111958*lmMst2)/33075. - 
                     (50824*pow(lmMst2,2))/945. + 
                     (3052*pow(lmMst2,3))/27. - 
                     (40*lmMsq*
                        (-2 + pow(lmMst1,2) + 
                        lmMst1*(5 - 2*lmMst2) - 5*lmMst2 + 
                        pow(lmMst2,2)))/3. + 
                     pow(lmMst1,2)*
                      (586.2179894179894 + (364*lmMst2)/9. - 64*lmMt) - 
                     (64*lmMt)/3. - (256*lmMst2*lmMt)/3. - 
                     64*pow(lmMst2,2)*lmMt + (640*OepS2)/729. - 
                     (1112*S2)/27. + (160*lmMst2*S2)/9. - 
                     (320*T1ep)/243. + 
                     lmMst1*(1145.274618291761 - 
                        (577072*lmMst2)/945. - 
                        (2284*pow(lmMst2,2))/9. + (256*lmMt)/3. + 
                        128*lmMst2*lmMt - (160*S2)/9. - (1792*z2)/9.) - 
                     (105596*z2)/243. + (1024*lmMst2*z2)/9. - 
                     (80*pow(z2,2))/81. + (5872*z3)/243. - 
                     (160*z4)/243.)/pow(Mst2,4)) + 4*z4 - 
               (pow(Mst1,2)*
                  (-120*(-2017 + 900*pow(lmMsq,2) - 
                       1350*pow(lmMst1,2) - 
                       15*lmMsq*(-532 + 195*lmMst1 - 75*lmMst2) + 
                       3750*lmMst2 - 3375*pow(lmMst2,2) + 
                       15*lmMst1*(-782 + 375*lmMst2))*pow(Msq,2)*
                     pow(Mst2,2) + 
                    1125*(-195 + 60*lmMsq*(3 + 2*lmMst1 - 2*lmMst2) - 
                       4*lmMst2 + 120*pow(lmMst2,2) - 
                       8*lmMst1*(22 + 15*lmMst2))*pow(Mst2,4) + 
                    4*pow(Msq,4)*
                     (7874051 + 303750*pow(lmMsq,2) - 
                       582750*pow(lmMst1,3) + 7815060*lmMst2 + 
                       1978425*pow(lmMst2,2) - 
                       713250*pow(lmMst2,3) + 
                       101250*lmMsq*
                        (-9 + 2*pow(lmMst1,2) - 6*lmMst2 - 
                         4*lmMst1*lmMst2 + 2*pow(lmMst2,2)) - 
                       675*pow(lmMst1,2)*
                        (989 + 290*lmMst2 - 480*lmMt) + 324000*lmMt + 
                       648000*lmMst2*lmMt + 
                       324000*pow(lmMst2,2)*lmMt - 14000*OepS2 + 
                       708750*S2 - 283500*lmMst2*S2 + 21000*T1ep + 
                       6562875*z2 + 499500*lmMst2*z2 + 
                       15750*pow(z2,2) + 
                       90*lmMst1*
                        (-6359 + 10035*lmMst2 + 16575*pow(lmMst2,2) - 
                         7200*lmMt - 7200*lmMst2*lmMt + 3150*S2 + 
                         8850*z2) - 532500*z3 + 10500*z4)))/
                (60750.*pow(Msq,4)*pow(Mst2,2))))/Tbeta + 
          (Mst1*pow(MuSUSY,2)*(-1 + pow(Sbeta,2))*
             (3*pow(Dmglst1,2)*
                (240*pow(Msq,2)*
                   (-3*pow(Mst2,4) + 
                     pow(Mst1,4)*
                      (203 - 378*pow(lmMst1,2) + 
                        72*lmMsq*(-2 + 3*lmMst1 - 3*lmMst2) + 
                        366*lmMst2 - 162*pow(lmMst2,2) + 
                        6*lmMst1*(-37 + 90*lmMst2) - 324*z2) + 
                     pow(Mst1,2)*pow(Mst2,2)*
                      (557 - 126*lmMst1 - 36*pow(lmMst1,2) + 
                        72*lmMsq*(-2 + lmMst1 - lmMst2) + 270*lmMst2 + 
                        36*pow(lmMst2,2) + 72*z2)) + 
                  5*pow(Mst2,2)*
                   ((-467 + 12*lmMsq - 12*lmMst2)*pow(Mst1,2)*
                      pow(Mst2,2) + 
                     (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                     18*pow(Mst1,4)*
                      (928 - 145*lmMst1 - 90*pow(lmMst1,2) + 
                        180*lmMsq*(-2 + lmMst1 - lmMst2) + 505*lmMst2 + 
                        90*pow(lmMst2,2) + 180*z2)) + 
                  2*pow(Msq,4)*
                   (pow(Mst1,2)*
                      (59579 + 20088*B4 - 324*DN - 39240*lmMsq - 
                        2160*pow(lmMsq,2) - 1344*lmMst1 + 
                        46440*lmMsq*lmMst1 + 
                        3240*pow(lmMsq,2)*lmMst1 - 
                        13914*pow(lmMst1,2) - 
                        29160*lmMsq*pow(lmMst1,2) + 
                        33084*pow(lmMst1,3) + 33840*lmMst2 - 
                        42120*lmMsq*lmMst2 - 
                        3240*pow(lmMsq,2)*lmMst2 - 
                        39924*lmMst1*lmMst2 + 
                        51840*lmMsq*lmMst1*lmMst2 - 
                        23796*pow(lmMst1,2)*lmMst2 + 
                        31950*pow(lmMst2,2) - 
                        22680*lmMsq*pow(lmMst2,2) - 
                        25740*lmMst1*pow(lmMst2,2) + 
                        16452*pow(lmMst2,3) + 110196*z2 - 
                        45360*lmMsq*z2 - 15624*lmMst1*z2 + 
                        84744*lmMst2*z2 - 20736*pow(z2,2) - 16308*z3 + 
                        99144*lmMst1*z3 - 99144*lmMst2*z3 - 62532*z4) + 
                     3*pow(Mst2,2)*
                      (413 + 408*B4 + 12*DN + 8520*lmMsq - 
                        720*pow(lmMsq,2) - 3146*lmMst1 - 
                        1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 - 
                        918*pow(lmMst1,2) - 360*lmMsq*pow(lmMst1,2) + 
                        200*pow(lmMst1,3) - 15206*lmMst2 + 
                        2520*lmMsq*lmMst2 - 360*pow(lmMsq,2)*lmMst2 + 
                        708*lmMst1*lmMst2 + 360*pow(lmMst1,2)*lmMst2 - 
                        4782*pow(lmMst2,2) + 
                        360*lmMsq*pow(lmMst2,2) + 
                        24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                        7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                        2304*lmMst2*z2 - 384*pow(z2,2) - 6708*z3 - 
                        216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))) + 
               3*Dmglst1*Mgl*(720*pow(Msq,2)*
                   (-pow(Mst2,4) + 
                     2*pow(Mst1,4)*
                      (29 - 24*pow(lmMst1,2) + 
                        6*lmMsq*(-2 + 3*lmMst1 - 3*lmMst2) + 
                        48*lmMst2 - 6*pow(lmMst2,2) + 
                        6*lmMst1*(-6 + 5*lmMst2) - 12*z2) + 
                     2*pow(Mst1,2)*pow(Mst2,2)*
                      (41 - 10*lmMst1 - 3*pow(lmMst1,2) + 
                        6*lmMsq*(-2 + lmMst1 - lmMst2) + 22*lmMst2 + 
                        3*pow(lmMst2,2) + 6*z2)) + 
                  5*pow(Mst2,2)*
                   ((-251 + 12*lmMsq - 12*lmMst2)*pow(Mst1,2)*
                      pow(Mst2,2) + 
                     (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                     6*pow(Mst1,4)*
                      (818 - 117*lmMst1 - 90*pow(lmMst1,2) + 
                        180*lmMsq*(-2 + lmMst1 - lmMst2) + 477*lmMst2 + 
                        90*pow(lmMst2,2) + 180*z2)) + 
                  2*pow(Msq,4)*
                   (pow(Mst1,2)*
                      (-13969 + 11880*B4 - 108*DN + 4320*lmMsq - 
                        2160*pow(lmMsq,2) + 16728*lmMst1 + 
                        3240*lmMsq*lmMst1 + 3240*pow(lmMsq,2)*lmMst1 + 
                        21978*pow(lmMst1,2) - 
                        16200*lmMsq*pow(lmMst1,2) + 
                        16848*pow(lmMst1,3) - 49128*lmMst2 + 
                        1080*lmMsq*lmMst2 - 3240*pow(lmMsq,2)*lmMst2 - 
                        26460*lmMst1*lmMst2 + 
                        25920*lmMsq*lmMst1*lmMst2 - 
                        9648*pow(lmMst1,2)*lmMst2 - 
                        10494*pow(lmMst2,2) - 
                        9720*lmMsq*pow(lmMst2,2) - 
                        12240*lmMst1*pow(lmMst2,2) + 
                        5040*pow(lmMst2,3) + 24732*z2 - 
                        19440*lmMsq*z2 - 3312*lmMst1*z2 + 
                        30960*lmMst2*z2 - 12096*pow(z2,2) + 33264*z3 + 
                        48600*lmMst1*z3 - 48600*lmMst2*z3 - 18252*z4) + 
                     3*pow(Mst2,2)*
                      (-11337 + 408*B4 + 12*DN + 6480*lmMsq - 
                        720*pow(lmMsq,2) - 2190*lmMst1 - 
                        1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 + 
                        234*pow(lmMst1,2) - 360*lmMsq*pow(lmMst1,2) + 
                        200*pow(lmMst1,3) - 13986*lmMst2 + 
                        2520*lmMsq*lmMst2 - 360*pow(lmMsq,2)*lmMst2 + 
                        708*lmMst1*lmMst2 + 360*pow(lmMst1,2)*lmMst2 - 
                        4782*pow(lmMst2,2) + 
                        360*lmMsq*pow(lmMst2,2) + 
                        24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                        7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                        2304*lmMst2*z2 - 384*pow(z2,2) + 1392*z3 - 
                        216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))) + 
               pow(Mgl,2)*(720*pow(Msq,2)*
                   (4*(14 - 21*lmMst1 - 9*pow(lmMst1,2) + 
                        lmMsq*(-6 + 9*lmMst1 - 9*lmMst2) + 27*lmMst2 + 
                        9*lmMst1*lmMst2)*pow(Mst1,4) - 
                     3*pow(Mst2,4) + 
                     2*pow(Mst1,2)*pow(Mst2,2)*
                      (34 - 8*lmMst1 - 3*pow(lmMst1,2) + 
                        6*lmMsq*(-2 + lmMst1 - lmMst2) + 20*lmMst2 + 
                        3*pow(lmMst2,2) + 6*z2)) + 
                  15*pow(Mst2,2)*
                   ((-107 + 12*lmMsq - 12*lmMst2)*pow(Mst1,2)*
                      pow(Mst2,2) + 
                     (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                     6*pow(Mst1,4)*
                      (134 - 9*lmMst1 - 18*pow(lmMst1,2) + 
                        36*lmMsq*(-2 + lmMst1 - lmMst2) + 81*lmMst2 + 
                        18*pow(lmMst2,2) + 36*z2)) + 
                  2*pow(Msq,4)*
                   (9*pow(Mst2,2)*
                      (-13317 + 408*B4 + 12*DN + 4320*lmMsq - 
                        720*pow(lmMsq,2) + 474*lmMst1 - 
                        1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 + 
                        1002*pow(lmMst1,2) - 
                        360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                        12810*lmMst2 + 2520*lmMsq*lmMst2 - 
                        360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                        360*pow(lmMst1,2)*lmMst2 - 
                        4782*pow(lmMst2,2) + 
                        360*lmMsq*pow(lmMst2,2) + 
                        24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                        7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                        2304*lmMst2*z2 - 384*pow(z2,2) + 3192*z3 - 
                        216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4) + 
                     pow(Mst1,2)*
                      (-107299 + 19224*B4 + 108*DN + 32400*lmMsq - 
                        6480*pow(lmMsq,2) + 146472*lmMst1 - 
                        42120*lmMsq*lmMst1 + 9720*pow(lmMsq,2)*lmMst1 + 
                        78822*pow(lmMst1,2) - 
                        22680*lmMsq*pow(lmMst1,2) + 
                        18072*pow(lmMst1,3) - 250584*lmMst2 + 
                        55080*lmMsq*lmMst2 - 9720*pow(lmMsq,2)*lmMst2 - 
                        8388*lmMst1*lmMst2 + 25920*lmMsq*lmMst1*lmMst2 - 
                        648*pow(lmMst1,2)*lmMst2 - 
                        101538*pow(lmMst2,2) - 
                        3240*lmMsq*pow(lmMst2,2) - 
                        9720*lmMst1*pow(lmMst2,2) - 
                        7704*pow(lmMst2,3) - 86652*z2 - 6480*lmMsq*z2 + 
                        14688*lmMst1*z2 - 14688*lmMst2*z2 - 
                        19008*pow(z2,2) + 124200*z3 + 44712*lmMst1*z3 - 
                        44712*lmMst2*z3 + 33804*z4)))))/
           (pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)*pow(Sbeta,2))))/486. + 
     pow(Mt,2)*pow(s2t,2)*((2*
           (5108 + 900*pow(lmMsq,2) + 
             15*lmMsq*(-218 + 75*lmMst1 - 195*lmMst2) + 6270*lmMst2 + 
             2025*pow(lmMst2,2) - 375*lmMst1*(8 + 3*lmMst2))*pow(Mst2,4)
)/(2025.*pow(Msq,2)) - (20*pow(Msq,2)*
           (2 + (-1 + lmMst1 - lmMst2)*shiftst1 + 
             (-1 - lmMst1 + lmMst2)*shiftst2)*(-1 + 2*lmMsq + 2*z2))/3. - 
        (2*pow(Mst2,2)*(10*pow(Msq,2)*(-1 + shiftst1)*
              (-1 + 2*lmMsq + 2*z2) + 
             pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2)))/
         (3.*pow(Mst1,2)) + (Dmglst1*
           (360*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
              ((-131 + 120*lmMsq - 78*lmMst1 - 42*lmMst2)*pow(Mst1,2) + 
                3*(7 - 20*lmMsq + 26*lmMst1 - 6*lmMst2)*pow(Mst2,2)) - 
             45*pow(Mst1,2)*pow(Mst2,4)*
              ((-17 + 324*lmMsq - 408*lmMst1 + 84*lmMst2)*pow(Mst1,2) + 
                3*(13 - 12*lmMsq + 12*lmMst2)*pow(Mst2,2)) - 
             2*pow(Msq,4)*(pow(Mst1,4)*
                 (63295 + 4860*pow(lmMsq,2) + 29520*pow(lmMst1,3) - 
                   1620*lmMsq*(-9 + 20*lmMst1 - 14*lmMst2) - 
                   222366*lmMst2 + 97488*pow(lmMst2,2) + 
                   32688*pow(lmMst2,3) - 10368*lmMt - 
                   36288*lmMst2*lmMt - 20736*pow(lmMst2,2)*lmMt - 
                   144*pow(lmMst1,2)*(-1355 + 39*lmMst2 + 144*lmMt) + 
                   66456*z2 + 105840*lmMst2*z2 - 
                   6*lmMst1*(-42083 + 45744*lmMst2 + 
                      9432*pow(lmMst2,2) - 6048*lmMt - 
                      6912*lmMst2*lmMt + 10728*z2) - 42984*z3) + 
                18*pow(Mst2,4)*
                 (-158 + 270*pow(lmMsq,2) + 459*pow(lmMst1,2) - 
                   60*lmMsq*(-4 + 9*lmMst1) - 96*lmMst2 + 
                   27*pow(lmMst2,2) + 2*lmMst1*(-35 + 69*lmMst2) + 
                   594*z2 - 330*z3) + 
                pow(Mst1,2)*pow(Mst2,2)*
                 (-156781 + 864*B4 + 432*DN + 10260*lmMsq - 
                   9720*pow(lmMsq,2) + 2850*lmMst1 + 9720*lmMsq*lmMst1 - 
                   7524*pow(lmMst1,2) + 7200*pow(lmMst1,3) - 
                   131946*lmMst2 + 9720*lmMsq*lmMst2 - 2232*lmMst1*lmMst2 - 
                   2592*pow(lmMst1,2)*lmMst2 - 36900*pow(lmMst2,2) - 
                   6048*lmMst1*pow(lmMst2,2) + 1440*pow(lmMst2,3) - 
                   10368*lmMt + 15552*lmMst1*lmMt - 
                   5184*pow(lmMst1,2)*lmMt - 15552*lmMst2*lmMt + 
                   10368*lmMst1*lmMst2*lmMt - 5184*pow(lmMst2,2)*lmMt - 
                   110664*z2 - 4320*lmMst1*z2 - 16416*lmMst2*z2 + 
                   40284*z3 + 2592*lmMst1*z3 - 2592*lmMst2*z3 - 6480*z4))))/
         (486.*Mgl*pow(Msq,4)*pow(Mst2,2)) - 
        (pow(Dmglst1,2)*(-360*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
              ((-577 + 600*lmMsq - 354*lmMst1 - 246*lmMst2)*
                 pow(Mst1,2) + 
                3*(9 - 100*lmMsq + 118*lmMst1 - 18*lmMst2)*pow(Mst2,2)) + 
             45*pow(Mst1,2)*pow(Mst2,4)*
              ((497 + 1980*lmMsq - 2472*lmMst1 + 492*lmMst2)*
                 pow(Mst1,2) + 
                9*(13 - 12*lmMsq + 12*lmMst2)*pow(Mst2,2)) + 
             2*pow(Msq,4)*(pow(Mst1,4)*
                 (135281 + 14580*pow(lmMsq,2) + 133344*pow(lmMst1,3) - 
                   1620*lmMsq*(-103 + 100*lmMst1 - 82*lmMst2) - 
                   460266*lmMst2 + 643824*pow(lmMst2,2) + 
                   177696*pow(lmMst2,3) - 114048*lmMt - 
                   247104*lmMst2*lmMt - 103680*pow(lmMst2,2)*lmMt - 
                   144*pow(lmMst1,2)*(-5257 + 186*lmMst2 + 720*lmMt) + 
                   534888*z2 + 614736*lmMst2*z2 - 
                   6*lmMst1*(-91201 + 47376*pow(lmMst2,2) - 
                      41184*lmMt - 48*lmMst2*(-4651 + 720*lmMt) + 54072*z2
) - 472824*z3) + 9*pow(Mst2,4)*
                 (8802 + 1620*pow(lmMsq,2) - 2924*lmMst1 + 
                   1986*pow(lmMst1,2) - 120*lmMsq*(-26 + 27*lmMst1) - 
                   888*lmMst2 + 828*lmMst1*lmMst2 + 162*pow(lmMst2,2) + 
                   3564*z2 - 10437*z3) + 
                3*pow(Mst1,2)*pow(Mst2,2)*
                 (-266599 + 864*B4 + 432*DN + 5220*lmMsq - 
                   9720*pow(lmMsq,2) - 10350*lmMst1 + 9720*lmMsq*lmMst1 - 
                   7236*pow(lmMst1,2) + 7200*pow(lmMst1,3) - 
                   124698*lmMst2 + 9720*lmMsq*lmMst2 - 2808*lmMst1*lmMst2 - 
                   2592*pow(lmMst1,2)*lmMst2 - 34308*pow(lmMst2,2) - 
                   6048*lmMst1*pow(lmMst2,2) + 1440*pow(lmMst2,3) - 
                   16704*lmMt + 20160*lmMst1*lmMt - 
                   5184*pow(lmMst1,2)*lmMt - 20160*lmMst2*lmMt + 
                   10368*lmMst1*lmMst2*lmMt - 5184*pow(lmMst2,2)*lmMt - 
                   110664*z2 - 4320*lmMst1*z2 - 16416*lmMst2*z2 + 
                   144567*z3 + 2592*lmMst1*z3 - 2592*lmMst2*z3 - 6480*z4))))/
         (972.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,2)) + 
        pow(Mst1,4)*((2*(-22642 + 900*pow(lmMsq,2) + 
                2025*pow(lmMst1,2) - 
                15*lmMsq*(-1282 + 195*lmMst1 - 75*lmMst2) - 7500*lmMst2 - 
                15*lmMst1*(782 + 75*lmMst2)))/(2025.*pow(Msq,2)) + 
           ((2.8203865673253428 - (5*pow(lmMsq,2))/21. + 
                (16*pow(lmMst1,2))/21. + 
                lmMst1*(9.152834467120181 - lmMst2) - (113*lmMst2)/45. + 
                lmMsq*(-6.64172335600907 - (11*lmMst1)/21. + lmMst2))*
              pow(Mst2,2))/pow(Msq,4) + 
           (-238.25271580142933 - 10*pow(lmMsq,2) - 
              (836*pow(lmMst1,3))/27. + 
              (10*lmMsq*(5 + 10*lmMst1 - 4*lmMst2))/3. + 
              (4731149*lmMst2)/11025. - (46219*pow(lmMst2,2))/945. - 
              (892*pow(lmMst2,3))/27. + (64*lmMst2*lmMt)/3. + 
              (64*pow(lmMst2,2)*lmMt)/3. + 
              pow(lmMst1,2)*(-281.7978835978836 - (124*lmMst2)/9. + 
                 (64*lmMt)/3.) + (16*OepS2)/729. - (74*S2)/27. + 
              (4*lmMst2*S2)/9. - (8*T1ep)/243. + (295*z2)/243. - 
              (220*lmMst2*z2)/3. - (2*pow(z2,2))/81. + 
              lmMst1*(-543.1291609977325 + (280598*lmMst2)/945. + 
                 (700*pow(lmMst2,2))/9. - (64*lmMt)/3. - 
                 (128*lmMst2*lmMt)/3. - (4*S2)/9. + (220*z2)/3.) + 
              (1324*z3)/243. - (4*z4)/243.)/pow(Mst2,2)) + 
        (pow(Mst2,2)*(-4501 + 288*DN + 10896*lmMst1 - 
             2952*pow(lmMst1,2) + 696*pow(lmMst1,3) + 
             1080*pow(lmMsq,2)*(-3 + lmMst1 - lmMst2) - 17592*lmMst2 + 
             8064*lmMst1*lmMst2 + 864*pow(lmMst1,2)*lmMst2 - 
             13752*pow(lmMst2,2) + 3168*lmMst1*pow(lmMst2,2) - 
             4728*pow(lmMst2,3) + 
             360*lmMsq*(3 + lmMst1*(4 - 6*lmMst2) + 14*lmMst2 + 
                6*pow(lmMst2,2)) - 96*OepS2 + 972*S2 + 1944*lmMst1*S2 - 
             1944*lmMst2*S2 - 216*shiftst3 + 216*lmMst1*shiftst3 + 
             216*lmMst2*shiftst3 - 432*lmMst1*lmMst2*shiftst3 + 
             432*pow(lmMst2,2)*shiftst3 + 144*T1ep - 10998*z2 + 
             432*lmMst1*z2 - 432*lmMst2*z2 + 432*shiftst3*z2 - 
             432*lmMst1*shiftst3*z2 + 432*lmMst2*shiftst3*z2 - 
             180*pow(z2,2) - 3096*z3 - 648*z4))/324. + 
        pow(Mst1,2)*(268.4533251028807 - (8*DN)/9. - (100*lmMsq)/3. + 
           20*pow(lmMsq,2) - (9406*lmMst1)/225. - (40*lmMsq*lmMst1)/9. - 
           (10*pow(lmMsq,2)*lmMst1)/3. - (91*pow(lmMst1,2))/5. + 
           (20*lmMsq*pow(lmMst1,2))/3. - (64*pow(lmMst1,3))/3. + 
           (67406*lmMst2)/225. - (320*lmMsq*lmMst2)/9. + 
           (10*pow(lmMsq,2)*lmMst2)/3. + (698*lmMst1*lmMst2)/45. - 
           (20*lmMsq*lmMst1*lmMst2)/3. - (82*pow(lmMst1,2)*lmMst2)/9. + 
           (4601*pow(lmMst2,2))/45. + (118*lmMst1*pow(lmMst2,2))/3. - 
           (80*pow(lmMst2,3))/9. + (32*lmMt)/3. - (64*lmMst1*lmMt)/3. + 
           (32*pow(lmMst1,2)*lmMt)/3. + (64*lmMst2*lmMt)/3. - 
           (64*lmMst1*lmMst2*lmMt)/3. + (32*pow(lmMst2,2)*lmMt)/3. - 
           (2*(3091 + 1800*pow(lmMsq,2) - 1350*pow(lmMst1,2) + 
                10020*lmMst2 - 1350*pow(lmMst2,2) - 
                30*lmMsq*(-157 + 60*lmMst1 + 60*lmMst2) + 
                30*lmMst1*(-491 + 150*lmMst2))*pow(Mst2,2))/
            (2025.*pow(Msq,2)) - 
           ((109502 + 11025*pow(lmMsq,2) - 
                105*lmMsq*(991 + 441*lmMst1 - 231*lmMst2) + 
                39228*lmMst2 - 35280*pow(lmMst2,2) + 
                9261*lmMst1*(7 + 5*lmMst2))*pow(Mst2,4))/
            (46305.*pow(Msq,4)) - (40*OepS2)/243. + (61*S2)/3. + 
           (10*lmMst1*S2)/3. - (10*lmMst2*S2)/3. + (20*T1ep)/81. + 
           (40285*z2)/162. + (224*lmMst1*z2)/9. + (160*lmMst2*z2)/9. + 
           (29*pow(z2,2))/27. - 
           (20*pow(Msq,2)*(-1 + shiftst2)*(-1 + 2*lmMsq + 2*z2))/
            (3.*pow(Mst2,2)) - (646*z3)/81. + (190*z4)/81.) + 
        (Mst1*MuSUSY*(12*(-720*pow(Msq,2)*pow(Mst2,2) + 
                5*(11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                6*pow(Msq,4)*
                 (-13317 + 408*B4 + 12*DN + 4320*lmMsq - 
                   720*pow(lmMsq,2) + 474*lmMst1 - 1080*lmMsq*lmMst1 + 
                   360*pow(lmMsq,2)*lmMst1 + 1002*pow(lmMst1,2) - 
                   360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                   12810*lmMst2 + 2520*lmMsq*lmMst2 - 
                   360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                   360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                   360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                   584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                   768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) + 
                   3192*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4)) + 
             (8*pow(Mst1,2)*
                (15*(-59 + 12*lmMsq - 12*lmMst2)*pow(Mst2,4) + 
                  360*pow(Msq,2)*pow(Mst2,2)*
                   (71 - 16*lmMst1 - 6*pow(lmMst1,2) + 
                     12*lmMsq*(-2 + lmMst1 - lmMst2) + 40*lmMst2 + 
                     6*pow(lmMst2,2) + 12*z2) + 
                  2*pow(Msq,4)*
                   (6277 + 7776*B4 + 71103*lmMst1 + 
                     34902*pow(lmMst1,2) + 8136*pow(lmMst1,3) + 
                     3240*pow(lmMsq,2)*(lmMst1 - lmMst2) - 
                     67647*lmMst2 - 7380*lmMst1*lmMst2 - 
                     1944*pow(lmMst1,2)*lmMst2 - 
                     29250*pow(lmMst2,2) - 
                     4968*lmMst1*pow(lmMst2,2) - 1224*pow(lmMst2,3) - 
                     9468*z2 + 3888*lmMst1*z2 + 3024*lmMst2*z2 - 
                     7776*pow(z2,2) - 
                     3240*lmMsq*
                      (1 + 5*lmMst1 + 3*pow(lmMst1,2) - 5*lmMst2 - 
                        4*lmMst1*lmMst2 + pow(lmMst2,2) + 2*z2) + 
                     47736*z3 + 23328*lmMst1*z3 - 23328*lmMst2*z3 + 
                     3888*z4)))/pow(Mst2,2) + 
             (3*pow(Mst1,4)*
                (-1920*pow(Msq,2)*pow(Mst2,2)*
                   (6 + 15*pow(lmMst1,2) - 34*lmMst2 + 
                     12*lmMsq*lmMst2 + 3*pow(lmMst2,2) - 
                     2*lmMst1*(-17 + 6*lmMsq + 9*lmMst2) + 6*z2) + 
                  20*pow(Mst2,4)*
                   (911 - 54*lmMst1 - 108*pow(lmMst1,2) + 
                     12*lmMsq*(-37 + 18*lmMst1 - 18*lmMst2) + 
                     498*lmMst2 + 108*pow(lmMst2,2) + 216*z2) + 
                  pow(Msq,4)*
                   (240861 + 41472*B4 + 378388*lmMst1 + 
                     78168*pow(lmMst1,2) + 6624*pow(lmMst1,3) + 
                     17280*pow(lmMsq,2)*(lmMst1 - lmMst2) - 
                     406036*lmMst2 + 139728*lmMst1*lmMst2 + 
                     63072*pow(lmMst1,2)*lmMst2 - 
                     217896*pow(lmMst2,2) - 
                     63072*lmMst1*pow(lmMst2,2) - 
                     6624*pow(lmMst2,3) - 85872*z2 - 20160*lmMst1*z2 + 
                     57024*lmMst2*z2 - 41472*pow(z2,2) - 
                     4320*lmMsq*
                      (-7 + 10*lmMst1 + 12*pow(lmMst1,2) - 10*lmMst2 - 
                        16*lmMst1*lmMst2 + 4*pow(lmMst2,2) + 8*z2) + 
                     105120*z3 + 124416*lmMst1*z3 - 124416*lmMst2*z3 + 
                     20736*z4)))/pow(Mst2,4) + 
             (pow(Dmglst1,2)*
                (-2880*pow(Msq,2)*pow(Mst2,2)*
                   (3*pow(Mst2,4) - 
                     2*pow(Mst1,2)*pow(Mst2,2)*
                      (280 - 63*lmMst1 - 18*pow(lmMst1,2) + 
                        36*lmMsq*(-2 + lmMst1 - lmMst2) + 135*lmMst2 + 
                        18*pow(lmMst2,2) + 36*z2) + 
                     6*pow(Mst1,4)*
                      (59 + 57*pow(lmMst1,2) + 
                        8*(-2 + 3*lmMsq)*lmMst2 + 33*pow(lmMst2,2) - 
                        2*lmMst1*(-8 + 12*lmMsq + 45*lmMst2) + 66*z2)) + 
                  60*pow(Mst2,4)*
                   (2*(-239 + 12*lmMsq - 12*lmMst2)*pow(Mst1,2)*
                      pow(Mst2,2) + 
                     (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                     pow(Mst1,4)*
                      (17171 - 2610*lmMst1 - 1620*pow(lmMst1,2) + 
                        12*lmMsq*(-541 + 270*lmMst1 - 270*lmMst2) + 
                        9102*lmMst2 + 1620*pow(lmMst2,2) + 3240*z2)) + 
                  pow(Msq,4)*
                   (pow(Mst1,4)*
                      (10707109 + 452736*B4 - 8640*DN - 790560*lmMsq + 
                        1785300*lmMst1 + 4069440*lmMsq*lmMst1 + 
                        51840*pow(lmMsq,2)*lmMst1 - 
                        2158056*pow(lmMst1,2) - 
                        673920*lmMsq*pow(lmMst1,2) + 
                        470592*pow(lmMst1,3) - 1149396*lmMst2 - 
                        4069440*lmMsq*lmMst2 - 
                        51840*pow(lmMsq,2)*lmMst2 - 
                        878256*lmMst1*lmMst2 + 
                        1244160*lmMsq*lmMst1*lmMst2 + 
                        219456*pow(lmMst1,2)*lmMst2 + 
                        3036312*pow(lmMst2,2) - 
                        570240*lmMsq*pow(lmMst2,2) - 
                        1325376*lmMst1*pow(lmMst2,2) + 
                        635328*pow(lmMst2,3) + 2994192*z2 - 
                        1140480*lmMsq*z2 - 2381184*lmMst1*z2 + 
                        4150656*lmMst2*z2 - 470016*pow(z2,2) - 
                        8167392*z3 + 2395008*lmMst1*z3 - 
                        2395008*lmMst2*z3 - 1708992*z4) + 
                     48*pow(Mst1,2)*pow(Mst2,2)*
                      (29170 + 9432*B4 - 180*DN - 32400*lmMsq + 
                        4047*lmMst1 + 24840*lmMsq*lmMst1 + 
                        1080*pow(lmMsq,2)*lmMst1 - 
                        5580*pow(lmMst1,2) - 
                        14040*lmMsq*pow(lmMst1,2) + 
                        16242*pow(lmMst1,3) + 39729*lmMst2 - 
                        24840*lmMsq*lmMst2 - 
                        1080*pow(lmMsq,2)*lmMst2 - 
                        21024*lmMst1*lmMst2 + 
                        25920*lmMsq*lmMst1*lmMst2 - 
                        12438*pow(lmMst1,2)*lmMst2 + 
                        23148*pow(lmMst2,2) - 
                        11880*lmMsq*pow(lmMst2,2) - 
                        12906*lmMst1*pow(lmMst2,2) + 
                        9102*pow(lmMst2,3) + 66384*z2 - 
                        23760*lmMsq*z2 - 8964*lmMst1*z2 + 
                        45828*lmMst2*z2 - 9792*pow(z2,2) + 1908*z3 + 
                        49896*lmMst1*z3 - 49896*lmMst2*z3 - 35604*z4) + 
                     72*pow(Mst2,4)*
                      (413 + 408*B4 + 12*DN + 8520*lmMsq - 
                        720*pow(lmMsq,2) - 3146*lmMst1 - 
                        1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 - 
                        918*pow(lmMst1,2) - 360*lmMsq*pow(lmMst1,2) + 
                        200*pow(lmMst1,3) - 15206*lmMst2 + 
                        2520*lmMsq*lmMst2 - 360*pow(lmMsq,2)*lmMst2 + 
                        708*lmMst1*lmMst2 + 360*pow(lmMst1,2)*lmMst2 - 
                        4782*pow(lmMst2,2) + 
                        360*lmMsq*pow(lmMst2,2) + 
                        24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                        7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                        2304*lmMst2*z2 - 384*pow(z2,2) - 6708*z3 - 
                        216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))))/
              (pow(Mgl,2)*pow(Mst2,4)) + 
             (Dmglst1*(-8640*pow(Msq,2)*pow(Mst2,2)*
                   (pow(Mst2,4) + 
                     pow(Mst1,2)*pow(Mst2,2)*
                      (-83 + 20*lmMst1 + 6*pow(lmMst1,2) - 
                        12*lmMsq*(-2 + lmMst1 - lmMst2) - 44*lmMst2 - 
                        6*pow(lmMst2,2) - 12*z2) + 
                     2*pow(Mst1,4)*
                      (12 + 21*pow(lmMst1,2) - 26*lmMst2 + 
                        12*lmMsq*lmMst2 + 9*pow(lmMst2,2) - 
                        2*lmMst1*(-13 + 6*lmMsq + 15*lmMst2) + 18*z2)) + 
                  60*pow(Mst2,4)*
                   (2*(-131 + 12*lmMsq - 12*lmMst2)*pow(Mst1,2)*
                      pow(Mst2,2) + 
                     (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                     pow(Mst1,4)*
                      (5159 - 702*lmMst1 - 540*pow(lmMst1,2) + 
                        12*lmMsq*(-181 + 90*lmMst1 - 90*lmMst2) + 
                        2874*lmMst2 + 540*pow(lmMst2,2) + 1080*z2)) + 
                  pow(Msq,4)*
                   (pow(Mst1,4)*
                      (3539195 + 255744*B4 - 3456*DN + 194400*lmMsq + 
                        718092*lmMst1 + 1010880*lmMsq*lmMst1 + 
                        51840*pow(lmMsq,2)*lmMst1 - 
                        166680*pow(lmMst1,2) - 
                        362880*lmMsq*pow(lmMst1,2) + 
                        186336*pow(lmMst1,3) - 1132812*lmMst2 - 
                        1010880*lmMsq*lmMst2 - 
                        51840*pow(lmMsq,2)*lmMst2 - 
                        326736*lmMst1*lmMst2 + 
                        622080*lmMsq*lmMst1*lmMst2 + 
                        242784*pow(lmMst1,2)*lmMst2 + 
                        493416*pow(lmMst2,2) - 
                        259200*lmMsq*pow(lmMst2,2) - 
                        685152*lmMst1*pow(lmMst2,2) + 
                        256032*pow(lmMst2,3) + 934128*z2 - 
                        518400*lmMsq*z2 - 872640*lmMst1*z2 + 
                        1646784*lmMst2*z2 - 262656*pow(z2,2) - 
                        1886112*z3 + 1181952*lmMst1*z3 - 
                        1181952*lmMst2*z3 - 646272*z4) + 
                     48*pow(Mst1,2)*pow(Mst2,2)*
                      (10021 + 5328*B4 - 72*DN - 7560*lmMsq + 
                        11649*lmMst1 + 3240*lmMsq*lmMst1 + 
                        1080*pow(lmMsq,2)*lmMst1 + 
                        10638*pow(lmMst1,2) - 
                        7560*lmMsq*pow(lmMst1,2) + 
                        8124*pow(lmMst1,3) - 3585*lmMst2 - 
                        3240*lmMsq*lmMst2 - 1080*pow(lmMsq,2)*lmMst2 - 
                        14292*lmMst1*lmMst2 + 12960*lmMsq*lmMst1*lmMst2 - 
                        5364*pow(lmMst1,2)*lmMst2 + 
                        1926*pow(lmMst2,2) - 
                        5400*lmMsq*pow(lmMst2,2) - 
                        6156*lmMst1*pow(lmMst2,2) + 
                        3396*pow(lmMst2,3) + 23652*z2 - 
                        10800*lmMsq*z2 - 2808*lmMst1*z2 + 
                        18936*lmMst2*z2 - 5472*pow(z2,2) + 14544*z3 + 
                        24624*lmMst1*z3 - 24624*lmMst2*z3 - 13464*z4) + 
                     72*pow(Mst2,4)*
                      (-11337 + 408*B4 + 12*DN + 6480*lmMsq - 
                        720*pow(lmMsq,2) - 2190*lmMst1 - 
                        1080*lmMsq*lmMst1 + 360*pow(lmMsq,2)*lmMst1 + 
                        234*pow(lmMst1,2) - 360*lmMsq*pow(lmMst1,2) + 
                        200*pow(lmMst1,3) - 13986*lmMst2 + 
                        2520*lmMsq*lmMst2 - 360*pow(lmMsq,2)*lmMst2 + 
                        708*lmMst1*lmMst2 + 360*pow(lmMst1,2)*lmMst2 - 
                        4782*pow(lmMst2,2) + 360*lmMsq*pow(lmMst2,2) + 
                        24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                        7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                        2304*lmMst2*z2 - 384*pow(z2,2) + 1392*z3 - 
                        216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))))/
              (Mgl*pow(Mst2,4))))/(1296.*pow(Msq,4)*Tbeta) + 
        pow(MuSUSY,2)*(-83.61265432098766 - 4*B4 + (4*DN)/9. + 
           (185*lmMsq)/9. - (25*pow(lmMsq,2))/3. + (3781*lmMst1)/108. - 
           (25*lmMsq*lmMst1)/9. + (5*pow(lmMsq,2)*lmMst1)/3. - 
           (229*pow(lmMst1,2))/36. + (5*lmMsq*pow(lmMst1,2))/3. - 
           (11*pow(lmMst1,3))/18. - (14065*lmMst2)/108. + 
           (175*lmMsq*lmMst2)/9. - (5*pow(lmMsq,2)*lmMst2)/3. + 
           (583*lmMst1*lmMst2)/18. - (20*lmMsq*lmMst1*lmMst2)/3. + 
           (pow(lmMst1,2)*lmMst2)/6. - (731*pow(lmMst2,2))/12. + 
           5*lmMsq*pow(lmMst2,2) + (221*lmMst1*pow(lmMst2,2))/18. - 
           (71*pow(lmMst2,3))/6. - (8*OepS2)/27. - 33*S2 + 6*lmMst1*S2 - 
           6*lmMst2*S2 + 54181/(648.*pow(Sbeta,2)) + 
           (4*B4)/pow(Sbeta,2) - (4*DN)/(9.*pow(Sbeta,2)) - 
           (185*lmMsq)/(9.*pow(Sbeta,2)) + 
           (25*pow(lmMsq,2))/(3.*pow(Sbeta,2)) - 
           (3781*lmMst1)/(108.*pow(Sbeta,2)) + 
           (25*lmMsq*lmMst1)/(9.*pow(Sbeta,2)) - 
           (5*pow(lmMsq,2)*lmMst1)/(3.*pow(Sbeta,2)) + 
           (229*pow(lmMst1,2))/(36.*pow(Sbeta,2)) - 
           (5*lmMsq*pow(lmMst1,2))/(3.*pow(Sbeta,2)) + 
           (11*pow(lmMst1,3))/(18.*pow(Sbeta,2)) + 
           (14065*lmMst2)/(108.*pow(Sbeta,2)) - 
           (175*lmMsq*lmMst2)/(9.*pow(Sbeta,2)) + 
           (5*pow(lmMsq,2)*lmMst2)/(3.*pow(Sbeta,2)) - 
           (583*lmMst1*lmMst2)/(18.*pow(Sbeta,2)) + 
           (20*lmMsq*lmMst1*lmMst2)/(3.*pow(Sbeta,2)) - 
           (pow(lmMst1,2)*lmMst2)/(6.*pow(Sbeta,2)) + 
           (731*pow(lmMst2,2))/(12.*pow(Sbeta,2)) - 
           (5*lmMsq*pow(lmMst2,2))/pow(Sbeta,2) - 
           (221*lmMst1*pow(lmMst2,2))/(18.*pow(Sbeta,2)) + 
           (71*pow(lmMst2,3))/(6.*pow(Sbeta,2)) + 
           (8*OepS2)/(27.*pow(Sbeta,2)) + (33*S2)/pow(Sbeta,2) - 
           (6*lmMst1*S2)/pow(Sbeta,2) + (6*lmMst2*S2)/pow(Sbeta,2) + 
           ((939 + 30*lmMsq*(-12 + 5*lmMst1 - 5*lmMst2) + 760*lmMst2 + 
                150*pow(lmMst2,2) - 50*lmMst1*(8 + 3*lmMst2))*
              pow(Mst2,2)*(-1 + pow(Sbeta,2)))/
            (135.*pow(Msq,2)*pow(Sbeta,2)) + 
           ((7399303 + 176400*pow(lmMsq,2) + 
                420*lmMsq*(-9571 + 2940*lmMst1 - 3780*lmMst2) + 
                6571740*lmMst2 + 1411200*pow(lmMst2,2) - 
                82320*lmMst1*(31 + 15*lmMst2))*pow(Mst2,4)*
              (-1 + pow(Sbeta,2)))/(1.11132e7*pow(Msq,4)*pow(Sbeta,2)) 
+ (2*shiftst3)/3. - (2*lmMst1*shiftst3)/3. - (2*lmMst2*shiftst3)/3. + 
           (4*lmMst1*lmMst2*shiftst3)/3. - (4*pow(lmMst2,2)*shiftst3)/3. - 
           (2*shiftst3)/(3.*pow(Sbeta,2)) + 
           (2*lmMst1*shiftst3)/(3.*pow(Sbeta,2)) + 
           (2*lmMst2*shiftst3)/(3.*pow(Sbeta,2)) - 
           (4*lmMst1*lmMst2*shiftst3)/(3.*pow(Sbeta,2)) + 
           (4*pow(lmMst2,2)*shiftst3)/(3.*pow(Sbeta,2)) + (4*T1ep)/9. - 
           (4*T1ep)/(9.*pow(Sbeta,2)) + (113*z2)/3. - (10*lmMsq*z2)/3. - 
           (37*lmMst1*z2)/9. + (149*lmMst2*z2)/9. - 
           (113*z2)/(3.*pow(Sbeta,2)) + (10*lmMsq*z2)/(3.*pow(Sbeta,2)) + 
           (37*lmMst1*z2)/(9.*pow(Sbeta,2)) - 
           (149*lmMst2*z2)/(9.*pow(Sbeta,2)) - (4*shiftst3*z2)/3. + 
           (4*lmMst1*shiftst3*z2)/3. - (4*lmMst2*shiftst3*z2)/3. + 
           (4*shiftst3*z2)/(3.*pow(Sbeta,2)) - 
           (4*lmMst1*shiftst3*z2)/(3.*pow(Sbeta,2)) + 
           (4*lmMst2*shiftst3*z2)/(3.*pow(Sbeta,2)) + (35*pow(z2,2))/9. - 
           (35*pow(z2,2))/(9.*pow(Sbeta,2)) + 
           (10*pow(Msq,2)*(-1 + pow(Sbeta,2))*
              (1 + 2*lmMst1*(-1 + shiftst1) - 2*lmMst2*(-1 + shiftst1) - 
                2*shiftst1 + shiftst2)*(-1 + 2*lmMsq + 2*z2))/
            (3.*pow(Mst2,2)*pow(Sbeta,2)) - 
           ((-1 + pow(Sbeta,2))*
              (10*pow(Msq,2)*(-1 + shiftst1)*(-1 + 2*lmMsq + 2*z2) + 
                pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2)))/
            (3.*pow(Mst1,2)*pow(Sbeta,2)) - (328*z3)/9. + 
           (328*z3)/(9.*pow(Sbeta,2)) - 
           (Dmglst1*(-1 + pow(Sbeta,2))*
              (-1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                 (-(pow(Mst2,2)*
                      (82 - 93*lmMst1 - 9*pow(lmMst1,2) + 
                        6*lmMsq*(4 + 3*lmMst1 - 3*lmMst2) + 69*lmMst2 + 
                        9*pow(lmMst2,2) + 18*z2)) + 
                   2*pow(Mst1,2)*
                    (55 + lmMst1 - 21*pow(lmMst1,2) + 
                      6*lmMsq*(-5 + 7*lmMst1 - 7*lmMst2) + 29*lmMst2 + 
                      21*pow(lmMst2,2) + 42*z2)) + 
                180*pow(Mst1,2)*pow(Mst2,4)*
                 (-18*pow(Mst2,2) + 
                   pow(Mst1,2)*
                    (485 - 346*lmMst1 - 60*pow(lmMst1,2) + 
                      12*lmMsq*(1 + 10*lmMst1 - 10*lmMst2) + 334*lmMst2 + 
                      60*pow(lmMst2,2) + 120*z2)) + 
                pow(Msq,4)*(216*pow(Mst2,4)*
                    (7 + 180*pow(lmMsq,2) - 2*lmMst1 + 
                      178*pow(lmMst1,2) - 60*lmMsq*(-5 + 6*lmMst1) - 
                      226*lmMst2 + 220*lmMst1*lmMst2 + 
                      18*pow(lmMst2,2) + 396*z2 - 390*z3) + 
                   pow(Mst1,4)*
                    (-437365 + 10368*B4 + 8640*DN - 988500*lmMst1 + 
                      466560*lmMsq*lmMst1 - 77760*pow(lmMsq,2)*lmMst1 - 
                      503784*pow(lmMst1,2) + 
                      77760*lmMsq*pow(lmMst1,2) - 
                      16416*pow(lmMst1,3) + 822612*lmMst2 - 
                      466560*lmMsq*lmMst2 + 77760*pow(lmMsq,2)*lmMst2 - 
                      207216*lmMst1*lmMst2 + 
                      146016*pow(lmMst1,2)*lmMst2 + 
                      683352*pow(lmMst2,2) - 
                      77760*lmMsq*pow(lmMst2,2) - 
                      477792*lmMst1*pow(lmMst2,2) + 
                      348192*pow(lmMst2,3) + 232272*z2 - 
                      155520*lmMsq*z2 - 530496*lmMst1*z2 + 
                      834624*lmMst2*z2 - 6912*pow(z2,2) + 2640384*z3 + 
                      238464*lmMst1*z3 - 238464*lmMst2*z3 - 457920*z4) + 
                   288*pow(Mst1,2)*pow(Mst2,2)*
                    (586 + 36*B4 + 30*DN - 495*lmMsq + 135*pow(lmMsq,2) + 
                      438*lmMst1 + 270*lmMsq*lmMst1 - 
                      270*pow(lmMsq,2)*lmMst1 - 774*pow(lmMst1,2) + 
                      270*lmMsq*pow(lmMst1,2) - 65*pow(lmMst1,3) + 
                      687*lmMst2 - 540*lmMsq*lmMst2 + 
                      270*pow(lmMsq,2)*lmMst2 + 258*lmMst1*lmMst2 - 
                      237*pow(lmMst1,2)*lmMst2 + 1116*pow(lmMst2,2) - 
                      270*lmMsq*pow(lmMst2,2) - 
                      147*lmMst1*pow(lmMst2,2) + 449*pow(lmMst2,3) + 
                      2340*z2 - 540*lmMsq*z2 - 834*lmMst1*z2 + 
                      1890*lmMst2*z2 - 24*pow(z2,2) + 630*z3 + 
                      828*lmMst1*z3 - 828*lmMst2*z3 - 1590*z4))))/
            (3888.*Mgl*pow(Msq,4)*pow(Mst2,4)*pow(Sbeta,2)) - 
           (242*z4)/9. + (242*z4)/(9.*pow(Sbeta,2)) + 
           (pow(Mst1,2)*(-1 + pow(Sbeta,2))*
              (2215078222*pow(Msq,4)*pow(Mst2,2) - 
                703836000*B4*pow(Msq,4)*pow(Mst2,2) + 
                18522000*DN*pow(Msq,4)*pow(Mst2,2) + 
                972405000*lmMsq*pow(Msq,4)*pow(Mst2,2) - 
                416745000*pow(lmMsq,2)*pow(Msq,4)*pow(Mst2,2) + 
                24696000*pow(lmMst1,3)*pow(Msq,4)*pow(Mst2,2) - 
                5359032000*pow(lmMst2,3)*pow(Msq,4)*pow(Mst2,2) - 
                516146400*pow(Msq,2)*pow(Mst2,4) - 
                129654000*lmMsq*pow(Msq,2)*pow(Mst2,4) + 
                145858305*pow(Mst2,6) - 82586700*lmMsq*pow(Mst2,6) - 
                2646000*pow(lmMsq,2)*pow(Mst2,6) - 
                926100*pow(lmMst1,2)*pow(Msq,2)*pow(Mst2,2)*
                 ((149 + 1180*lmMst2)*pow(Msq,2) - 210*pow(Mst2,2)) - 
                186592000*pow(Msq,4)*pow(Mst2,2)*OepS2 + 
                5445468000*pow(Msq,4)*pow(Mst2,2)*S2 + 
                555660000*pow(Msq,6)*shiftst1 - 
                1111320000*lmMsq*pow(Msq,6)*shiftst1 - 
                555660000*pow(Msq,6)*shiftst2 + 
                1111320000*lmMsq*pow(Msq,6)*shiftst2 + 
                132300*pow(lmMst2,2)*pow(Mst2,2)*
                 (2030*pow(Msq,2)*pow(Mst2,2) + 540*pow(Mst2,4) + 
                   21*pow(Msq,4)*(-5903 + 800*lmMsq - 80*shiftst3)) + 
                55566000*pow(Msq,4)*pow(Mst2,2)*shiftst3 + 
                279888000*pow(Msq,4)*pow(Mst2,2)*T1ep + 
                320019000*pow(Msq,4)*pow(Mst2,2)*z2 + 
                1111320000*lmMsq*pow(Msq,4)*pow(Mst2,2)*z2 - 
                277830000*pow(Msq,2)*pow(Mst2,4)*z2 - 
                1111320000*pow(Msq,6)*shiftst1*z2 + 
                1111320000*pow(Msq,6)*shiftst2*z2 - 
                111132000*pow(Msq,4)*pow(Mst2,2)*shiftst3*z2 + 
                876708000*pow(Msq,4)*pow(Mst2,2)*pow(z2,2) + 
                61740*lmMst1*(10*(-143 + 120*lmMsq - 750*lmMst2)*
                    pow(Msq,2)*pow(Mst2,4) + 
                   40*(-47 + 30*lmMsq - 30*lmMst2)*pow(Mst2,6) + 
                   9000*pow(Msq,6)*(-1 + 2*shiftst1 - shiftst2)*
                    (-1 + 2*lmMsq + 2*z2) + 
                   pow(Msq,4)*pow(Mst2,2)*
                    (302707 + 18000*pow(lmMsq,2) + 
                      104100*pow(lmMst2,2) - 
                      3000*lmMsq*(19 + 12*lmMst2) + 61200*S2 - 
                      1800*shiftst3 + 30*lmMst2*(8089 + 120*shiftst3) + 
                      36600*z2 + 3600*shiftst3*z2 - 37800*z3)) - 
                1260*lmMst2*(490*(-353 + 120*lmMsq)*pow(Msq,2)*
                    pow(Mst2,4) + 
                   15*(-10511 + 3640*lmMsq)*pow(Mst2,6) + 
                   441000*pow(Msq,6)*(-1 + 2*shiftst1 - shiftst2)*
                    (-1 + 2*lmMsq + 2*z2) + 
                   49*pow(Msq,4)*pow(Mst2,2)*
                    (372457 - 70500*lmMsq + 18000*pow(lmMsq,2) + 
                      61200*S2 + 55800*z2 + 3600*shiftst3*z2 - 37800*z3)) - 
                18075414000*pow(Msq,4)*pow(Mst2,2)*z3 - 
                26754000*pow(Msq,4)*pow(Mst2,2)*z4))/
            (8.3349e7*pow(Msq,4)*pow(Mst2,4)*pow(Sbeta,2)) + 
           (pow(Mst1,4)*(-1 + pow(Sbeta,2))*
              (180*pow(Mst2,4)*
                 (-41220947 + 176400*pow(lmMsq,2) + 
                   11951100*pow(lmMst1,2) + 
                   420*lmMsq*(12479 + 4830*lmMst1 - 5670*lmMst2) + 
                   1081710*lmMst2 + 14156100*pow(lmMst2,2) - 
                   210*lmMst1*(30109 + 123480*lmMst2) - 15435000*z2) + 
                14817600*pow(Msq,2)*pow(Mst2,2)*
                 (1525 + 240*pow(lmMst1,2) + 
                   30*lmMsq*(-25 + 44*lmMst1 - 44*lmMst2) + 1928*lmMst2 + 
                   1560*pow(lmMst2,2) - 2*lmMst1*(589 + 900*lmMst2) + 
                   600*z2) + pow(Msq,4)*
                 (531403689547 - 16892064000*B4 + 444528000*DN - 
                   25004700000*lmMsq + 852909489180*lmMst1 - 
                   134469720000*lmMsq*lmMst1 + 
                   26671680000*pow(lmMsq,2)*lmMst1 - 
                   132506123400*pow(lmMst1,2) + 
                   26671680000*lmMsq*pow(lmMst1,2) + 
                   5927040000*pow(lmMst1,3) - 823570641180*lmMst2 + 
                   134469720000*lmMsq*lmMst2 - 
                   26671680000*pow(lmMsq,2)*lmMst2 + 
                   733544758800*lmMst1*lmMst2 - 
                   106686720000*lmMsq*lmMst1*lmMst2 - 
                   198704016000*pow(lmMst1,2)*lmMst2 - 
                   597482411400*pow(lmMst2,2) + 
                   80015040000*lmMsq*pow(lmMst2,2) + 
                   483201936000*lmMst1*pow(lmMst2,2) - 
                   290424960000*pow(lmMst2,3) - 8122240000*OepS2 + 
                   306576144000*S2 + 164475360000*lmMst1*S2 - 
                   164475360000*lmMst2*S2 + 1333584000*shiftst3 - 
                   4000752000*lmMst1*shiftst3 + 
                   1333584000*lmMst2*shiftst3 + 
                   8001504000*lmMst1*lmMst2*shiftst3 - 
                   8001504000*pow(lmMst2,2)*shiftst3 + 12183360000*T1ep + 
                   142720242000*z2 + 26671680000*lmMsq*z2 + 
                   192925152000*lmMst1*z2 - 221374944000*lmMst2*z2 - 
                   2667168000*shiftst3*z2 + 8001504000*lmMst1*shiftst3*z2 - 
                   8001504000*lmMst2*shiftst3*z2 + 
                   25140528000*pow(z2,2) - 1113065184000*z3 - 
                   56010528000*lmMst1*z3 + 56010528000*lmMst2*z3 + 
                   2090928000*z4)))/
            (2.000376e9*pow(Msq,4)*pow(Mst2,4)*pow(Sbeta,2)) + 
           (pow(Dmglst1,2)*(-1 + pow(Sbeta,2))*
              (1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                 (-3*pow(Mst2,2)*
                    (108 - 133*lmMst1 - 9*pow(lmMst1,2) + 
                      2*lmMsq*(32 + 9*lmMst1 - 9*lmMst2) + 69*lmMst2 + 
                      9*pow(lmMst2,2) + 18*z2) + 
                   2*pow(Mst1,2)*
                    (335 - 97*lmMst1 - 123*pow(lmMst1,2) + 
                      6*lmMsq*(-25 + 41*lmMst1 - 41*lmMst2) + 247*lmMst2 + 
                      123*pow(lmMst2,2) + 246*z2)) - 
                180*pow(Mst1,2)*pow(Mst2,4)*
                 (-54*pow(Mst2,2) + 
                   pow(Mst1,2)*
                    (3087 - 2306*lmMst1 - 300*pow(lmMst1,2) + 
                      12*lmMsq*(47 + 50*lmMst1 - 50*lmMst2) + 1742*lmMst2 + 
                      300*pow(lmMst2,2) + 600*z2)) + 
                pow(Msq,4)*(-72*pow(Mst2,4)*
                    (6457 + 1620*pow(lmMsq,2) - 982*lmMst1 + 
                      834*pow(lmMst1,2) - 60*lmMsq*(-67 + 54*lmMst1) - 
                      2670*lmMst2 + 1980*lmMst1*lmMst2 + 
                      162*pow(lmMst2,2) + 3564*z2 - 9198*z3) - 
                   864*pow(Mst1,2)*pow(Mst2,2)*
                    (479 + 36*B4 + 30*DN - 975*lmMsq + 135*pow(lmMsq,2) + 
                      1018*lmMst1 + 270*lmMsq*lmMst1 - 
                      270*pow(lmMsq,2)*lmMst1 - 646*pow(lmMst1,2) + 
                      270*lmMsq*pow(lmMst1,2) - 65*pow(lmMst1,3) + 
                      811*lmMst2 - 540*lmMsq*lmMst2 + 
                      270*pow(lmMsq,2)*lmMst2 + 258*lmMst1*lmMst2 - 
                      237*pow(lmMst1,2)*lmMst2 + 1116*pow(lmMst2,2) - 
                      270*lmMsq*pow(lmMst2,2) - 
                      147*lmMst1*pow(lmMst2,2) + 449*pow(lmMst2,3) + 
                      2340*z2 - 540*lmMsq*z2 - 834*lmMst1*z2 + 
                      1890*lmMst2*z2 - 24*pow(z2,2) + 588*z3 + 
                      828*lmMst1*z3 - 828*lmMst2*z3 - 1590*z4) + 
                   pow(Mst1,4)*
                    (-130639 + 24192*B4 + 1728*DN + 984960*lmMsq + 
                      3147108*lmMst1 - 2177280*lmMsq*lmMst1 + 
                      233280*pow(lmMsq,2)*lmMst1 + 
                      1561608*pow(lmMst1,2) - 
                      233280*lmMsq*pow(lmMst1,2) + 
                      240480*pow(lmMst1,3) - 4170084*lmMst2 + 
                      2177280*lmMsq*lmMst2 - 233280*pow(lmMsq,2)*lmMst2 + 
                      1875888*lmMst1*lmMst2 - 
                      1011744*pow(lmMst1,2)*lmMst2 - 
                      3299256*pow(lmMst2,2) + 
                      233280*lmMsq*pow(lmMst2,2) + 
                      2007072*lmMst1*pow(lmMst2,2) - 
                      1235808*pow(lmMst2,3) + 418032*z2 + 
                      466560*lmMsq*z2 + 1577664*lmMst1*z2 - 
                      2490048*lmMst2*z2 + 20736*pow(z2,2) - 11216448*z3 - 
                      549504*lmMst1*z3 + 549504*lmMst2*z3 + 959040*z4))))/
            (7776.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)*pow(Sbeta,2)))))
