((2*pow(Mst2,4) - lmMst1*(2*pow(Mst1,4) + 
          2*pow(Mst1,2)*pow(Mst2,2) + pow(Mst2,4)) + 
       lmMst2*(2*pow(Mst1,4) + 2*pow(Mst1,2)*pow(Mst2,2) + 
          pow(Mst2,4)))*pow(Mt,2)*pow(MuSUSY,2)*oneLoopFlag*
     pow(s2t,2))/(8.*pow(Mst2,4)) - 
  (Al4p*pow(Mt,2)*pow(MuSUSY,2)*s2t*twoLoopFlag*
     (-(pow(Mgl,2)*((1 + 20*pow(lmMst1,2) + 46*lmMst2 + 
               44*pow(lmMst2,2) - 2*lmMst1*(23 + 32*lmMst2))*
             pow(Mst1,4)*s2t + 
            4*(2 + pow(lmMst1,2) + 11*lmMst2 + 7*pow(lmMst2,2) - 
               2*lmMst1*(5 + 4*lmMst2))*pow(Mst1,2)*pow(Mst2,2)*s2t - 
            8*pow(Mst1,3)*Mt*
             (-6 + 5*pow(lmMst1,2) - 4*lmMst1*(-3 + lmMst2) - 
               16*lmMst2 - pow(lmMst2,2) - 2*z2) - 
            8*Mst1*pow(Mst2,2)*Mt*
             (-8 + 2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
               pow(lmMst2,2) - 2*z2) - 
            4*pow(Mst2,4)*s2t*
             (-7 - 7*lmMst2 - 2*pow(lmMst2,2) + 2*lmMst1*(1 + lmMst2) + 
               z2))) + 8*Dmglst1*Mgl*
        (-((-1 + lmMst1)*pow(Mst2,4)*s2t) + 
          pow(Mst1,4)*s2t*(2 + 3*lmMst1 + pow(lmMst1,2) - 3*lmMst2 - 
             pow(lmMst2,2) - 2*z2) + 
          pow(Mst1,2)*pow(Mst2,2)*s2t*
           (pow(lmMst1,2) - lmMst2 - pow(lmMst2,2) - 2*z2) + 
          pow(Mst1,3)*Mt*(-10 + 9*pow(lmMst1,2) + 
             lmMst1*(8 - 12*lmMst2) - 12*lmMst2 + 3*pow(lmMst2,2) + 6*z2
) + Mst1*pow(Mst2,2)*Mt*(2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
             pow(lmMst2,2) - 2*(6 + z2))) + 
       4*pow(Dmglst1,2)*((4 - 3*lmMst1)*pow(Mst2,4)*s2t + 
          pow(Mst1,2)*pow(Mst2,2)*s2t*
           (-4 + 3*pow(lmMst1,2) - 3*lmMst2 - 3*pow(lmMst2,2) - 6*z2) + 
          3*pow(Mst1,4)*s2t*(5*lmMst1 + pow(lmMst1,2) - 5*lmMst2 - 
             pow(lmMst2,2) - 2*z2) + 
          2*pow(Mst1,3)*Mt*(-2 + 15*pow(lmMst1,2) + 2*lmMst2 + 
             9*pow(lmMst2,2) - 6*lmMst1*(1 + 4*lmMst2) + 18*z2) + 
          2*Mst1*pow(Mst2,2)*Mt*
           (2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - pow(lmMst2,2) - 
             2*(8 + z2)))))/(6.*pow(Mgl,2)*pow(Mst2,4)) + 
  pow(Al4p,2)*pow(Mt,2)*pow(MuSUSY,2)*threeLoopFlag*
   ((-8*pow(Mst1,2)*pow(Mt,2)*
        (pow(Dmglst1,2)*(-9893 + 54*B4 + 27*DN + 50*lmMst1 - 
             138*pow(lmMst1,2) + 234*pow(lmMst1,3) - 4538*lmMst2 + 
             300*lmMst1*lmMst2 - 54*pow(lmMst1,2)*lmMst2 - 
             1026*pow(lmMst2,2) - 162*lmMst1*pow(lmMst2,2) - 
             18*pow(lmMst2,3) - 696*lmMt + 840*lmMst1*lmMt - 
             216*pow(lmMst1,2)*lmMt - 840*lmMst2*lmMt + 
             432*lmMst1*lmMst2*lmMt - 216*pow(lmMst2,2)*lmMt - 2970*z2 - 
             864*lmMst2*z2 + 3960*z3 + 162*lmMst1*z3 - 162*lmMst2*z3 - 
             405*z4) + 3*pow(Mgl,2)*
           (-417 + 6*B4 + 3*DN + 162*lmMst1 + 26*pow(lmMst1,3) - 
             522*lmMst2 + 48*lmMst1*lmMst2 - 6*pow(lmMst1,2)*lmMst2 - 
             144*pow(lmMst2,2) - 18*lmMst1*pow(lmMst2,2) - 
             2*pow(lmMst2,3) - 24*lmMt + 48*lmMst1*lmMt - 
             24*pow(lmMst1,2)*lmMt - 48*lmMst2*lmMt + 
             48*lmMst1*lmMst2*lmMt - 24*pow(lmMst2,2)*lmMt - 330*z2 - 
             96*lmMst2*z2 - 138*z3 + 18*lmMst1*z3 - 18*lmMst2*z3 - 45*z4) + 
          6*Dmglst1*Mgl*(-735 + 6*B4 + 3*DN + 78*lmMst1 - 
             6*pow(lmMst1,2) + 26*pow(lmMst1,3) - 510*lmMst2 + 
             36*lmMst1*lmMst2 - 6*pow(lmMst1,2)*lmMst2 - 
             126*pow(lmMst2,2) - 18*lmMst1*pow(lmMst2,2) - 
             2*pow(lmMst2,3) - 48*lmMt + 72*lmMst1*lmMt - 
             24*pow(lmMst1,2)*lmMt - 72*lmMst2*lmMt + 
             48*lmMst1*lmMst2*lmMt - 24*pow(lmMst2,2)*lmMt - 330*z2 - 
             96*lmMst2*z2 + 117*z3 + 18*lmMst1*z3 - 18*lmMst2*z3 - 45*z4)))/
      (81.*pow(Mgl,2)*pow(Mst2,4)) - 
     (Mst1*Mt*s2t*(3*pow(Dmglst1,2)*
           (240*pow(Msq,2)*(-3*pow(Mst2,4) + 
                pow(Mst1,4)*
                 (203 - 378*pow(lmMst1,2) + 
                   72*lmMsq*(-2 + 3*lmMst1 - 3*lmMst2) + 366*lmMst2 - 
                   162*pow(lmMst2,2) + 6*lmMst1*(-37 + 90*lmMst2) - 
                   324*z2) + pow(Mst1,2)*pow(Mst2,2)*
                 (557 - 126*lmMst1 - 36*pow(lmMst1,2) + 
                   72*lmMsq*(-2 + lmMst1 - lmMst2) + 270*lmMst2 + 
                   36*pow(lmMst2,2) + 72*z2)) + 
             5*pow(Mst2,2)*((-467 + 12*lmMsq - 12*lmMst2)*
                 pow(Mst1,2)*pow(Mst2,2) + 
                (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                18*pow(Mst1,4)*
                 (928 - 145*lmMst1 - 90*pow(lmMst1,2) + 
                   180*lmMsq*(-2 + lmMst1 - lmMst2) + 505*lmMst2 + 
                   90*pow(lmMst2,2) + 180*z2)) + 
             2*pow(Msq,4)*(pow(Mst1,2)*
                 (59579 + 20088*B4 - 324*DN - 39240*lmMsq - 
                   2160*pow(lmMsq,2) - 1344*lmMst1 + 
                   46440*lmMsq*lmMst1 + 3240*pow(lmMsq,2)*lmMst1 - 
                   13914*pow(lmMst1,2) - 29160*lmMsq*pow(lmMst1,2) + 
                   33084*pow(lmMst1,3) + 33840*lmMst2 - 
                   42120*lmMsq*lmMst2 - 3240*pow(lmMsq,2)*lmMst2 - 
                   39924*lmMst1*lmMst2 + 51840*lmMsq*lmMst1*lmMst2 - 
                   23796*pow(lmMst1,2)*lmMst2 + 31950*pow(lmMst2,2) - 
                   22680*lmMsq*pow(lmMst2,2) - 
                   25740*lmMst1*pow(lmMst2,2) + 16452*pow(lmMst2,3) + 
                   110196*z2 - 45360*lmMsq*z2 - 15624*lmMst1*z2 + 
                   84744*lmMst2*z2 - 20736*pow(z2,2) - 16308*z3 + 
                   99144*lmMst1*z3 - 99144*lmMst2*z3 - 62532*z4) + 
                3*pow(Mst2,2)*
                 (413 + 408*B4 + 12*DN + 8520*lmMsq - 720*pow(lmMsq,2) - 
                   3146*lmMst1 - 1080*lmMsq*lmMst1 + 
                   360*pow(lmMsq,2)*lmMst1 - 918*pow(lmMst1,2) - 
                   360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                   15206*lmMst2 + 2520*lmMsq*lmMst2 - 
                   360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                   360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                   360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                   584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                   768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) - 
                   6708*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))) + 
          3*Dmglst1*Mgl*(720*pow(Msq,2)*
              (-pow(Mst2,4) + 
                2*pow(Mst1,4)*
                 (29 - 24*pow(lmMst1,2) + 
                   6*lmMsq*(-2 + 3*lmMst1 - 3*lmMst2) + 48*lmMst2 - 
                   6*pow(lmMst2,2) + 6*lmMst1*(-6 + 5*lmMst2) - 12*z2) 
+ 2*pow(Mst1,2)*pow(Mst2,2)*
                 (41 - 10*lmMst1 - 3*pow(lmMst1,2) + 
                   6*lmMsq*(-2 + lmMst1 - lmMst2) + 22*lmMst2 + 
                   3*pow(lmMst2,2) + 6*z2)) + 
             5*pow(Mst2,2)*((-251 + 12*lmMsq - 12*lmMst2)*
                 pow(Mst1,2)*pow(Mst2,2) + 
                (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                6*pow(Mst1,4)*
                 (818 - 117*lmMst1 - 90*pow(lmMst1,2) + 
                   180*lmMsq*(-2 + lmMst1 - lmMst2) + 477*lmMst2 + 
                   90*pow(lmMst2,2) + 180*z2)) + 
             2*pow(Msq,4)*(pow(Mst1,2)*
                 (-13969 + 11880*B4 - 108*DN + 4320*lmMsq - 
                   2160*pow(lmMsq,2) + 16728*lmMst1 + 
                   3240*lmMsq*lmMst1 + 3240*pow(lmMsq,2)*lmMst1 + 
                   21978*pow(lmMst1,2) - 16200*lmMsq*pow(lmMst1,2) + 
                   16848*pow(lmMst1,3) - 49128*lmMst2 + 
                   1080*lmMsq*lmMst2 - 3240*pow(lmMsq,2)*lmMst2 - 
                   26460*lmMst1*lmMst2 + 25920*lmMsq*lmMst1*lmMst2 - 
                   9648*pow(lmMst1,2)*lmMst2 - 10494*pow(lmMst2,2) - 
                   9720*lmMsq*pow(lmMst2,2) - 
                   12240*lmMst1*pow(lmMst2,2) + 5040*pow(lmMst2,3) + 
                   24732*z2 - 19440*lmMsq*z2 - 3312*lmMst1*z2 + 
                   30960*lmMst2*z2 - 12096*pow(z2,2) + 33264*z3 + 
                   48600*lmMst1*z3 - 48600*lmMst2*z3 - 18252*z4) + 
                3*pow(Mst2,2)*
                 (-11337 + 408*B4 + 12*DN + 6480*lmMsq - 
                   720*pow(lmMsq,2) - 2190*lmMst1 - 1080*lmMsq*lmMst1 + 
                   360*pow(lmMsq,2)*lmMst1 + 234*pow(lmMst1,2) - 
                   360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                   13986*lmMst2 + 2520*lmMsq*lmMst2 - 
                   360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                   360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                   360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                   584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                   768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) + 
                   1392*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4))) + 
          pow(Mgl,2)*(720*pow(Msq,2)*
              (4*(14 - 21*lmMst1 - 9*pow(lmMst1,2) + 
                   lmMsq*(-6 + 9*lmMst1 - 9*lmMst2) + 27*lmMst2 + 
                   9*lmMst1*lmMst2)*pow(Mst1,4) - 3*pow(Mst2,4) + 
                2*pow(Mst1,2)*pow(Mst2,2)*
                 (34 - 8*lmMst1 - 3*pow(lmMst1,2) + 
                   6*lmMsq*(-2 + lmMst1 - lmMst2) + 20*lmMst2 + 
                   3*pow(lmMst2,2) + 6*z2)) + 
             15*pow(Mst2,2)*((-107 + 12*lmMsq - 12*lmMst2)*
                 pow(Mst1,2)*pow(Mst2,2) + 
                (11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                6*pow(Mst1,4)*
                 (134 - 9*lmMst1 - 18*pow(lmMst1,2) + 
                   36*lmMsq*(-2 + lmMst1 - lmMst2) + 81*lmMst2 + 
                   18*pow(lmMst2,2) + 36*z2)) + 
             2*pow(Msq,4)*(9*pow(Mst2,2)*
                 (-13317 + 408*B4 + 12*DN + 4320*lmMsq - 
                   720*pow(lmMsq,2) + 474*lmMst1 - 1080*lmMsq*lmMst1 + 
                   360*pow(lmMsq,2)*lmMst1 + 1002*pow(lmMst1,2) - 
                   360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                   12810*lmMst2 + 2520*lmMsq*lmMst2 - 
                   360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                   360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                   360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                   584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                   768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) + 
                   3192*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4) + 
                pow(Mst1,2)*(-107299 + 19224*B4 + 108*DN + 32400*lmMsq - 
                   6480*pow(lmMsq,2) + 146472*lmMst1 - 
                   42120*lmMsq*lmMst1 + 9720*pow(lmMsq,2)*lmMst1 + 
                   78822*pow(lmMst1,2) - 22680*lmMsq*pow(lmMst1,2) + 
                   18072*pow(lmMst1,3) - 250584*lmMst2 + 
                   55080*lmMsq*lmMst2 - 9720*pow(lmMsq,2)*lmMst2 - 
                   8388*lmMst1*lmMst2 + 25920*lmMsq*lmMst1*lmMst2 - 
                   648*pow(lmMst1,2)*lmMst2 - 101538*pow(lmMst2,2) - 
                   3240*lmMsq*pow(lmMst2,2) - 
                   9720*lmMst1*pow(lmMst2,2) - 7704*pow(lmMst2,3) - 
                   86652*z2 - 6480*lmMsq*z2 + 14688*lmMst1*z2 - 
                   14688*lmMst2*z2 - 19008*pow(z2,2) + 124200*z3 + 
                   44712*lmMst1*z3 - 44712*lmMst2*z3 + 33804*z4)))))/
      (486.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)) + 
     pow(s2t,2)*(83.61265432098766 + 4*B4 - (4*DN)/9. - (185*lmMsq)/9. + 
        (25*pow(lmMsq,2))/3. - (3781*lmMst1)/108. + (25*lmMsq*lmMst1)/9. - 
        (5*pow(lmMsq,2)*lmMst1)/3. + (229*pow(lmMst1,2))/36. - 
        (5*lmMsq*pow(lmMst1,2))/3. + (11*pow(lmMst1,3))/18. + 
        (14065*lmMst2)/108. - (175*lmMsq*lmMst2)/9. + 
        (5*pow(lmMsq,2)*lmMst2)/3. - (583*lmMst1*lmMst2)/18. + 
        (20*lmMsq*lmMst1*lmMst2)/3. - (pow(lmMst1,2)*lmMst2)/6. + 
        (731*pow(lmMst2,2))/12. - 5*lmMsq*pow(lmMst2,2) - 
        (221*lmMst1*pow(lmMst2,2))/18. + (71*pow(lmMst2,3))/6. - 
        ((939 + 30*lmMsq*(-12 + 5*lmMst1 - 5*lmMst2) + 760*lmMst2 + 
             150*pow(lmMst2,2) - 50*lmMst1*(8 + 3*lmMst2))*pow(Mst2,2))/
         (135.*pow(Msq,2)) - ((7399303 + 176400*pow(lmMsq,2) + 
             420*lmMsq*(-9571 + 2940*lmMst1 - 3780*lmMst2) + 
             6571740*lmMst2 + 1411200*pow(lmMst2,2) - 
             82320*lmMst1*(31 + 15*lmMst2))*pow(Mst2,4))/
         (1.11132e7*pow(Msq,4)) + (8*OepS2)/27. + 33*S2 - 6*lmMst1*S2 + 
        6*lmMst2*S2 - (2*shiftst3)/3. + (2*lmMst1*shiftst3)/3. + 
        (2*lmMst2*shiftst3)/3. - (4*lmMst1*lmMst2*shiftst3)/3. + 
        (4*pow(lmMst2,2)*shiftst3)/3. - (4*T1ep)/9. - (113*z2)/3. + 
        (10*lmMsq*z2)/3. + (37*lmMst1*z2)/9. - (149*lmMst2*z2)/9. + 
        (4*shiftst3*z2)/3. - (4*lmMst1*shiftst3*z2)/3. + 
        (4*lmMst2*shiftst3*z2)/3. - (35*pow(z2,2))/9. - 
        (10*pow(Msq,2)*(1 + 2*lmMst1*(-1 + shiftst1) - 
             2*lmMst2*(-1 + shiftst1) - 2*shiftst1 + shiftst2)*
           (-1 + 2*lmMsq + 2*z2))/(3.*pow(Mst2,2)) + 
        (10*pow(Msq,2)*(-1 + shiftst1)*(-1 + 2*lmMsq + 2*z2) + 
           pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2))/
         (3.*pow(Mst1,2)) + (328*z3)/9. + 
        (Dmglst1*(-1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
              (-(pow(Mst2,2)*
                   (82 - 93*lmMst1 - 9*pow(lmMst1,2) + 
                     6*lmMsq*(4 + 3*lmMst1 - 3*lmMst2) + 69*lmMst2 + 
                     9*pow(lmMst2,2) + 18*z2)) + 
                2*pow(Mst1,2)*
                 (55 + lmMst1 - 21*pow(lmMst1,2) + 
                   6*lmMsq*(-5 + 7*lmMst1 - 7*lmMst2) + 29*lmMst2 + 
                   21*pow(lmMst2,2) + 42*z2)) + 
             180*pow(Mst1,2)*pow(Mst2,4)*
              (-18*pow(Mst2,2) + 
                pow(Mst1,2)*(485 - 346*lmMst1 - 60*pow(lmMst1,2) + 
                   12*lmMsq*(1 + 10*lmMst1 - 10*lmMst2) + 334*lmMst2 + 
                   60*pow(lmMst2,2) + 120*z2)) + 
             pow(Msq,4)*(216*pow(Mst2,4)*
                 (7 + 180*pow(lmMsq,2) - 2*lmMst1 + 
                   178*pow(lmMst1,2) - 60*lmMsq*(-5 + 6*lmMst1) - 
                   226*lmMst2 + 220*lmMst1*lmMst2 + 18*pow(lmMst2,2) + 
                   396*z2 - 390*z3) + 
                pow(Mst1,4)*(-437365 + 10368*B4 + 8640*DN - 
                   988500*lmMst1 + 466560*lmMsq*lmMst1 - 
                   77760*pow(lmMsq,2)*lmMst1 - 503784*pow(lmMst1,2) + 
                   77760*lmMsq*pow(lmMst1,2) - 16416*pow(lmMst1,3) + 
                   822612*lmMst2 - 466560*lmMsq*lmMst2 + 
                   77760*pow(lmMsq,2)*lmMst2 - 207216*lmMst1*lmMst2 + 
                   146016*pow(lmMst1,2)*lmMst2 + 
                   683352*pow(lmMst2,2) - 77760*lmMsq*pow(lmMst2,2) - 
                   477792*lmMst1*pow(lmMst2,2) + 
                   348192*pow(lmMst2,3) + 232272*z2 - 155520*lmMsq*z2 - 
                   530496*lmMst1*z2 + 834624*lmMst2*z2 - 
                   6912*pow(z2,2) + 2640384*z3 + 238464*lmMst1*z3 - 
                   238464*lmMst2*z3 - 457920*z4) + 
                288*pow(Mst1,2)*pow(Mst2,2)*
                 (586 + 36*B4 + 30*DN - 495*lmMsq + 135*pow(lmMsq,2) + 
                   438*lmMst1 + 270*lmMsq*lmMst1 - 
                   270*pow(lmMsq,2)*lmMst1 - 774*pow(lmMst1,2) + 
                   270*lmMsq*pow(lmMst1,2) - 65*pow(lmMst1,3) + 
                   687*lmMst2 - 540*lmMsq*lmMst2 + 
                   270*pow(lmMsq,2)*lmMst2 + 258*lmMst1*lmMst2 - 
                   237*pow(lmMst1,2)*lmMst2 + 1116*pow(lmMst2,2) - 
                   270*lmMsq*pow(lmMst2,2) - 147*lmMst1*pow(lmMst2,2) + 
                   449*pow(lmMst2,3) + 2340*z2 - 540*lmMsq*z2 - 
                   834*lmMst1*z2 + 1890*lmMst2*z2 - 24*pow(z2,2) + 
                   630*z3 + 828*lmMst1*z3 - 828*lmMst2*z3 - 1590*z4))))/
         (3888.*Mgl*pow(Msq,4)*pow(Mst2,4)) + 
        pow(Mst1,2)*(((-1.7499706655148832 + (2*pow(lmMsq,2))/63. + 
                lmMsq*(0.990854119425548 - (8*lmMst1)/9. + 
                   (52*lmMst2)/63.) - (10511*lmMst2)/4410. - 
                (6*pow(lmMst2,2))/7. + (4*lmMst1*(47 + 30*lmMst2))/135.)*
              pow(Mst2,2))/pow(Msq,4) - 
           (20*pow(Msq,2)*(-shiftst1 + 
                lmMst1*(-1 + 2*shiftst1 - shiftst2) + shiftst2 + 
                lmMst2*(1 - 2*shiftst1 + shiftst2))*(-1 + 2*lmMsq + 2*z2))/
            (3.*pow(Mst2,4)) + 
           (836 - 315*pow(lmMst1,2) - 
              30*lmMsq*(-7 + 4*lmMst1 - 4*lmMst2) - 353*lmMst2 - 
              435*pow(lmMst2,2) + lmMst1*(143 + 750*lmMst2) + 450*z2)/
            (135.*pow(Msq,2)) + 
           (-26.575942386831276 + (76*B4)/9. - (2*DN)/9. - (35*lmMsq)/3. + 
              5*pow(lmMsq,2) - (302707*lmMst1)/1350. + 
              (380*lmMsq*lmMst1)/9. - (40*pow(lmMsq,2)*lmMst1)/3. + 
              (149*pow(lmMst1,2))/90. - (8*pow(lmMst1,3))/27. + 
              (372457*lmMst2)/1350. - (470*lmMsq*lmMst2)/9. + 
              (40*pow(lmMsq,2)*lmMst2)/3. - (8089*lmMst1*lmMst2)/45. + 
              (80*lmMsq*lmMst1*lmMst2)/3. + 
              (118*pow(lmMst1,2)*lmMst2)/9. + 
              (5903*pow(lmMst2,2))/30. - (80*lmMsq*pow(lmMst2,2))/3. - 
              (694*lmMst1*pow(lmMst2,2))/9. + 
              (1736*pow(lmMst2,3))/27. + (544*OepS2)/243. - (196*S2)/3. - 
              (136*lmMst1*S2)/3. + (136*lmMst2*S2)/3. - (2*shiftst3)/3. + 
              (4*lmMst1*shiftst3)/3. - (8*lmMst1*lmMst2*shiftst3)/3. + 
              (8*pow(lmMst2,2)*shiftst3)/3. - (272*T1ep)/81. - 
              (311*z2)/81. - (40*lmMsq*z2)/3. - (244*lmMst1*z2)/9. + 
              (124*lmMst2*z2)/3. + (4*shiftst3*z2)/3. - 
              (8*lmMst1*shiftst3*z2)/3. + (8*lmMst2*shiftst3*z2)/3. - 
              (284*pow(z2,2))/27. + (17566*z3)/81. + 28*lmMst1*z3 - 
              28*lmMst2*z3 + (26*z4)/81.)/pow(Mst2,2)) + (242*z4)/9. + 
        pow(Mst1,4)*((3.709187902674297 - pow(lmMsq,2)/63. - 
              (271*pow(lmMst1,2))/252. - 
              (lmMsq*(12479 + 4830*lmMst1 - 5670*lmMst2))/26460. - 
              (1717*lmMst2)/17640. - (107*pow(lmMst2,2))/84. + 
              lmMst1*(0.5689531368102797 + (7*lmMst2)/3.) + (25*z2)/18.)/
            pow(Msq,4) - (1525 + 240*pow(lmMst1,2) + 
              30*lmMsq*(-25 + 44*lmMst1 - 44*lmMst2) + 1928*lmMst2 + 
              1560*pow(lmMst2,2) - 2*lmMst1*(589 + 900*lmMst2) + 600*z2)/
            (135.*pow(Msq,2)*pow(Mst2,2)) - 
           (265.6519022158834 - (76*B4)/9. + (2*DN)/9. - (25*lmMsq)/2. + 
              (75212477*lmMst1)/176400. - (605*lmMsq*lmMst1)/9. + 
              (40*pow(lmMsq,2)*lmMst1)/3. - 
              (500779*pow(lmMst1,2))/7560. + 
              (40*lmMsq*pow(lmMst1,2))/3. + (80*pow(lmMst1,3))/27. - 
              (72625277*lmMst2)/176400. + (605*lmMsq*lmMst2)/9. - 
              (40*pow(lmMsq,2)*lmMst2)/3. + 
              (1386139*lmMst1*lmMst2)/3780. - 
              (160*lmMsq*lmMst1*lmMst2)/3. - 
              (298*pow(lmMst1,2)*lmMst2)/3. - 
              (2258059*pow(lmMst2,2))/7560. + 40*lmMsq*pow(lmMst2,2) + 
              (2174*lmMst1*pow(lmMst2,2))/9. - 
              (3920*pow(lmMst2,3))/27. - (2960*OepS2)/729. + 
              (4138*S2)/27. + (740*lmMst1*S2)/9. - (740*lmMst2*S2)/9. + 
              (2*shiftst3)/3. - 2*lmMst1*shiftst3 + 
              (2*lmMst2*shiftst3)/3. + 4*lmMst1*lmMst2*shiftst3 - 
              4*pow(lmMst2,2)*shiftst3 + (1480*T1ep)/243. + 
              (69349*z2)/972. + (40*lmMsq*z2)/3. + (868*lmMst1*z2)/9. - 
              (332*lmMst2*z2)/3. - (4*shiftst3*z2)/3. + 
              4*lmMst1*shiftst3*z2 - 4*lmMst2*shiftst3*z2 + 
              (1018*pow(z2,2))/81. - (135212*z3)/243. - 28*lmMst1*z3 + 
              28*lmMst2*z3 + (254*z4)/243.)/pow(Mst2,4)) - 
        (pow(Dmglst1,2)*(1440*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
              (-3*pow(Mst2,2)*
                 (108 - 133*lmMst1 - 9*pow(lmMst1,2) + 
                   2*lmMsq*(32 + 9*lmMst1 - 9*lmMst2) + 69*lmMst2 + 
                   9*pow(lmMst2,2) + 18*z2) + 
                2*pow(Mst1,2)*
                 (335 - 97*lmMst1 - 123*pow(lmMst1,2) + 
                   6*lmMsq*(-25 + 41*lmMst1 - 41*lmMst2) + 247*lmMst2 + 
                   123*pow(lmMst2,2) + 246*z2)) - 
             180*pow(Mst1,2)*pow(Mst2,4)*
              (-54*pow(Mst2,2) + 
                pow(Mst1,2)*(3087 - 2306*lmMst1 - 300*pow(lmMst1,2) + 
                   12*lmMsq*(47 + 50*lmMst1 - 50*lmMst2) + 1742*lmMst2 + 
                   300*pow(lmMst2,2) + 600*z2)) + 
             pow(Msq,4)*(-72*pow(Mst2,4)*
                 (6457 + 1620*pow(lmMsq,2) - 982*lmMst1 + 
                   834*pow(lmMst1,2) - 60*lmMsq*(-67 + 54*lmMst1) - 
                   2670*lmMst2 + 1980*lmMst1*lmMst2 + 162*pow(lmMst2,2) + 
                   3564*z2 - 9198*z3) - 
                864*pow(Mst1,2)*pow(Mst2,2)*
                 (479 + 36*B4 + 30*DN - 975*lmMsq + 135*pow(lmMsq,2) + 
                   1018*lmMst1 + 270*lmMsq*lmMst1 - 
                   270*pow(lmMsq,2)*lmMst1 - 646*pow(lmMst1,2) + 
                   270*lmMsq*pow(lmMst1,2) - 65*pow(lmMst1,3) + 
                   811*lmMst2 - 540*lmMsq*lmMst2 + 
                   270*pow(lmMsq,2)*lmMst2 + 258*lmMst1*lmMst2 - 
                   237*pow(lmMst1,2)*lmMst2 + 1116*pow(lmMst2,2) - 
                   270*lmMsq*pow(lmMst2,2) - 147*lmMst1*pow(lmMst2,2) + 
                   449*pow(lmMst2,3) + 2340*z2 - 540*lmMsq*z2 - 
                   834*lmMst1*z2 + 1890*lmMst2*z2 - 24*pow(z2,2) + 
                   588*z3 + 828*lmMst1*z3 - 828*lmMst2*z3 - 1590*z4) + 
                pow(Mst1,4)*(-130639 + 24192*B4 + 1728*DN + 984960*lmMsq + 
                   3147108*lmMst1 - 2177280*lmMsq*lmMst1 + 
                   233280*pow(lmMsq,2)*lmMst1 + 1561608*pow(lmMst1,2) - 
                   233280*lmMsq*pow(lmMst1,2) + 240480*pow(lmMst1,3) - 
                   4170084*lmMst2 + 2177280*lmMsq*lmMst2 - 
                   233280*pow(lmMsq,2)*lmMst2 + 1875888*lmMst1*lmMst2 - 
                   1011744*pow(lmMst1,2)*lmMst2 - 
                   3299256*pow(lmMst2,2) + 233280*lmMsq*pow(lmMst2,2) + 
                   2007072*lmMst1*pow(lmMst2,2) - 
                   1235808*pow(lmMst2,3) + 418032*z2 + 466560*lmMsq*z2 + 
                   1577664*lmMst1*z2 - 2490048*lmMst2*z2 + 
                   20736*pow(z2,2) - 11216448*z3 - 549504*lmMst1*z3 + 
                   549504*lmMst2*z3 + 959040*z4))))/
         (7776.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4))))
