(Mt*MuSUSY*oneLoopFlag*s2t*(2*(-2 + lmMst1 - lmMst2)*Mt*MuSUSY*s2t + 
       4*(lmMst1 - lmMst2)*pow(Mt,2)*Tbeta + 
       (2 - lmMst1 + lmMst2)*pow(Mst2,2)*pow(s2t,2)*Tbeta))/(16.*Tbeta) + 
  (Al4p*Mt*MuSUSY*twoLoopFlag*((-4*Mst1*pow(Mt,3)*
          (18*Dmglst1*(5 + lmMst2 + 2*lmMt + lmMst2*lmMt - 
               lmMst1*(3 + lmMt))*Mgl*pow(Mst2,2) + 
            18*(2 + lmMst2 + lmMt + lmMst2*lmMt - lmMst1*(2 + lmMt))*
             pow(Mgl,2)*pow(Mst2,2) + 
            pow(Dmglst1,2)*((151 + 51*lmMt + 18*lmMst2*(1 + lmMt) - 
                  3*lmMst1*(23 + 6*lmMt))*pow(Mst2,2) + 
               pow(Mst1,2)*(61 - 54*pow(lmMst2,2) + 
                  3*lmMst1*(-5 + 18*lmMst2 - 18*lmMt) + 105*lmMt + 
                  18*lmMst2*(-5 + 3*lmMt) - 108*z2))))/pow(Mst2,4) - 
       9*pow(s2t,3)*(pow(Dmglst1,2)*
           ((4 - 3*lmMst1)*pow(Mst2,2) + 
             pow(Mst1,2)*(-8 + 3*lmMst1 + 3*pow(lmMst1,2) - 
                3*lmMst2 - 3*pow(lmMst2,2) - 6*z2)) + 
          2*Dmglst1*Mgl*(-((-1 + lmMst1)*pow(Mst2,2)) + 
             pow(Mst1,2)*(-1 + lmMst1 + pow(lmMst1,2) - lmMst2 - 
                pow(lmMst2,2) - 2*z2)) + 
          pow(Mgl,2)*pow(Mst2,2)*
           (-7 - 7*lmMst2 - 2*pow(lmMst2,2) + 2*lmMst1*(1 + lmMst2) + z2)
) + (6*pow(Mt,2)*s2t*(3*pow(Mgl,2)*pow(Mst2,2)*
             ((pow(lmMst1,2) + 2*lmMst1*(1 + lmMst2) - 
                  lmMst2*(4 + 3*lmMst2))*pow(Mst2,2)*Tbeta + 
               2*Mst1*MuSUSY*(-8 + 2*lmMst1 + pow(lmMst1,2) - 
                  6*lmMst2 - pow(lmMst2,2) - 2*z2)) + 
            6*Dmglst1*Mgl*pow(Mst2,2)*
             (2*(1 + lmMst2)*pow(Mst1,2)*Tbeta + 
               (1 - 2*lmMst1)*pow(Mst2,2)*Tbeta + 
               Mst1*MuSUSY*(2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                  pow(lmMst2,2) - 2*(6 + z2))) + 
            pow(Dmglst1,2)*(18*(1 + lmMst2)*pow(Mst1,2)*
                pow(Mst2,2)*Tbeta + 
               (17 - 18*lmMst1)*pow(Mst2,4)*Tbeta + 
               12*pow(Mst1,3)*MuSUSY*
                (4 + 3*pow(lmMst1,2) + 7*lmMst2 + 3*pow(lmMst2,2) - 
                  lmMst1*(7 + 6*lmMst2) + 6*z2) + 
               6*Mst1*pow(Mst2,2)*MuSUSY*
                (2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - 
                  pow(lmMst2,2) - 2*(8 + z2)))))/(pow(Mst2,4)*Tbeta) + 
       (9*Mt*pow(s2t,2)*(Dmglst1*Mgl*
             (4*pow(Mst2,2)*MuSUSY + 36*Mst1*pow(Mst2,2)*Tbeta - 
               2*lmMst1*pow(Mst2,2)*(2*MuSUSY + 3*Mst1*Tbeta) + 
               pow(lmMst1,2)*Mst1*
                (4*Mst1*MuSUSY - 3*pow(Mst2,2)*Tbeta) + 
               pow(lmMst2,2)*Mst1*
                (-4*Mst1*MuSUSY + 3*pow(Mst2,2)*Tbeta) + 
               2*lmMst2*Mst1*(-2*Mst1*MuSUSY + 9*pow(Mst2,2)*Tbeta) - 
               8*pow(Mst1,2)*MuSUSY*z2 + 6*Mst1*pow(Mst2,2)*Tbeta*z2) 
+ pow(Mgl,2)*pow(Mst2,2)*(2*MuSUSY*
                (-7 - 7*lmMst2 - 2*pow(lmMst2,2) + 
                  2*lmMst1*(1 + lmMst2) + z2) + 
               3*Mst1*Tbeta*(8 - 2*lmMst1 - pow(lmMst1,2) + 6*lmMst2 + 
                  pow(lmMst2,2) + 2*z2)) - 
            pow(Dmglst1,2)*(2*(-4 + 3*lmMst1)*pow(Mst2,2)*MuSUSY + 
               2*pow(Mst1,2)*MuSUSY*
                (4 - 3*pow(lmMst1,2) + 3*lmMst2 + 3*pow(lmMst2,2) + 
                  6*z2) + 6*pow(Mst1,3)*Tbeta*
                (6 + 3*pow(lmMst1,2) + 7*lmMst2 + 3*pow(lmMst2,2) - 
                  lmMst1*(7 + 6*lmMst2) + 6*z2) + 
               3*Mst1*pow(Mst2,2)*Tbeta*
                (2*lmMst1 + pow(lmMst1,2) - 6*lmMst2 - pow(lmMst2,2) - 
                  2*(8 + z2)))))/(pow(Mst2,2)*Tbeta)))/(27.*pow(Mgl,2)) + 
  pow(Al4p,2)*Mt*threeLoopFlag*
   ((MuSUSY*pow(s2t,3)*((2160*pow(Msq,2)*pow(Mst2,2)*
             (-1 + shiftst1)*(-1 + 2*lmMsq + 2*z2))/pow(Mst1,2) - 
          2160*pow(Msq,2)*(shiftst1 - shiftst2 + 
             lmMst1*(-2 + shiftst1 + shiftst2) - 
             lmMst2*(-2 + shiftst1 + shiftst2))*(-1 + 2*lmMsq + 2*z2) + 
          (6*pow(Dmglst1,2)*
             (60*pow(Mst1,2)*pow(Mst2,2)*
                (108 - 133*lmMst1 - 9*pow(lmMst1,2) + 
                  2*lmMsq*(32 + 9*lmMst1 - 9*lmMst2) + 69*lmMst2 + 
                  9*pow(lmMst2,2) + 18*z2) + 
               pow(Msq,2)*(pow(Mst2,2)*
                   (6457 + 1620*pow(lmMsq,2) - 982*lmMst1 + 
                     834*pow(lmMst1,2) - 60*lmMsq*(-67 + 54*lmMst1) - 
                     2670*lmMst2 + 1980*lmMst1*lmMst2 + 
                     162*pow(lmMst2,2) + 3564*z2 - 9198*z3) + 
                  pow(Mst1,2)*
                   (-709 + 432*B4 + 360*DN - 15720*lmMsq + 13198*lmMst1 + 
                     6480*lmMsq*lmMst1 - 3240*pow(lmMsq,2)*lmMst1 - 
                     8586*pow(lmMst1,2) + 3240*lmMsq*pow(lmMst1,2) - 
                     780*pow(lmMst1,3) + 12402*lmMst2 - 
                     6480*lmMsq*lmMst2 + 3240*pow(lmMsq,2)*lmMst2 + 
                     1116*lmMst1*lmMst2 - 2844*pow(lmMst1,2)*lmMst2 + 
                     13230*pow(lmMst2,2) - 3240*lmMsq*pow(lmMst2,2) - 
                     1764*lmMst1*pow(lmMst2,2) + 5388*pow(lmMst2,3) + 
                     24516*z2 - 6480*lmMsq*z2 - 10008*lmMst1*z2 + 
                     22680*lmMst2*z2 - 288*pow(z2,2) + 16254*z3 + 
                     9936*lmMst1*z3 - 9936*lmMst2*z3 - 19080*z4))))/
           (pow(Mgl,2)*pow(Msq,2)) + 
          (12*Dmglst1*(20*pow(Mst1,2)*pow(Mst2,2)*
                (82 - 93*lmMst1 - 9*pow(lmMst1,2) + 
                  6*lmMsq*(4 + 3*lmMst1 - 3*lmMst2) + 69*lmMst2 + 
                  9*pow(lmMst2,2) + 18*z2) + 
               pow(Msq,2)*(3*pow(Mst2,2)*
                   (7 + 180*pow(lmMsq,2) - 2*lmMst1 + 
                     178*pow(lmMst1,2) - 60*lmMsq*(-5 + 6*lmMst1) - 
                     226*lmMst2 + 220*lmMst1*lmMst2 + 
                     18*pow(lmMst2,2) + 396*z2 - 390*z3) + 
                  pow(Mst1,2)*
                   (2323 + 144*B4 + 120*DN - 2880*lmMsq + 1758*lmMst1 + 
                     2160*lmMsq*lmMst1 - 1080*pow(lmMsq,2)*lmMst1 - 
                     3630*pow(lmMst1,2) + 1080*lmMsq*pow(lmMst1,2) - 
                     260*pow(lmMst1,3) + 3426*lmMst2 - 
                     2160*lmMsq*lmMst2 + 1080*pow(lmMsq,2)*lmMst2 + 
                     372*lmMst1*lmMst2 - 948*pow(lmMst1,2)*lmMst2 + 
                     4410*pow(lmMst2,2) - 1080*lmMsq*pow(lmMst2,2) - 
                     588*lmMst1*pow(lmMst2,2) + 1796*pow(lmMst2,3) + 
                     8172*z2 - 2160*lmMsq*z2 - 3336*lmMst1*z2 + 
                     7560*lmMst2*z2 - 96*pow(z2,2) + 3690*z3 + 
                     3312*lmMst1*z3 - 3312*lmMst2*z3 - 6360*z4))))/
           (Mgl*pow(Msq,2)) + 
          pow(Mst2,2)*(53965 + 2592*B4 - 288*DN - 13320*lmMsq + 
             5400*pow(lmMsq,2) - 22686*lmMst1 + 1800*lmMsq*lmMst1 - 
             1080*pow(lmMsq,2)*lmMst1 + 4122*pow(lmMst1,2) - 
             1080*lmMsq*pow(lmMst1,2) + 396*pow(lmMst1,3) + 
             84822*lmMst2 - 12600*lmMsq*lmMst2 + 
             1080*pow(lmMsq,2)*lmMst2 - 20988*lmMst1*lmMst2 + 
             4320*lmMsq*lmMst1*lmMst2 - 108*pow(lmMst1,2)*lmMst2 + 
             39474*pow(lmMst2,2) - 3240*lmMsq*pow(lmMst2,2) - 
             7956*lmMst1*pow(lmMst2,2) + 7668*pow(lmMst2,3) + 
             192*OepS2 + 21384*S2 - 3888*lmMst1*S2 + 3888*lmMst2*S2 + 
             216*shiftst3 + 216*lmMst1*shiftst3 - 648*lmMst2*shiftst3 - 
             432*lmMst1*lmMst2*shiftst3 + 432*pow(lmMst2,2)*shiftst3 - 
             288*T1ep - 23976*z2 + 2160*lmMsq*z2 + 2664*lmMst1*z2 - 
             10728*lmMst2*z2 - 432*shiftst3*z2 - 432*lmMst1*shiftst3*z2 + 
             432*lmMst2*shiftst3*z2 - 2520*pow(z2,2) + 23616*z3 + 17424*z4
)))/1296. - (Mst1*pow(Mt,3)*MuSUSY*
        (Dmglst1*Mgl*(-80*pow(Msq,2)*pow(Mst2,4)*Tbeta*
              (-17 + 18*pow(lmMsq,2) + 33*lmMt - 
                6*lmMsq*(5 + 3*lmMst2 + 3*lmMt) + 
                3*lmMst2*(-1 + 6*lmMt) + 36*z2) - 
             5*pow(Mst2,6)*Tbeta*
              (-299 + 72*pow(lmMsq,2) + 78*lmMt - 
                12*lmMsq*(-5 + 6*lmMst2 + 6*lmMt) + 
                6*lmMst2*(-23 + 12*lmMt) + 144*z2) - 
             8*pow(Msq,4)*(12*Mst1*MuSUSY*
                 (-735 + 6*B4 + 3*DN + 78*lmMst1 - 6*pow(lmMst1,2) + 
                   26*pow(lmMst1,3) - 510*lmMst2 + 36*lmMst1*lmMst2 - 
                   6*pow(lmMst1,2)*lmMst2 - 126*pow(lmMst2,2) - 
                   18*lmMst1*pow(lmMst2,2) - 2*pow(lmMst2,3) - 
                   48*lmMt + 72*lmMst1*lmMt - 24*pow(lmMst1,2)*lmMt - 
                   72*lmMst2*lmMt + 48*lmMst1*lmMst2*lmMt - 
                   24*pow(lmMst2,2)*lmMt - 330*z2 - 96*lmMst2*z2 + 
                   117*z3 + 18*lmMst1*z3 - 18*lmMst2*z3 - 45*z4) + 
                pow(Mst2,2)*Tbeta*
                 (1846 - 66*pow(lmMst1,3) + 
                   270*pow(lmMsq,2)*(lmMst1 - lmMst2) - 1057*lmMst2 - 
                   306*pow(lmMst2,2) - 42*pow(lmMst2,3) - 3315*lmMt - 
                   1824*lmMst2*lmMt - 324*pow(lmMst2,2)*lmMt - 
                   864*pow(lmMt,2) - 432*lmMst2*pow(lmMt,2) + 
                   6*pow(lmMst1,2)*(352 + 15*lmMst2 + 42*lmMt) + 
                   30*lmMsq*(151 + 51*lmMt + 9*lmMst2*(3 + 2*lmMt) - 
                      6*lmMst1*(13 + 3*lmMt)) - 48*z2 - 324*lmMst2*z2 - 
                   252*lmMt*z2 + 72*pow(z2,2) + 
                   2*lmMst1*(-2534 + 201*lmMst2 + 9*pow(lmMst2,2) - 
                      192*lmMt + 36*lmMst2*lmMt + 216*pow(lmMt,2) + 
                      288*z2 - 108*z3) + 666*z3 + 216*lmMst2*z3 - 36*z4))) 
+ pow(Mgl,2)*pow(Mst2,2)*Tbeta*
           (-80*pow(Msq,2)*pow(Mst2,2)*
              (-17 + 18*pow(lmMsq,2) + 33*lmMt - 
                6*lmMsq*(5 + 3*lmMst2 + 3*lmMt) + 
                3*lmMst2*(-1 + 6*lmMt) + 36*z2) - 
             5*pow(Mst2,4)*(-299 + 72*pow(lmMsq,2) + 78*lmMt - 
                12*lmMsq*(-5 + 6*lmMst2 + 6*lmMt) + 
                6*lmMst2*(-23 + 12*lmMt) + 144*z2) - 
             24*pow(Msq,4)*(-212 - 22*pow(lmMst1,3) + 
                90*pow(lmMsq,2)*(lmMst1 - lmMst2) - 225*lmMst2 - 
                102*pow(lmMst2,2) - 14*pow(lmMst2,3) - 795*lmMt - 
                606*lmMst2*lmMt - 108*pow(lmMst2,2)*lmMt - 
                144*pow(lmMt,2) - 144*lmMst2*pow(lmMt,2) + 
                6*pow(lmMst1,2)*(67 + 5*lmMst2 + 14*lmMt) + 
                90*lmMsq*(7 + 3*lmMst2 + 3*lmMt + 2*lmMst2*lmMt - 
                   2*lmMst1*(3 + lmMt)) - 16*z2 - 108*lmMst2*z2 - 
                84*lmMt*z2 + 24*pow(z2,2) + 
                6*lmMst1*(-54 + 22*lmMst2 + pow(lmMst2,2) + 37*lmMt + 
                   4*lmMst2*lmMt + 24*pow(lmMt,2) + 32*z2 - 12*z3) + 
                324*z3 + 72*lmMst2*z3 - 12*z4)) + 
          pow(Dmglst1,2)*(-80*pow(Msq,2)*pow(Mst2,2)*Tbeta*
              (3*(245 + 6*lmMst1*(-25 + 6*lmMsq - 6*lmMt) + 84*lmMt + 
                   lmMst2*(66 - 36*lmMsq + 36*lmMt))*pow(Mst1,2) + 
                pow(Mst2,2)*(-17 + 18*pow(lmMsq,2) + 33*lmMt - 
                   6*lmMsq*(5 + 3*lmMst2 + 3*lmMt) + 
                   3*lmMst2*(-1 + 6*lmMt) + 36*z2)) - 
             5*pow(Mst2,4)*Tbeta*
              (pow(Mst2,2)*(-299 + 72*pow(lmMsq,2) - 138*lmMst2 + 
                   78*lmMt + 72*lmMst2*lmMt - 
                   12*lmMsq*(-5 + 6*lmMst2 + 6*lmMt) + 144*z2) + 
                6*pow(Mst1,2)*
                 (-185 + 72*pow(lmMsq,2) - 66*lmMst2 + 78*lmMt + 
                   72*lmMst2*lmMt - 12*lmMsq*(1 + 6*lmMst2 + 6*lmMt) + 
                   144*z2)) + 4*pow(Msq,4)*
              (pow(Mst1,2)*Tbeta*
                 (-32085 + 1368*pow(lmMst1,3) - 23606*lmMst2 - 
                   18846*pow(lmMst2,2) - 5094*pow(lmMst2,3) + 
                   6*pow(lmMst1,2)*(-601 + 567*lmMst2 - 1251*lmMt) + 
                   17100*lmMt + 8088*lmMst2*lmMt + 
                   1134*pow(lmMst2,2)*lmMt + 5040*pow(lmMt,2) + 
                   2592*lmMst2*pow(lmMt,2) - 50076*z2 - 
                   29268*lmMst2*z2 - 756*lmMt*z2 + 
                   180*lmMsq*(-31 + 78*lmMst2 + 36*pow(lmMst2,2) - 
                      84*lmMt - 36*lmMst2*lmMt + 
                      lmMst1*(6 - 36*lmMst2 + 36*lmMt) + 72*z2) + 
                   2*lmMst1*(5093 + 162*pow(lmMst2,2) + 5700*lmMt - 
                      1296*pow(lmMt,2) + 6*lmMst2*(-173 + 531*lmMt) + 
                      1188*z2) + 32355*z3) - 
                4*Mst1*MuSUSY*(-9893 + 54*B4 + 27*DN + 50*lmMst1 - 
                   138*pow(lmMst1,2) + 234*pow(lmMst1,3) - 
                   4538*lmMst2 + 300*lmMst1*lmMst2 - 
                   54*pow(lmMst1,2)*lmMst2 - 1026*pow(lmMst2,2) - 
                   162*lmMst1*pow(lmMst2,2) - 18*pow(lmMst2,3) - 
                   696*lmMt + 840*lmMst1*lmMt - 216*pow(lmMst1,2)*lmMt - 
                   840*lmMst2*lmMt + 432*lmMst1*lmMst2*lmMt - 
                   216*pow(lmMst2,2)*lmMt - 2970*z2 - 864*lmMst2*z2 + 
                   3960*z3 + 162*lmMst1*z3 - 162*lmMst2*z3 - 405*z4) + 
                pow(Mst2,2)*Tbeta*
                 (-33943 + 132*pow(lmMst1,3) - 
                   540*pow(lmMsq,2)*(lmMst1 - lmMst2) + 2918*lmMst2 + 
                   612*pow(lmMst2,2) + 84*pow(lmMst2,3) + 5778*lmMt + 
                   3702*lmMst2*lmMt + 648*pow(lmMst2,2)*lmMt + 
                   2448*pow(lmMt,2) + 864*lmMst2*pow(lmMt,2) - 
                   6*pow(lmMst1,2)*(799 + 30*lmMst2 + 84*lmMt) - 
                   60*lmMsq*(244 + 69*lmMt + 9*lmMst2*(3 + 2*lmMt) - 
                      6*lmMst1*(16 + 3*lmMt)) + 96*z2 + 648*lmMst2*z2 + 
                   504*lmMt*z2 - 144*pow(z2,2) - 
                   2*lmMst1*(-10100 + 18*pow(lmMst2,2) - 1173*lmMt + 
                      432*pow(lmMt,2) + lmMst2*(429 + 72*lmMt) + 
                      576*z2 - 216*z3) + 15255*z3 - 432*lmMst2*z3 + 72*z4)))
))/(162.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)*Tbeta) + 
     Mt*MuSUSY*pow(s2t,2)*(Mst1*
         (369.9166666666667 - (34*B4)/3. - DN/3. - 120*lmMsq + 
           20*pow(lmMsq,2) - (79*lmMst1)/6. + 30*lmMsq*lmMst1 - 
           10*pow(lmMsq,2)*lmMst1 - (167*pow(lmMst1,2))/6. + 
           10*lmMsq*pow(lmMst1,2) - (50*pow(lmMst1,3))/9. + 
           (2135*lmMst2)/6. - 70*lmMsq*lmMst2 + 10*pow(lmMsq,2)*lmMst2 - 
           (59*lmMst1*lmMst2)/3. - 10*pow(lmMst1,2)*lmMst2 + 
           (797*pow(lmMst2,2))/6. - 10*lmMsq*pow(lmMst2,2) - 
           (2*lmMst1*pow(lmMst2,2))/3. + (146*pow(lmMst2,3))/9. + 
           (10*pow(Mst2,2))/(3.*pow(Msq,2)) + 209*z2 - 20*lmMsq*z2 - 
           (64*lmMst1*z2)/3. + 64*lmMst2*z2 + (32*pow(z2,2))/3. - 
           (266*z3)/3. + 6*lmMst1*z3 - 6*lmMst2*z3 - (241*z4)/3.) + 
        (MuSUSY*(-83.61265432098766 - 4*B4 + (4*DN)/9. + (185*lmMsq)/9. - 
             (25*pow(lmMsq,2))/3. + (3781*lmMst1)/108. - 
             (25*lmMsq*lmMst1)/9. + (5*pow(lmMsq,2)*lmMst1)/3. - 
             (229*pow(lmMst1,2))/36. + (5*lmMsq*pow(lmMst1,2))/3. - 
             (11*pow(lmMst1,3))/18. - (14065*lmMst2)/108. + 
             (175*lmMsq*lmMst2)/9. - (5*pow(lmMsq,2)*lmMst2)/3. + 
             (583*lmMst1*lmMst2)/18. - (20*lmMsq*lmMst1*lmMst2)/3. + 
             (pow(lmMst1,2)*lmMst2)/6. - (731*pow(lmMst2,2))/12. + 
             5*lmMsq*pow(lmMst2,2) + (221*lmMst1*pow(lmMst2,2))/18. - 
             (71*pow(lmMst2,3))/6. + 
             ((939 + 30*lmMsq*(-12 + 5*lmMst1 - 5*lmMst2) + 
                  760*lmMst2 + 150*pow(lmMst2,2) - 
                  50*lmMst1*(8 + 3*lmMst2))*pow(Mst2,2))/
              (135.*pow(Msq,2)) - (8*OepS2)/27. - 33*S2 + 6*lmMst1*S2 - 
             6*lmMst2*S2 + (2*shiftst3)/3. - (2*lmMst1*shiftst3)/3. - 
             (2*lmMst2*shiftst3)/3. + (4*lmMst1*lmMst2*shiftst3)/3. - 
             (4*pow(lmMst2,2)*shiftst3)/3. + (4*T1ep)/9. + (113*z2)/3. - 
             (10*lmMsq*z2)/3. - (37*lmMst1*z2)/9. + (149*lmMst2*z2)/9. - 
             (4*shiftst3*z2)/3. + (4*lmMst1*shiftst3*z2)/3. - 
             (4*lmMst2*shiftst3*z2)/3. + (35*pow(z2,2))/9. + 
             (10*pow(Msq,2)*
                (1 + 2*lmMst1*(-1 + shiftst1) - 
                  2*lmMst2*(-1 + shiftst1) - 2*shiftst1 + shiftst2)*
                (-1 + 2*lmMsq + 2*z2))/(3.*pow(Mst2,2)) - 
             (10*pow(Msq,2)*(-1 + shiftst1)*(-1 + 2*lmMsq + 2*z2) + 
                pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2))/
              (3.*pow(Mst1,2)) - (328*z3)/9. - 
             (pow(Dmglst1,2)*
                (-135*pow(Mst1,2)*pow(Mst2,4) + 
                  60*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                   (108 - 133*lmMst1 - 9*pow(lmMst1,2) + 
                     2*lmMsq*(32 + 9*lmMst1 - 9*lmMst2) + 69*lmMst2 + 
                     9*pow(lmMst2,2) + 18*z2) + 
                  pow(Msq,4)*
                   (pow(Mst2,2)*
                      (6457 + 1620*pow(lmMsq,2) - 982*lmMst1 + 
                        834*pow(lmMst1,2) - 
                        60*lmMsq*(-67 + 54*lmMst1) - 2670*lmMst2 + 
                        1980*lmMst1*lmMst2 + 162*pow(lmMst2,2) + 
                        3564*z2 - 9198*z3) + 
                     12*pow(Mst1,2)*
                      (479 + 36*B4 + 30*DN - 975*lmMsq + 
                        135*pow(lmMsq,2) + 1018*lmMst1 + 
                        270*lmMsq*lmMst1 - 270*pow(lmMsq,2)*lmMst1 - 
                        646*pow(lmMst1,2) + 
                        270*lmMsq*pow(lmMst1,2) - 65*pow(lmMst1,3) + 
                        811*lmMst2 - 540*lmMsq*lmMst2 + 
                        270*pow(lmMsq,2)*lmMst2 + 258*lmMst1*lmMst2 - 
                        237*pow(lmMst1,2)*lmMst2 + 
                        1116*pow(lmMst2,2) - 
                        270*lmMsq*pow(lmMst2,2) - 
                        147*lmMst1*pow(lmMst2,2) + 
                        449*pow(lmMst2,3) + 2340*z2 - 540*lmMsq*z2 - 
                        834*lmMst1*z2 + 1890*lmMst2*z2 - 
                        24*pow(z2,2) + 588*z3 + 828*lmMst1*z3 - 
                        828*lmMst2*z3 - 1590*z4))))/
              (108.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,2)) - 
             (Dmglst1*(-45*pow(Mst1,2)*pow(Mst2,4) + 
                  20*pow(Msq,2)*pow(Mst1,2)*pow(Mst2,2)*
                   (82 - 93*lmMst1 - 9*pow(lmMst1,2) + 
                     6*lmMsq*(4 + 3*lmMst1 - 3*lmMst2) + 69*lmMst2 + 
                     9*pow(lmMst2,2) + 18*z2) + 
                  pow(Msq,4)*
                   (3*pow(Mst2,2)*
                      (7 + 180*pow(lmMsq,2) - 2*lmMst1 + 
                        178*pow(lmMst1,2) - 
                        60*lmMsq*(-5 + 6*lmMst1) - 226*lmMst2 + 
                        220*lmMst1*lmMst2 + 18*pow(lmMst2,2) + 
                        396*z2 - 390*z3) + 
                     4*pow(Mst1,2)*
                      (586 + 36*B4 + 30*DN - 495*lmMsq + 
                        135*pow(lmMsq,2) + 438*lmMst1 + 
                        270*lmMsq*lmMst1 - 270*pow(lmMsq,2)*lmMst1 - 
                        774*pow(lmMst1,2) + 
                        270*lmMsq*pow(lmMst1,2) - 65*pow(lmMst1,3) + 
                        687*lmMst2 - 540*lmMsq*lmMst2 + 
                        270*pow(lmMsq,2)*lmMst2 + 258*lmMst1*lmMst2 - 
                        237*pow(lmMst1,2)*lmMst2 + 
                        1116*pow(lmMst2,2) - 
                        270*lmMsq*pow(lmMst2,2) - 
                        147*lmMst1*pow(lmMst2,2) + 
                        449*pow(lmMst2,3) + 2340*z2 - 540*lmMsq*z2 - 
                        834*lmMst1*z2 + 1890*lmMst2*z2 - 
                        24*pow(z2,2) + 630*z3 + 828*lmMst1*z3 - 
                        828*lmMst2*z3 - 1590*z4))))/
              (54.*Mgl*pow(Msq,4)*pow(Mst2,2)) - (242*z4)/9.))/Tbeta - 
        (Dmglst1*Mst1*(-944.75 + 34*B4 + DN + 540*lmMsq - 
             60*pow(lmMsq,2) - (365*lmMst1)/2. - 90*lmMsq*lmMst1 + 
             30*pow(lmMsq,2)*lmMst1 + (39*pow(lmMst1,2))/2. - 
             30*lmMsq*pow(lmMst1,2) + (50*pow(lmMst1,3))/3. - 
             (2331*lmMst2)/2. + 210*lmMsq*lmMst2 - 
             30*pow(lmMsq,2)*lmMst2 + 59*lmMst1*lmMst2 + 
             30*pow(lmMst1,2)*lmMst2 - (797*pow(lmMst2,2))/2. + 
             30*lmMsq*pow(lmMst2,2) + 2*lmMst1*pow(lmMst2,2) - 
             (146*pow(lmMst2,3))/3. - (10*pow(Mst2,2))/pow(Msq,2) - 
             627*z2 + 60*lmMsq*z2 + 64*lmMst1*z2 - 192*lmMst2*z2 - 
             32*pow(z2,2) + 116*z3 - 18*lmMst1*z3 + 18*lmMst2*z3 + 241*z4
))/(3.*Mgl) + (pow(Dmglst1,2)*Mst1*
           (-413 - 408*B4 - 12*DN - 8520*lmMsq + 720*pow(lmMsq,2) + 
             3146*lmMst1 + 1080*lmMsq*lmMst1 - 360*pow(lmMsq,2)*lmMst1 + 
             918*pow(lmMst1,2) + 360*lmMsq*pow(lmMst1,2) - 
             200*pow(lmMst1,3) + 15206*lmMst2 - 2520*lmMsq*lmMst2 + 
             360*pow(lmMsq,2)*lmMst2 - 708*lmMst1*lmMst2 - 
             360*pow(lmMst1,2)*lmMst2 + 4782*pow(lmMst2,2) - 
             360*lmMsq*pow(lmMst2,2) - 24*lmMst1*pow(lmMst2,2) + 
             584*pow(lmMst2,3) + (120*pow(Mst2,2))/pow(Msq,2) + 
             7524*z2 - 720*lmMsq*z2 - 768*lmMst1*z2 + 2304*lmMst2*z2 + 
             384*pow(z2,2) + 6708*z3 + 216*lmMst1*z3 - 216*lmMst2*z3 - 
             2892*z4 + 36*pow(Mst1,2)*
              ((5*pow(Mst2,2))/pow(Msq,4) - 
                (10*(311 - 66*lmMst1 - 18*pow(lmMst1,2) + 
                     36*lmMsq*(-2 + lmMst1 - lmMst2) + 138*lmMst2 + 
                     18*pow(lmMst2,2) + 36*z2))/(9.*pow(Msq,2)) + 
                (-354.6111111111111 - 76*B4 + 2*DN + 460*lmMsq + 
                   (1267*lmMst1)/9. - 400*lmMsq*lmMst1 + 
                   (901*pow(lmMst1,2))/3. + 120*lmMsq*pow(lmMst1,2) - 
                   (451*pow(lmMst1,3))/3. - (7219*lmMst2)/9. + 
                   400*lmMsq*lmMst2 + (374*lmMst1*lmMst2)/3. - 
                   240*lmMsq*lmMst1*lmMst2 + 131*pow(lmMst1,2)*lmMst2 - 
                   393*pow(lmMst2,2) + 120*lmMsq*pow(lmMst2,2) + 
                   125*lmMst1*pow(lmMst2,2) - (317*pow(lmMst2,3))/3. - 
                   (2374*z2)/3. + 240*lmMsq*z2 + 114*lmMst1*z2 - 
                   498*lmMst2*z2 + 80*pow(z2,2) + 234*z3 - 
                   468*lmMst1*z3 + 468*lmMst2*z3 + 410*z4)/pow(Mst2,2))))/
         (36.*pow(Mgl,2))) + pow(Mt,2)*MuSUSY*s2t*
      (-14.558641975308642 + (8*DN)/9. + (10*lmMsq)/3. - 10*pow(lmMsq,2) + 
        (908*lmMst1)/27. + (40*lmMsq*lmMst1)/9. + 
        (10*pow(lmMsq,2)*lmMst1)/3. - (82*pow(lmMst1,2))/9. + 
        (58*pow(lmMst1,3))/27. - (1430*lmMst2)/27. + 
        (140*lmMsq*lmMst2)/9. - (10*pow(lmMsq,2)*lmMst2)/3. + 
        (224*lmMst1*lmMst2)/9. - (20*lmMsq*lmMst1*lmMst2)/3. + 
        (8*pow(lmMst1,2)*lmMst2)/3. - (382*pow(lmMst2,2))/9. + 
        (20*lmMsq*pow(lmMst2,2))/3. + (88*lmMst1*pow(lmMst2,2))/9. - 
        (394*pow(lmMst2,3))/27. + 
        (2*(5108 + 900*pow(lmMsq,2) + 
             15*lmMsq*(-218 + 75*lmMst1 - 195*lmMst2) + 6270*lmMst2 + 
             2025*pow(lmMst2,2) - 375*lmMst1*(8 + 3*lmMst2))*pow(Mst2,2)
)/(2025.*pow(Msq,2)) - (8*OepS2)/27. + 3*S2 + 6*lmMst1*S2 - 6*lmMst2*S2 + 
        (4*T1ep)/9. - (587*z2)/18. + (4*lmMst1*z2)/3. - (4*lmMst2*z2)/3. - 
        (5*pow(z2,2))/9. + (20*pow(Msq,2)*(-1 + shiftst2)*
           (-1 + 2*lmMsq + 2*z2))/(3.*pow(Mst2,2)) - 
        (20*pow(Msq,2)*(-1 + shiftst1)*(-1 + 2*lmMsq + 2*z2) + 
           2*pow(Mst2,2)*(-1 + shiftst3)*(-1 + 2*lmMst2 + 2*z2))/
         (3.*pow(Mst1,2)) - (86*z3)/9. - 
        (Dmglst1*(1080*(-7 + 20*lmMsq - 26*lmMst1 + 6*lmMst2)*pow(Msq,2)*
              pow(Mst1,2)*pow(Mst2,2) + 
             135*(13 - 12*lmMsq + 12*lmMst2)*pow(Mst1,2)*pow(Mst2,4) + 
             2*pow(Msq,4)*(18*pow(Mst2,2)*
                 (-158 + 270*pow(lmMsq,2) - 70*lmMst1 + 
                   459*pow(lmMst1,2) - 60*lmMsq*(-4 + 9*lmMst1) - 
                   96*lmMst2 + 138*lmMst1*lmMst2 + 27*pow(lmMst2,2) + 
                   594*z2 - 330*z3) + 
                pow(Mst1,2)*(-164809 + 864*B4 + 432*DN + 14580*lmMsq - 
                   4860*pow(lmMsq,2) + 9366*lmMst1 - 
                   1854*pow(lmMst1,2) + 7200*pow(lmMst1,3) - 
                   141450*lmMst2 + 9720*lmMsq*lmMst2 + 5436*lmMst1*lmMst2 - 
                   2592*pow(lmMst1,2)*lmMst2 - 39006*pow(lmMst2,2) - 
                   6048*lmMst1*pow(lmMst2,2) + 1440*pow(lmMst2,3) - 
                   10368*lmMt + 15552*lmMst1*lmMt - 
                   5184*pow(lmMst1,2)*lmMt - 15552*lmMst2*lmMt + 
                   10368*lmMst1*lmMst2*lmMt - 5184*pow(lmMst2,2)*lmMt - 
                   99972*z2 - 4320*lmMst1*z2 - 16416*lmMst2*z2 + 34344*z3 + 
                   2592*lmMst1*z3 - 2592*lmMst2*z3 - 6480*z4))))/
         (486.*Mgl*pow(Msq,4)*pow(Mst2,2)) - 2*z4 + 
        (pow(Dmglst1,2)*(-163 - 30*pow(lmMsq,2) - 
             (331*pow(lmMst1,2))/9. + 
             lmMsq*(-57.77777777777778 + 60*lmMst1) + (148*lmMst2)/9. - 
             3*pow(lmMst2,2) - (2*lmMst1*(-731 + 207*lmMst2))/27. - 
             66*z2 + (3479*z3)/18. + 
             pow(Mst1,2)*((-10*
                   (-9 + 100*lmMsq - 118*lmMst1 + 18*lmMst2))/
                 (9.*pow(Msq,2)) + 
                ((-5.416666666666667 + 5*lmMsq - 5*lmMst2)*pow(Mst2,2))/
                 pow(Msq,4) + 
                (1534.2283950617284 - (16*B4)/3. - (8*DN)/3. - 90*lmMsq + 
                   30*pow(lmMsq,2) + (1507*lmMst1)/27. + 
                   (215*pow(lmMst1,2))/9. - (400*pow(lmMst1,3))/9. + 
                   (22907*lmMst2)/27. - 60*lmMsq*lmMst2 - 
                   30*lmMst1*lmMst2 + 16*pow(lmMst1,2)*lmMst2 + 
                   (2023*pow(lmMst2,2))/9. + 
                   (112*lmMst1*pow(lmMst2,2))/3. - 
                   (80*pow(lmMst2,3))/9. + (928*lmMt)/9. - 
                   (1120*lmMst1*lmMt)/9. + 32*pow(lmMst1,2)*lmMt + 
                   (1120*lmMst2*lmMt)/9. - 64*lmMst1*lmMst2*lmMt + 
                   32*pow(lmMst2,2)*lmMt + (5554*z2)/9. + 
                   (80*lmMst1*z2)/3. + (304*lmMst2*z2)/3. - (6292*z3)/9. - 
                   16*lmMst1*z3 + 16*lmMst2*z3 + 40*z4)/pow(Mst2,2))))/
         pow(Mgl,2) + (Mst1*MuSUSY*
           (Dmglst1*Mgl*pow(Mst2,2)*
              (-720*pow(Msq,2)*pow(Mst2,2) + 
                5*(11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                6*pow(Msq,4)*
                 (-11337 + 408*B4 + 12*DN + 6480*lmMsq - 
                   720*pow(lmMsq,2) - 2190*lmMst1 - 1080*lmMsq*lmMst1 + 
                   360*pow(lmMsq,2)*lmMst1 + 234*pow(lmMst1,2) - 
                   360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                   13986*lmMst2 + 2520*lmMsq*lmMst2 - 
                   360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                   360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                   360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                   584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                   768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) + 
                   1392*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4)) + 
             pow(Mgl,2)*pow(Mst2,2)*
              (-720*pow(Msq,2)*pow(Mst2,2) + 
                5*(11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,4) + 
                6*pow(Msq,4)*
                 (-13317 + 408*B4 + 12*DN + 4320*lmMsq - 
                   720*pow(lmMsq,2) + 474*lmMst1 - 1080*lmMsq*lmMst1 + 
                   360*pow(lmMsq,2)*lmMst1 + 1002*pow(lmMst1,2) - 
                   360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                   12810*lmMst2 + 2520*lmMsq*lmMst2 - 
                   360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                   360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                   360*lmMsq*pow(lmMst2,2) + 24*lmMst1*pow(lmMst2,2) - 
                   584*pow(lmMst2,3) - 7524*z2 + 720*lmMsq*z2 + 
                   768*lmMst1*z2 - 2304*lmMst2*z2 - 384*pow(z2,2) + 
                   3192*z3 - 216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4)) + 
             pow(Dmglst1,2)*(-1080*pow(Mst1,2)*pow(Mst2,4) + 
                5*(11 - 12*lmMsq + 12*lmMst2)*pow(Mst2,6) + 
                240*pow(Msq,2)*pow(Mst2,2)*
                 (-3*pow(Mst2,2) + 
                   pow(Mst1,2)*
                    (311 - 66*lmMst1 - 18*pow(lmMst1,2) + 
                      36*lmMsq*(-2 + lmMst1 - lmMst2) + 138*lmMst2 + 
                      18*pow(lmMst2,2) + 36*z2)) + 
                6*pow(Msq,4)*
                 (4*pow(Mst1,2)*
                    (6129 + 684*B4 - 18*DN - 3630*lmMsq - 1506*lmMst1 + 
                      3600*lmMsq*lmMst1 - 2991*pow(lmMst1,2) - 
                      1080*lmMsq*pow(lmMst1,2) + 1353*pow(lmMst1,3) + 
                      6914*lmMst2 - 3600*lmMsq*lmMst2 - 
                      1122*lmMst1*lmMst2 + 2160*lmMsq*lmMst1*lmMst2 - 
                      1179*pow(lmMst1,2)*lmMst2 + 3537*pow(lmMst2,2) - 
                      1080*lmMsq*pow(lmMst2,2) - 
                      1125*lmMst1*pow(lmMst2,2) + 951*pow(lmMst2,3) + 
                      7122*z2 - 2160*lmMsq*z2 - 1026*lmMst1*z2 + 
                      4482*lmMst2*z2 - 720*pow(z2,2) - 4131*z3 + 
                      4212*lmMst1*z3 - 4212*lmMst2*z3 - 3690*z4) + 
                   pow(Mst2,2)*
                    (413 + 408*B4 + 12*DN + 8520*lmMsq - 
                      720*pow(lmMsq,2) - 3146*lmMst1 - 1080*lmMsq*lmMst1 + 
                      360*pow(lmMsq,2)*lmMst1 - 918*pow(lmMst1,2) - 
                      360*lmMsq*pow(lmMst1,2) + 200*pow(lmMst1,3) - 
                      15206*lmMst2 + 2520*lmMsq*lmMst2 - 
                      360*pow(lmMsq,2)*lmMst2 + 708*lmMst1*lmMst2 + 
                      360*pow(lmMst1,2)*lmMst2 - 4782*pow(lmMst2,2) + 
                      360*lmMsq*pow(lmMst2,2) + 
                      24*lmMst1*pow(lmMst2,2) - 584*pow(lmMst2,3) - 
                      7524*z2 + 720*lmMsq*z2 + 768*lmMst1*z2 - 
                      2304*lmMst2*z2 - 384*pow(z2,2) - 6708*z3 - 
                      216*lmMst1*z3 + 216*lmMst2*z3 + 2892*z4)))))/
         (162.*pow(Mgl,2)*pow(Msq,4)*pow(Mst2,4)*Tbeta)))
