name: test

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: install conan
      run: pip install conan
    - name: install dependencies
      run: conan install .
    - name: install gfortran on Ubuntu
      run: sudo apt install gfortran
      if: startsWith(matrix.os, 'ubuntu-')
    - name: install gfortran on MacOS
      run: |
        brew gcc
        brew link gcc
      if: startsWith(matrix.os, 'macos-')
    - name: cmake
      run: cmake . -DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake
    - name: make
      run: make
    - name: make test
      run: make test
