name: test

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    env:
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: install conan
      run: pip install conan
    - name: detect conan profile
      run: conan profile detect --force
    - name: install dependencies
      run: conan install . --build=missing -s build_type=${{ env.BUILD_TYPE }}
    - name: cmake
      run: cmake . -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      env:
        FC: gfortran-11
    - name: cmake build
      run: cmake --build . --config ${{ env.BUILD_TYPE }}
    - name: ctest
      run: ctest -C ${{ env.BUILD_TYPE }}
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
